"""Permission service interfaces."""
from typing import List, Optional, Protocol
from internal.types import Tuple


class GraphStore(Protocol):
    """Contract for graph storage implementations."""

    def write_tuple(self, tuple_: Tuple) -> Optional[int]: ...
    def read_tuples(self, subject: str) -> List[Tuple]: ...
    def delete_tuple(self, tuple_: Tuple) -> Optional[int]: ...
    def check(self, subject: str, action: str, object: str) -> bool: ...
    def health(self) -> None: ...
    def close(self) -> None: ...
