// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: metadata.proto

package metadatav1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MetadataService_CreateBucket_FullMethodName        = "/opens3.metadata.v1.MetadataService/CreateBucket"
	MetadataService_DeleteBucket_FullMethodName        = "/opens3.metadata.v1.MetadataService/DeleteBucket"
	MetadataService_GetBucket_FullMethodName           = "/opens3.metadata.v1.MetadataService/GetBucket"
	MetadataService_ListBuckets_FullMethodName         = "/opens3.metadata.v1.MetadataService/ListBuckets"
	MetadataService_HeadBucket_FullMethodName          = "/opens3.metadata.v1.MetadataService/HeadBucket"
	MetadataService_CreateObjectVersion_FullMethodName = "/opens3.metadata.v1.MetadataService/CreateObjectVersion"
	MetadataService_GetObjectMeta_FullMethodName       = "/opens3.metadata.v1.MetadataService/GetObjectMeta"
	MetadataService_DeleteObjectMeta_FullMethodName    = "/opens3.metadata.v1.MetadataService/DeleteObjectMeta"
	MetadataService_ListObjects_FullMethodName         = "/opens3.metadata.v1.MetadataService/ListObjects"
	MetadataService_HealthCheck_FullMethodName         = "/opens3.metadata.v1.MetadataService/HealthCheck"
)

// MetadataServiceClient is the client API for MetadataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MetadataService — единственный источник правды о том, что существует в системе.
// Хранит метаданные бакетов, объектов, версий и blob_id без хранения самих байт.
// Вызывается только Gateway.
//
// Порт: 50052 (конфигурируется через GRPC_PORT)
//
// PostgreSQL схема:
//
//	buckets (id UUID, name TEXT UNIQUE, owner_id UUID, created_at TIMESTAMPTZ)
//	objects (id UUID, bucket_id UUID→buckets, key TEXT, current_version_id UUID, UNIQUE(bucket_id, key))
//	versions (id UUID, object_id UUID→objects, blob_id UUID, size_bytes BIGINT,
//	          etag TEXT, content_type TEXT, created_at TIMESTAMPTZ, is_deleted BOOLEAN)
//
// Kafka:
//
//	Публикует → object-deleted: при DeleteObjectMeta (запускает async-очистку в Data Node и AuthZ)
//	Публикует → bucket-deleted: при DeleteBucket (запускает async-очистку графа в AuthZ)
//	Потребляет ← object-stored: резервный путь для подтверждения версии объекта
type MetadataServiceClient interface {
	// CreateBucket регистрирует новый бакет в метаданных.
	// Ошибки: ALREADY_EXISTS (имя занято), INVALID_ARGUMENT (пустое имя).
	CreateBucket(ctx context.Context, in *CreateBucketRequest, opts ...grpc.CallOption) (*CreateBucketResponse, error)
	// DeleteBucket удаляет метаданные бакета.
	// Ошибки: NOT_FOUND, FAILED_PRECONDITION (бакет не пуст).
	// После успешного удаления публикует событие bucket-deleted в Kafka.
	DeleteBucket(ctx context.Context, in *DeleteBucketRequest, opts ...grpc.CallOption) (*DeleteBucketResponse, error)
	// GetBucket возвращает метаданные бакета по имени.
	// Ошибки: NOT_FOUND.
	GetBucket(ctx context.Context, in *GetBucketRequest, opts ...grpc.CallOption) (*GetBucketResponse, error)
	// ListBuckets возвращает все бакеты, принадлежащие пользователю.
	ListBuckets(ctx context.Context, in *ListBucketsRequest, opts ...grpc.CallOption) (*ListBucketsResponse, error)
	// HeadBucket проверяет, существует ли бакет (для S3 HEAD /{bucket}).
	HeadBucket(ctx context.Context, in *HeadBucketRequest, opts ...grpc.CallOption) (*HeadBucketResponse, error)
	// CreateObjectVersion регистрирует новую версию объекта после того, как Data Node
	// подтвердил запись blob'а на диск. Вызывается Gateway сразу после StoreObject.
	// Ошибки: NOT_FOUND (бакет не существует), INVALID_ARGUMENT.
	CreateObjectVersion(ctx context.Context, in *CreateObjectVersionRequest, opts ...grpc.CallOption) (*CreateObjectVersionResponse, error)
	// GetObjectMeta возвращает метаданные актуальной (или конкретной) версии объекта.
	// blob_id в ответе используется Gateway для вызова Data Node RetrieveObject.
	// Ошибки: NOT_FOUND (бакет или объект не существуют).
	GetObjectMeta(ctx context.Context, in *GetObjectMetaRequest, opts ...grpc.CallOption) (*GetObjectMetaResponse, error)
	// DeleteObjectMeta помечает объект удалённым и публикует ObjectDeleted в Kafka.
	// Асинхронно запускает: удаление файла в Data Node + очистку графа в AuthZ.
	// Ошибки: NOT_FOUND.
	DeleteObjectMeta(ctx context.Context, in *DeleteObjectMetaRequest, opts ...grpc.CallOption) (*DeleteObjectMetaResponse, error)
	// ListObjects возвращает постранично объекты бакета с опциональной фильтрацией по префиксу.
	// Аналог S3 ListObjectsV2. Только метаданные — Data Node не вызывается.
	// Ошибки: NOT_FOUND (бакет не существует).
	ListObjects(ctx context.Context, in *ListObjectsRequest, opts ...grpc.CallOption) (*ListObjectsResponse, error)
	// HealthCheck — стандартный gRPC Health Checking Protocol.
	// Используется Kubernetes liveness/readiness probe и Gateway /ready.
	// NOT_SERVING возвращается если PostgreSQL или Kafka недоступны.
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type metadataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMetadataServiceClient(cc grpc.ClientConnInterface) MetadataServiceClient {
	return &metadataServiceClient{cc}
}

func (c *metadataServiceClient) CreateBucket(ctx context.Context, in *CreateBucketRequest, opts ...grpc.CallOption) (*CreateBucketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBucketResponse)
	err := c.cc.Invoke(ctx, MetadataService_CreateBucket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) DeleteBucket(ctx context.Context, in *DeleteBucketRequest, opts ...grpc.CallOption) (*DeleteBucketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteBucketResponse)
	err := c.cc.Invoke(ctx, MetadataService_DeleteBucket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) GetBucket(ctx context.Context, in *GetBucketRequest, opts ...grpc.CallOption) (*GetBucketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBucketResponse)
	err := c.cc.Invoke(ctx, MetadataService_GetBucket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) ListBuckets(ctx context.Context, in *ListBucketsRequest, opts ...grpc.CallOption) (*ListBucketsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBucketsResponse)
	err := c.cc.Invoke(ctx, MetadataService_ListBuckets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) HeadBucket(ctx context.Context, in *HeadBucketRequest, opts ...grpc.CallOption) (*HeadBucketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeadBucketResponse)
	err := c.cc.Invoke(ctx, MetadataService_HeadBucket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) CreateObjectVersion(ctx context.Context, in *CreateObjectVersionRequest, opts ...grpc.CallOption) (*CreateObjectVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateObjectVersionResponse)
	err := c.cc.Invoke(ctx, MetadataService_CreateObjectVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) GetObjectMeta(ctx context.Context, in *GetObjectMetaRequest, opts ...grpc.CallOption) (*GetObjectMetaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetObjectMetaResponse)
	err := c.cc.Invoke(ctx, MetadataService_GetObjectMeta_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) DeleteObjectMeta(ctx context.Context, in *DeleteObjectMetaRequest, opts ...grpc.CallOption) (*DeleteObjectMetaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteObjectMetaResponse)
	err := c.cc.Invoke(ctx, MetadataService_DeleteObjectMeta_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) ListObjects(ctx context.Context, in *ListObjectsRequest, opts ...grpc.CallOption) (*ListObjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListObjectsResponse)
	err := c.cc.Invoke(ctx, MetadataService_ListObjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, MetadataService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetadataServiceServer is the server API for MetadataService service.
// All implementations must embed UnimplementedMetadataServiceServer
// for forward compatibility.
//
// MetadataService — единственный источник правды о том, что существует в системе.
// Хранит метаданные бакетов, объектов, версий и blob_id без хранения самих байт.
// Вызывается только Gateway.
//
// Порт: 50052 (конфигурируется через GRPC_PORT)
//
// PostgreSQL схема:
//
//	buckets (id UUID, name TEXT UNIQUE, owner_id UUID, created_at TIMESTAMPTZ)
//	objects (id UUID, bucket_id UUID→buckets, key TEXT, current_version_id UUID, UNIQUE(bucket_id, key))
//	versions (id UUID, object_id UUID→objects, blob_id UUID, size_bytes BIGINT,
//	          etag TEXT, content_type TEXT, created_at TIMESTAMPTZ, is_deleted BOOLEAN)
//
// Kafka:
//
//	Публикует → object-deleted: при DeleteObjectMeta (запускает async-очистку в Data Node и AuthZ)
//	Публикует → bucket-deleted: при DeleteBucket (запускает async-очистку графа в AuthZ)
//	Потребляет ← object-stored: резервный путь для подтверждения версии объекта
type MetadataServiceServer interface {
	// CreateBucket регистрирует новый бакет в метаданных.
	// Ошибки: ALREADY_EXISTS (имя занято), INVALID_ARGUMENT (пустое имя).
	CreateBucket(context.Context, *CreateBucketRequest) (*CreateBucketResponse, error)
	// DeleteBucket удаляет метаданные бакета.
	// Ошибки: NOT_FOUND, FAILED_PRECONDITION (бакет не пуст).
	// После успешного удаления публикует событие bucket-deleted в Kafka.
	DeleteBucket(context.Context, *DeleteBucketRequest) (*DeleteBucketResponse, error)
	// GetBucket возвращает метаданные бакета по имени.
	// Ошибки: NOT_FOUND.
	GetBucket(context.Context, *GetBucketRequest) (*GetBucketResponse, error)
	// ListBuckets возвращает все бакеты, принадлежащие пользователю.
	ListBuckets(context.Context, *ListBucketsRequest) (*ListBucketsResponse, error)
	// HeadBucket проверяет, существует ли бакет (для S3 HEAD /{bucket}).
	HeadBucket(context.Context, *HeadBucketRequest) (*HeadBucketResponse, error)
	// CreateObjectVersion регистрирует новую версию объекта после того, как Data Node
	// подтвердил запись blob'а на диск. Вызывается Gateway сразу после StoreObject.
	// Ошибки: NOT_FOUND (бакет не существует), INVALID_ARGUMENT.
	CreateObjectVersion(context.Context, *CreateObjectVersionRequest) (*CreateObjectVersionResponse, error)
	// GetObjectMeta возвращает метаданные актуальной (или конкретной) версии объекта.
	// blob_id в ответе используется Gateway для вызова Data Node RetrieveObject.
	// Ошибки: NOT_FOUND (бакет или объект не существуют).
	GetObjectMeta(context.Context, *GetObjectMetaRequest) (*GetObjectMetaResponse, error)
	// DeleteObjectMeta помечает объект удалённым и публикует ObjectDeleted в Kafka.
	// Асинхронно запускает: удаление файла в Data Node + очистку графа в AuthZ.
	// Ошибки: NOT_FOUND.
	DeleteObjectMeta(context.Context, *DeleteObjectMetaRequest) (*DeleteObjectMetaResponse, error)
	// ListObjects возвращает постранично объекты бакета с опциональной фильтрацией по префиксу.
	// Аналог S3 ListObjectsV2. Только метаданные — Data Node не вызывается.
	// Ошибки: NOT_FOUND (бакет не существует).
	ListObjects(context.Context, *ListObjectsRequest) (*ListObjectsResponse, error)
	// HealthCheck — стандартный gRPC Health Checking Protocol.
	// Используется Kubernetes liveness/readiness probe и Gateway /ready.
	// NOT_SERVING возвращается если PostgreSQL или Kafka недоступны.
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedMetadataServiceServer()
}

// UnimplementedMetadataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetadataServiceServer struct{}

func (UnimplementedMetadataServiceServer) CreateBucket(context.Context, *CreateBucketRequest) (*CreateBucketResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBucket not implemented")
}
func (UnimplementedMetadataServiceServer) DeleteBucket(context.Context, *DeleteBucketRequest) (*DeleteBucketResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBucket not implemented")
}
func (UnimplementedMetadataServiceServer) GetBucket(context.Context, *GetBucketRequest) (*GetBucketResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBucket not implemented")
}
func (UnimplementedMetadataServiceServer) ListBuckets(context.Context, *ListBucketsRequest) (*ListBucketsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBuckets not implemented")
}
func (UnimplementedMetadataServiceServer) HeadBucket(context.Context, *HeadBucketRequest) (*HeadBucketResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HeadBucket not implemented")
}
func (UnimplementedMetadataServiceServer) CreateObjectVersion(context.Context, *CreateObjectVersionRequest) (*CreateObjectVersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateObjectVersion not implemented")
}
func (UnimplementedMetadataServiceServer) GetObjectMeta(context.Context, *GetObjectMetaRequest) (*GetObjectMetaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetObjectMeta not implemented")
}
func (UnimplementedMetadataServiceServer) DeleteObjectMeta(context.Context, *DeleteObjectMetaRequest) (*DeleteObjectMetaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteObjectMeta not implemented")
}
func (UnimplementedMetadataServiceServer) ListObjects(context.Context, *ListObjectsRequest) (*ListObjectsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListObjects not implemented")
}
func (UnimplementedMetadataServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedMetadataServiceServer) mustEmbedUnimplementedMetadataServiceServer() {}
func (UnimplementedMetadataServiceServer) testEmbeddedByValue()                         {}

// UnsafeMetadataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetadataServiceServer will
// result in compilation errors.
type UnsafeMetadataServiceServer interface {
	mustEmbedUnimplementedMetadataServiceServer()
}

func RegisterMetadataServiceServer(s grpc.ServiceRegistrar, srv MetadataServiceServer) {
	// If the following call panics, it indicates UnimplementedMetadataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MetadataService_ServiceDesc, srv)
}

func _MetadataService_CreateBucket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBucketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).CreateBucket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_CreateBucket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).CreateBucket(ctx, req.(*CreateBucketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_DeleteBucket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBucketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).DeleteBucket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_DeleteBucket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).DeleteBucket(ctx, req.(*DeleteBucketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_GetBucket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBucketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).GetBucket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_GetBucket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).GetBucket(ctx, req.(*GetBucketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_ListBuckets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBucketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).ListBuckets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_ListBuckets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).ListBuckets(ctx, req.(*ListBucketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_HeadBucket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeadBucketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).HeadBucket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_HeadBucket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).HeadBucket(ctx, req.(*HeadBucketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_CreateObjectVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateObjectVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).CreateObjectVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_CreateObjectVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).CreateObjectVersion(ctx, req.(*CreateObjectVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_GetObjectMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetObjectMetaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).GetObjectMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_GetObjectMeta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).GetObjectMeta(ctx, req.(*GetObjectMetaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_DeleteObjectMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteObjectMetaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).DeleteObjectMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_DeleteObjectMeta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).DeleteObjectMeta(ctx, req.(*DeleteObjectMetaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_ListObjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListObjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).ListObjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_ListObjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).ListObjects(ctx, req.(*ListObjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MetadataService_ServiceDesc is the grpc.ServiceDesc for MetadataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetadataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "opens3.metadata.v1.MetadataService",
	HandlerType: (*MetadataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBucket",
			Handler:    _MetadataService_CreateBucket_Handler,
		},
		{
			MethodName: "DeleteBucket",
			Handler:    _MetadataService_DeleteBucket_Handler,
		},
		{
			MethodName: "GetBucket",
			Handler:    _MetadataService_GetBucket_Handler,
		},
		{
			MethodName: "ListBuckets",
			Handler:    _MetadataService_ListBuckets_Handler,
		},
		{
			MethodName: "HeadBucket",
			Handler:    _MetadataService_HeadBucket_Handler,
		},
		{
			MethodName: "CreateObjectVersion",
			Handler:    _MetadataService_CreateObjectVersion_Handler,
		},
		{
			MethodName: "GetObjectMeta",
			Handler:    _MetadataService_GetObjectMeta_Handler,
		},
		{
			MethodName: "DeleteObjectMeta",
			Handler:    _MetadataService_DeleteObjectMeta_Handler,
		},
		{
			MethodName: "ListObjects",
			Handler:    _MetadataService_ListObjects_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _MetadataService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "metadata.proto",
}
