// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: storage.proto

package storagev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_UNKNOWN     HealthCheckResponse_ServingStatus = 0 // Статус неизвестен
	HealthCheckResponse_SERVING     HealthCheckResponse_ServingStatus = 1 // Сервис готов
	HealthCheckResponse_NOT_SERVING HealthCheckResponse_ServingStatus = 2 // DATA_DIR недоступна или заканчивается место
)

// Enum value maps for HealthCheckResponse_ServingStatus.
var (
	HealthCheckResponse_ServingStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
	}
	HealthCheckResponse_ServingStatus_value = map[string]int32{
		"UNKNOWN":     0,
		"SERVING":     1,
		"NOT_SERVING": 2,
	}
)

func (x HealthCheckResponse_ServingStatus) Enum() *HealthCheckResponse_ServingStatus {
	p := new(HealthCheckResponse_ServingStatus)
	*p = x
	return p
}

func (x HealthCheckResponse_ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_storage_proto_enumTypes[0].Descriptor()
}

func (HealthCheckResponse_ServingStatus) Type() protoreflect.EnumType {
	return &file_storage_proto_enumTypes[0]
}

func (x HealthCheckResponse_ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_ServingStatus.Descriptor instead.
func (HealthCheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{16, 0}
}

// StoreObjectRequest — один чанк стримингового запроса.
type StoreObjectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Чанк байт файла. Отправляется в нескольких сообщениях для больших файлов.
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// Ожидаемый итоговый размер файла в байтах.
	// Передаётся только в первом сообщении потока — используется для предварительного выделения.
	Size int64 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	// MIME тип (напр. "image/jpeg", "application/octet-stream").
	// Передаётся только в первом сообщении потока.
	ContentType   string `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreObjectRequest) Reset() {
	*x = StoreObjectRequest{}
	mi := &file_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreObjectRequest) ProtoMessage() {}

func (x *StoreObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreObjectRequest.ProtoReflect.Descriptor instead.
func (*StoreObjectRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{0}
}

func (x *StoreObjectRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *StoreObjectRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *StoreObjectRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type StoreObjectResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID нового blob'а. Gateway передаёт его в Metadata CreateObjectVersion.
	BlobId string `protobuf:"bytes,1,opt,name=blob_id,json=blobId,proto3" json:"blob_id,omitempty"`
	// Hex-encoded MD5 сохранённого контента. Gateway использует его как ETag.
	ChecksumMd5   string `protobuf:"bytes,2,opt,name=checksum_md5,json=checksumMd5,proto3" json:"checksum_md5,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreObjectResponse) Reset() {
	*x = StoreObjectResponse{}
	mi := &file_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreObjectResponse) ProtoMessage() {}

func (x *StoreObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreObjectResponse.ProtoReflect.Descriptor instead.
func (*StoreObjectResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{1}
}

func (x *StoreObjectResponse) GetBlobId() string {
	if x != nil {
		return x.BlobId
	}
	return ""
}

func (x *StoreObjectResponse) GetChecksumMd5() string {
	if x != nil {
		return x.ChecksumMd5
	}
	return ""
}

type RetrieveObjectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID blob'а, полученный из Metadata GetObjectMeta.
	BlobId string `protobuf:"bytes,1,opt,name=blob_id,json=blobId,proto3" json:"blob_id,omitempty"`
	// Начальный байт (включительно) для range-запроса. 0 = начало файла.
	RangeStart int64 `protobuf:"varint,2,opt,name=range_start,json=rangeStart,proto3" json:"range_start,omitempty"`
	// Конечный байт (не включается в ответ) для range-запроса. -1 = конец файла.
	RangeEnd      int64 `protobuf:"varint,3,opt,name=range_end,json=rangeEnd,proto3" json:"range_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveObjectRequest) Reset() {
	*x = RetrieveObjectRequest{}
	mi := &file_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveObjectRequest) ProtoMessage() {}

func (x *RetrieveObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveObjectRequest.ProtoReflect.Descriptor instead.
func (*RetrieveObjectRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{2}
}

func (x *RetrieveObjectRequest) GetBlobId() string {
	if x != nil {
		return x.BlobId
	}
	return ""
}

func (x *RetrieveObjectRequest) GetRangeStart() int64 {
	if x != nil {
		return x.RangeStart
	}
	return 0
}

func (x *RetrieveObjectRequest) GetRangeEnd() int64 {
	if x != nil {
		return x.RangeEnd
	}
	return 0
}

// RetrieveObjectResponse — один чанк стримингового ответа.
type RetrieveObjectResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Чанк байт файла.
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// Полный размер blob'а в байтах. Передаётся только в первом сообщении потока.
	TotalSize     int64 `protobuf:"varint,2,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveObjectResponse) Reset() {
	*x = RetrieveObjectResponse{}
	mi := &file_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveObjectResponse) ProtoMessage() {}

func (x *RetrieveObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveObjectResponse.ProtoReflect.Descriptor instead.
func (*RetrieveObjectResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{3}
}

func (x *RetrieveObjectResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RetrieveObjectResponse) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

type DeleteObjectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID blob'а для удаления.
	BlobId        string `protobuf:"bytes,1,opt,name=blob_id,json=blobId,proto3" json:"blob_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteObjectRequest) Reset() {
	*x = DeleteObjectRequest{}
	mi := &file_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteObjectRequest) ProtoMessage() {}

func (x *DeleteObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteObjectRequest.ProtoReflect.Descriptor instead.
func (*DeleteObjectRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteObjectRequest) GetBlobId() string {
	if x != nil {
		return x.BlobId
	}
	return ""
}

type DeleteObjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteObjectResponse) Reset() {
	*x = DeleteObjectResponse{}
	mi := &file_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteObjectResponse) ProtoMessage() {}

func (x *DeleteObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteObjectResponse.ProtoReflect.Descriptor instead.
func (*DeleteObjectResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteObjectResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type InitiateMultipartUploadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ожидаемое количество частей — подсказка для предварительного выделения (не обязательно).
	ExpectedParts int32 `protobuf:"varint,1,opt,name=expected_parts,json=expectedParts,proto3" json:"expected_parts,omitempty"`
	// MIME тип итогового объекта (напр. "video/mp4").
	ContentType   string `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateMultipartUploadRequest) Reset() {
	*x = InitiateMultipartUploadRequest{}
	mi := &file_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateMultipartUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateMultipartUploadRequest) ProtoMessage() {}

func (x *InitiateMultipartUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateMultipartUploadRequest.ProtoReflect.Descriptor instead.
func (*InitiateMultipartUploadRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{6}
}

func (x *InitiateMultipartUploadRequest) GetExpectedParts() int32 {
	if x != nil {
		return x.ExpectedParts
	}
	return 0
}

func (x *InitiateMultipartUploadRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type InitiateMultipartUploadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID сессии multipart-загрузки. Используется во всех последующих вызовах.
	UploadId      string `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateMultipartUploadResponse) Reset() {
	*x = InitiateMultipartUploadResponse{}
	mi := &file_storage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateMultipartUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateMultipartUploadResponse) ProtoMessage() {}

func (x *InitiateMultipartUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateMultipartUploadResponse.ProtoReflect.Descriptor instead.
func (*InitiateMultipartUploadResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{7}
}

func (x *InitiateMultipartUploadResponse) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

// UploadPartRequest — один чанк стримингового запроса части.
type UploadPartRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID сессии из InitiateMultipartUpload.
	UploadId string `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	// Порядковый номер части (начиная с 1). Определяет порядок склейки в CompleteMultipartUpload.
	PartNumber int32 `protobuf:"varint,2,opt,name=part_number,json=partNumber,proto3" json:"part_number,omitempty"`
	// Чанк байт данной части.
	Data          []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadPartRequest) Reset() {
	*x = UploadPartRequest{}
	mi := &file_storage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadPartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadPartRequest) ProtoMessage() {}

func (x *UploadPartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadPartRequest.ProtoReflect.Descriptor instead.
func (*UploadPartRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{8}
}

func (x *UploadPartRequest) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *UploadPartRequest) GetPartNumber() int32 {
	if x != nil {
		return x.PartNumber
	}
	return 0
}

func (x *UploadPartRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UploadPartResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MD5 данной части в hex. Передаётся в CompleteMultipartUpload для верификации целостности.
	PartChecksumMd5 string `protobuf:"bytes,1,opt,name=part_checksum_md5,json=partChecksumMd5,proto3" json:"part_checksum_md5,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UploadPartResponse) Reset() {
	*x = UploadPartResponse{}
	mi := &file_storage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadPartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadPartResponse) ProtoMessage() {}

func (x *UploadPartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadPartResponse.ProtoReflect.Descriptor instead.
func (*UploadPartResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{9}
}

func (x *UploadPartResponse) GetPartChecksumMd5() string {
	if x != nil {
		return x.PartChecksumMd5
	}
	return ""
}

// PartInfo описывает одну часть при CompleteMultipartUpload.
type PartInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Порядковый номер части (1-based), совпадает с part_number из UploadPart.
	PartNumber int32 `protobuf:"varint,1,opt,name=part_number,json=partNumber,proto3" json:"part_number,omitempty"`
	// MD5 части, полученный из UploadPartResponse. Используется для верификации.
	ChecksumMd5   string `protobuf:"bytes,2,opt,name=checksum_md5,json=checksumMd5,proto3" json:"checksum_md5,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartInfo) Reset() {
	*x = PartInfo{}
	mi := &file_storage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartInfo) ProtoMessage() {}

func (x *PartInfo) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartInfo.ProtoReflect.Descriptor instead.
func (*PartInfo) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{10}
}

func (x *PartInfo) GetPartNumber() int32 {
	if x != nil {
		return x.PartNumber
	}
	return 0
}

func (x *PartInfo) GetChecksumMd5() string {
	if x != nil {
		return x.ChecksumMd5
	}
	return ""
}

type CompleteMultipartUploadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID сессии из InitiateMultipartUpload.
	UploadId string `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	// Все части в правильном порядке (по part_number).
	Parts         []*PartInfo `protobuf:"bytes,2,rep,name=parts,proto3" json:"parts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteMultipartUploadRequest) Reset() {
	*x = CompleteMultipartUploadRequest{}
	mi := &file_storage_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteMultipartUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteMultipartUploadRequest) ProtoMessage() {}

func (x *CompleteMultipartUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteMultipartUploadRequest.ProtoReflect.Descriptor instead.
func (*CompleteMultipartUploadRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{11}
}

func (x *CompleteMultipartUploadRequest) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *CompleteMultipartUploadRequest) GetParts() []*PartInfo {
	if x != nil {
		return x.Parts
	}
	return nil
}

type CompleteMultipartUploadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID итогового собранного blob'а. Gateway передаёт его в Metadata CreateObjectVersion.
	BlobId string `protobuf:"bytes,1,opt,name=blob_id,json=blobId,proto3" json:"blob_id,omitempty"`
	// MD5 итогового собранного файла в hex. Gateway использует как ETag.
	ChecksumMd5   string `protobuf:"bytes,2,opt,name=checksum_md5,json=checksumMd5,proto3" json:"checksum_md5,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteMultipartUploadResponse) Reset() {
	*x = CompleteMultipartUploadResponse{}
	mi := &file_storage_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteMultipartUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteMultipartUploadResponse) ProtoMessage() {}

func (x *CompleteMultipartUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteMultipartUploadResponse.ProtoReflect.Descriptor instead.
func (*CompleteMultipartUploadResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{12}
}

func (x *CompleteMultipartUploadResponse) GetBlobId() string {
	if x != nil {
		return x.BlobId
	}
	return ""
}

func (x *CompleteMultipartUploadResponse) GetChecksumMd5() string {
	if x != nil {
		return x.ChecksumMd5
	}
	return ""
}

type AbortMultipartUploadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID сессии для отмены.
	UploadId      string `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortMultipartUploadRequest) Reset() {
	*x = AbortMultipartUploadRequest{}
	mi := &file_storage_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortMultipartUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortMultipartUploadRequest) ProtoMessage() {}

func (x *AbortMultipartUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortMultipartUploadRequest.ProtoReflect.Descriptor instead.
func (*AbortMultipartUploadRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{13}
}

func (x *AbortMultipartUploadRequest) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

type AbortMultipartUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortMultipartUploadResponse) Reset() {
	*x = AbortMultipartUploadResponse{}
	mi := &file_storage_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortMultipartUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortMultipartUploadResponse) ProtoMessage() {}

func (x *AbortMultipartUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortMultipartUploadResponse.ProtoReflect.Descriptor instead.
func (*AbortMultipartUploadResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{14}
}

func (x *AbortMultipartUploadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type HealthCheckRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Имя сервиса. Пустая строка — проверить весь процесс.
	Service       string `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_storage_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{15}
}

func (x *HealthCheckRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Status        HealthCheckResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=opens3.storage.v1.HealthCheckResponse_ServingStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_storage_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{16}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_ServingStatus {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_UNKNOWN
}

var File_storage_proto protoreflect.FileDescriptor

const file_storage_proto_rawDesc = "" +
	"\n" +
	"\rstorage.proto\x12\x11opens3.storage.v1\"_\n" +
	"\x12StoreObjectRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\"Q\n" +
	"\x13StoreObjectResponse\x12\x17\n" +
	"\ablob_id\x18\x01 \x01(\tR\x06blobId\x12!\n" +
	"\fchecksum_md5\x18\x02 \x01(\tR\vchecksumMd5\"n\n" +
	"\x15RetrieveObjectRequest\x12\x17\n" +
	"\ablob_id\x18\x01 \x01(\tR\x06blobId\x12\x1f\n" +
	"\vrange_start\x18\x02 \x01(\x03R\n" +
	"rangeStart\x12\x1b\n" +
	"\trange_end\x18\x03 \x01(\x03R\brangeEnd\"K\n" +
	"\x16RetrieveObjectResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1d\n" +
	"\n" +
	"total_size\x18\x02 \x01(\x03R\ttotalSize\".\n" +
	"\x13DeleteObjectRequest\x12\x17\n" +
	"\ablob_id\x18\x01 \x01(\tR\x06blobId\"0\n" +
	"\x14DeleteObjectResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"j\n" +
	"\x1eInitiateMultipartUploadRequest\x12%\n" +
	"\x0eexpected_parts\x18\x01 \x01(\x05R\rexpectedParts\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\">\n" +
	"\x1fInitiateMultipartUploadResponse\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\"e\n" +
	"\x11UploadPartRequest\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\x12\x1f\n" +
	"\vpart_number\x18\x02 \x01(\x05R\n" +
	"partNumber\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"@\n" +
	"\x12UploadPartResponse\x12*\n" +
	"\x11part_checksum_md5\x18\x01 \x01(\tR\x0fpartChecksumMd5\"N\n" +
	"\bPartInfo\x12\x1f\n" +
	"\vpart_number\x18\x01 \x01(\x05R\n" +
	"partNumber\x12!\n" +
	"\fchecksum_md5\x18\x02 \x01(\tR\vchecksumMd5\"p\n" +
	"\x1eCompleteMultipartUploadRequest\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\x121\n" +
	"\x05parts\x18\x02 \x03(\v2\x1b.opens3.storage.v1.PartInfoR\x05parts\"]\n" +
	"\x1fCompleteMultipartUploadResponse\x12\x17\n" +
	"\ablob_id\x18\x01 \x01(\tR\x06blobId\x12!\n" +
	"\fchecksum_md5\x18\x02 \x01(\tR\vchecksumMd5\":\n" +
	"\x1bAbortMultipartUploadRequest\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\"8\n" +
	"\x1cAbortMultipartUploadResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\".\n" +
	"\x12HealthCheckRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\"\x9f\x01\n" +
	"\x13HealthCheckResponse\x12L\n" +
	"\x06status\x18\x01 \x01(\x0e24.opens3.storage.v1.HealthCheckResponse.ServingStatusR\x06status\":\n" +
	"\rServingStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x022\xf8\x06\n" +
	"\x12DataStorageService\x12^\n" +
	"\vStoreObject\x12%.opens3.storage.v1.StoreObjectRequest\x1a&.opens3.storage.v1.StoreObjectResponse(\x01\x12g\n" +
	"\x0eRetrieveObject\x12(.opens3.storage.v1.RetrieveObjectRequest\x1a).opens3.storage.v1.RetrieveObjectResponse0\x01\x12_\n" +
	"\fDeleteObject\x12&.opens3.storage.v1.DeleteObjectRequest\x1a'.opens3.storage.v1.DeleteObjectResponse\x12\x80\x01\n" +
	"\x17InitiateMultipartUpload\x121.opens3.storage.v1.InitiateMultipartUploadRequest\x1a2.opens3.storage.v1.InitiateMultipartUploadResponse\x12[\n" +
	"\n" +
	"UploadPart\x12$.opens3.storage.v1.UploadPartRequest\x1a%.opens3.storage.v1.UploadPartResponse(\x01\x12\x80\x01\n" +
	"\x17CompleteMultipartUpload\x121.opens3.storage.v1.CompleteMultipartUploadRequest\x1a2.opens3.storage.v1.CompleteMultipartUploadResponse\x12w\n" +
	"\x14AbortMultipartUpload\x12..opens3.storage.v1.AbortMultipartUploadRequest\x1a/.opens3.storage.v1.AbortMultipartUploadResponse\x12\\\n" +
	"\vHealthCheck\x12%.opens3.storage.v1.HealthCheckRequest\x1a&.opens3.storage.v1.HealthCheckResponseBEZCgithub.com/alesplll/opens3-rebac/shared/pkg/go/storage/v1;storagev1b\x06proto3"

var (
	file_storage_proto_rawDescOnce sync.Once
	file_storage_proto_rawDescData []byte
)

func file_storage_proto_rawDescGZIP() []byte {
	file_storage_proto_rawDescOnce.Do(func() {
		file_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storage_proto_rawDesc), len(file_storage_proto_rawDesc)))
	})
	return file_storage_proto_rawDescData
}

var file_storage_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_storage_proto_goTypes = []any{
	(HealthCheckResponse_ServingStatus)(0),  // 0: opens3.storage.v1.HealthCheckResponse.ServingStatus
	(*StoreObjectRequest)(nil),              // 1: opens3.storage.v1.StoreObjectRequest
	(*StoreObjectResponse)(nil),             // 2: opens3.storage.v1.StoreObjectResponse
	(*RetrieveObjectRequest)(nil),           // 3: opens3.storage.v1.RetrieveObjectRequest
	(*RetrieveObjectResponse)(nil),          // 4: opens3.storage.v1.RetrieveObjectResponse
	(*DeleteObjectRequest)(nil),             // 5: opens3.storage.v1.DeleteObjectRequest
	(*DeleteObjectResponse)(nil),            // 6: opens3.storage.v1.DeleteObjectResponse
	(*InitiateMultipartUploadRequest)(nil),  // 7: opens3.storage.v1.InitiateMultipartUploadRequest
	(*InitiateMultipartUploadResponse)(nil), // 8: opens3.storage.v1.InitiateMultipartUploadResponse
	(*UploadPartRequest)(nil),               // 9: opens3.storage.v1.UploadPartRequest
	(*UploadPartResponse)(nil),              // 10: opens3.storage.v1.UploadPartResponse
	(*PartInfo)(nil),                        // 11: opens3.storage.v1.PartInfo
	(*CompleteMultipartUploadRequest)(nil),  // 12: opens3.storage.v1.CompleteMultipartUploadRequest
	(*CompleteMultipartUploadResponse)(nil), // 13: opens3.storage.v1.CompleteMultipartUploadResponse
	(*AbortMultipartUploadRequest)(nil),     // 14: opens3.storage.v1.AbortMultipartUploadRequest
	(*AbortMultipartUploadResponse)(nil),    // 15: opens3.storage.v1.AbortMultipartUploadResponse
	(*HealthCheckRequest)(nil),              // 16: opens3.storage.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),             // 17: opens3.storage.v1.HealthCheckResponse
}
var file_storage_proto_depIdxs = []int32{
	11, // 0: opens3.storage.v1.CompleteMultipartUploadRequest.parts:type_name -> opens3.storage.v1.PartInfo
	0,  // 1: opens3.storage.v1.HealthCheckResponse.status:type_name -> opens3.storage.v1.HealthCheckResponse.ServingStatus
	1,  // 2: opens3.storage.v1.DataStorageService.StoreObject:input_type -> opens3.storage.v1.StoreObjectRequest
	3,  // 3: opens3.storage.v1.DataStorageService.RetrieveObject:input_type -> opens3.storage.v1.RetrieveObjectRequest
	5,  // 4: opens3.storage.v1.DataStorageService.DeleteObject:input_type -> opens3.storage.v1.DeleteObjectRequest
	7,  // 5: opens3.storage.v1.DataStorageService.InitiateMultipartUpload:input_type -> opens3.storage.v1.InitiateMultipartUploadRequest
	9,  // 6: opens3.storage.v1.DataStorageService.UploadPart:input_type -> opens3.storage.v1.UploadPartRequest
	12, // 7: opens3.storage.v1.DataStorageService.CompleteMultipartUpload:input_type -> opens3.storage.v1.CompleteMultipartUploadRequest
	14, // 8: opens3.storage.v1.DataStorageService.AbortMultipartUpload:input_type -> opens3.storage.v1.AbortMultipartUploadRequest
	16, // 9: opens3.storage.v1.DataStorageService.HealthCheck:input_type -> opens3.storage.v1.HealthCheckRequest
	2,  // 10: opens3.storage.v1.DataStorageService.StoreObject:output_type -> opens3.storage.v1.StoreObjectResponse
	4,  // 11: opens3.storage.v1.DataStorageService.RetrieveObject:output_type -> opens3.storage.v1.RetrieveObjectResponse
	6,  // 12: opens3.storage.v1.DataStorageService.DeleteObject:output_type -> opens3.storage.v1.DeleteObjectResponse
	8,  // 13: opens3.storage.v1.DataStorageService.InitiateMultipartUpload:output_type -> opens3.storage.v1.InitiateMultipartUploadResponse
	10, // 14: opens3.storage.v1.DataStorageService.UploadPart:output_type -> opens3.storage.v1.UploadPartResponse
	13, // 15: opens3.storage.v1.DataStorageService.CompleteMultipartUpload:output_type -> opens3.storage.v1.CompleteMultipartUploadResponse
	15, // 16: opens3.storage.v1.DataStorageService.AbortMultipartUpload:output_type -> opens3.storage.v1.AbortMultipartUploadResponse
	17, // 17: opens3.storage.v1.DataStorageService.HealthCheck:output_type -> opens3.storage.v1.HealthCheckResponse
	10, // [10:18] is the sub-list for method output_type
	2,  // [2:10] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_storage_proto_init() }
func file_storage_proto_init() {
	if File_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storage_proto_rawDesc), len(file_storage_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_storage_proto_goTypes,
		DependencyIndexes: file_storage_proto_depIdxs,
		EnumInfos:         file_storage_proto_enumTypes,
		MessageInfos:      file_storage_proto_msgTypes,
	}.Build()
	File_storage_proto = out.File
	file_storage_proto_goTypes = nil
	file_storage_proto_depIdxs = nil
}
