"""Metrics config protocol — mirrors go-kit metric.MetricsConfig interface."""
from typing import Protocol


class MetricsConfig(Protocol):
    def service_name(self) -> str: ...
    def service_version(self) -> str: ...
    def otlp_endpoint(self) -> str:
        """host:port of the OTLP collector gRPC endpoint."""
        ...
    def service_environment(self) -> str: ...
    def push_interval_seconds(self) -> float:
        """How often to push metrics to the collector (default 60s)."""
        ...
