package mocks

// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

//go:generate minimock -i github.com/alesplll/opens3-rebac/services/auth/internal/repository.AuthRepository -o auth_repository_minimock.go -n AuthRepositoryMock

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// AuthRepositoryMock implements repository.AuthRepository
type AuthRepositoryMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcGetLoginAttempts          func(ctx context.Context, email string) (i1 int8, err error)
	inspectFuncGetLoginAttempts   func(ctx context.Context, email string)
	afterGetLoginAttemptsCounter  uint64
	beforeGetLoginAttemptsCounter uint64
	GetLoginAttemptsMock          mAuthRepositoryMockGetLoginAttempts

	funcIncrementLoginAttempts          func(ctx context.Context, email string) (i1 int8, err error)
	inspectFuncIncrementLoginAttempts   func(ctx context.Context, email string)
	afterIncrementLoginAttemptsCounter  uint64
	beforeIncrementLoginAttemptsCounter uint64
	IncrementLoginAttemptsMock          mAuthRepositoryMockIncrementLoginAttempts

	funcResetLoginAttempts          func(ctx context.Context, email string) (err error)
	inspectFuncResetLoginAttempts   func(ctx context.Context, email string)
	afterResetLoginAttemptsCounter  uint64
	beforeResetLoginAttemptsCounter uint64
	ResetLoginAttemptsMock          mAuthRepositoryMockResetLoginAttempts
}

// NewAuthRepositoryMock returns a mock for repository.AuthRepository
func NewAuthRepositoryMock(t minimock.Tester) *AuthRepositoryMock {
	m := &AuthRepositoryMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.GetLoginAttemptsMock = mAuthRepositoryMockGetLoginAttempts{mock: m}
	m.GetLoginAttemptsMock.callArgs = []*AuthRepositoryMockGetLoginAttemptsParams{}

	m.IncrementLoginAttemptsMock = mAuthRepositoryMockIncrementLoginAttempts{mock: m}
	m.IncrementLoginAttemptsMock.callArgs = []*AuthRepositoryMockIncrementLoginAttemptsParams{}

	m.ResetLoginAttemptsMock = mAuthRepositoryMockResetLoginAttempts{mock: m}
	m.ResetLoginAttemptsMock.callArgs = []*AuthRepositoryMockResetLoginAttemptsParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mAuthRepositoryMockGetLoginAttempts struct {
	mock               *AuthRepositoryMock
	defaultExpectation *AuthRepositoryMockGetLoginAttemptsExpectation
	expectations       []*AuthRepositoryMockGetLoginAttemptsExpectation

	callArgs []*AuthRepositoryMockGetLoginAttemptsParams
	mutex    sync.RWMutex
}

// AuthRepositoryMockGetLoginAttemptsExpectation specifies expectation struct of the AuthRepository.GetLoginAttempts
type AuthRepositoryMockGetLoginAttemptsExpectation struct {
	mock    *AuthRepositoryMock
	params  *AuthRepositoryMockGetLoginAttemptsParams
	results *AuthRepositoryMockGetLoginAttemptsResults
	Counter uint64
}

// AuthRepositoryMockGetLoginAttemptsParams contains parameters of the AuthRepository.GetLoginAttempts
type AuthRepositoryMockGetLoginAttemptsParams struct {
	ctx   context.Context
	email string
}

// AuthRepositoryMockGetLoginAttemptsResults contains results of the AuthRepository.GetLoginAttempts
type AuthRepositoryMockGetLoginAttemptsResults struct {
	i1  int8
	err error
}

// Expect sets up expected params for AuthRepository.GetLoginAttempts
func (mmGetLoginAttempts *mAuthRepositoryMockGetLoginAttempts) Expect(ctx context.Context, email string) *mAuthRepositoryMockGetLoginAttempts {
	if mmGetLoginAttempts.mock.funcGetLoginAttempts != nil {
		mmGetLoginAttempts.mock.t.Fatalf("AuthRepositoryMock.GetLoginAttempts mock is already set by Set")
	}

	if mmGetLoginAttempts.defaultExpectation == nil {
		mmGetLoginAttempts.defaultExpectation = &AuthRepositoryMockGetLoginAttemptsExpectation{}
	}

	mmGetLoginAttempts.defaultExpectation.params = &AuthRepositoryMockGetLoginAttemptsParams{ctx, email}
	for _, e := range mmGetLoginAttempts.expectations {
		if minimock.Equal(e.params, mmGetLoginAttempts.defaultExpectation.params) {
			mmGetLoginAttempts.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetLoginAttempts.defaultExpectation.params)
		}
	}

	return mmGetLoginAttempts
}

// Inspect accepts an inspector function that has same arguments as the AuthRepository.GetLoginAttempts
func (mmGetLoginAttempts *mAuthRepositoryMockGetLoginAttempts) Inspect(f func(ctx context.Context, email string)) *mAuthRepositoryMockGetLoginAttempts {
	if mmGetLoginAttempts.mock.inspectFuncGetLoginAttempts != nil {
		mmGetLoginAttempts.mock.t.Fatalf("Inspect function is already set for AuthRepositoryMock.GetLoginAttempts")
	}

	mmGetLoginAttempts.mock.inspectFuncGetLoginAttempts = f

	return mmGetLoginAttempts
}

// Return sets up results that will be returned by AuthRepository.GetLoginAttempts
func (mmGetLoginAttempts *mAuthRepositoryMockGetLoginAttempts) Return(i1 int8, err error) *AuthRepositoryMock {
	if mmGetLoginAttempts.mock.funcGetLoginAttempts != nil {
		mmGetLoginAttempts.mock.t.Fatalf("AuthRepositoryMock.GetLoginAttempts mock is already set by Set")
	}

	if mmGetLoginAttempts.defaultExpectation == nil {
		mmGetLoginAttempts.defaultExpectation = &AuthRepositoryMockGetLoginAttemptsExpectation{mock: mmGetLoginAttempts.mock}
	}
	mmGetLoginAttempts.defaultExpectation.results = &AuthRepositoryMockGetLoginAttemptsResults{i1, err}
	return mmGetLoginAttempts.mock
}

// Set uses given function f to mock the AuthRepository.GetLoginAttempts method
func (mmGetLoginAttempts *mAuthRepositoryMockGetLoginAttempts) Set(f func(ctx context.Context, email string) (i1 int8, err error)) *AuthRepositoryMock {
	if mmGetLoginAttempts.defaultExpectation != nil {
		mmGetLoginAttempts.mock.t.Fatalf("Default expectation is already set for the AuthRepository.GetLoginAttempts method")
	}

	if len(mmGetLoginAttempts.expectations) > 0 {
		mmGetLoginAttempts.mock.t.Fatalf("Some expectations are already set for the AuthRepository.GetLoginAttempts method")
	}

	mmGetLoginAttempts.mock.funcGetLoginAttempts = f
	return mmGetLoginAttempts.mock
}

// When sets expectation for the AuthRepository.GetLoginAttempts which will trigger the result defined by the following
// Then helper
func (mmGetLoginAttempts *mAuthRepositoryMockGetLoginAttempts) When(ctx context.Context, email string) *AuthRepositoryMockGetLoginAttemptsExpectation {
	if mmGetLoginAttempts.mock.funcGetLoginAttempts != nil {
		mmGetLoginAttempts.mock.t.Fatalf("AuthRepositoryMock.GetLoginAttempts mock is already set by Set")
	}

	expectation := &AuthRepositoryMockGetLoginAttemptsExpectation{
		mock:   mmGetLoginAttempts.mock,
		params: &AuthRepositoryMockGetLoginAttemptsParams{ctx, email},
	}
	mmGetLoginAttempts.expectations = append(mmGetLoginAttempts.expectations, expectation)
	return expectation
}

// Then sets up AuthRepository.GetLoginAttempts return parameters for the expectation previously defined by the When method
func (e *AuthRepositoryMockGetLoginAttemptsExpectation) Then(i1 int8, err error) *AuthRepositoryMock {
	e.results = &AuthRepositoryMockGetLoginAttemptsResults{i1, err}
	return e.mock
}

// GetLoginAttempts implements repository.AuthRepository
func (mmGetLoginAttempts *AuthRepositoryMock) GetLoginAttempts(ctx context.Context, email string) (i1 int8, err error) {
	mm_atomic.AddUint64(&mmGetLoginAttempts.beforeGetLoginAttemptsCounter, 1)
	defer mm_atomic.AddUint64(&mmGetLoginAttempts.afterGetLoginAttemptsCounter, 1)

	if mmGetLoginAttempts.inspectFuncGetLoginAttempts != nil {
		mmGetLoginAttempts.inspectFuncGetLoginAttempts(ctx, email)
	}

	mm_params := AuthRepositoryMockGetLoginAttemptsParams{ctx, email}

	// Record call args
	mmGetLoginAttempts.GetLoginAttemptsMock.mutex.Lock()
	mmGetLoginAttempts.GetLoginAttemptsMock.callArgs = append(mmGetLoginAttempts.GetLoginAttemptsMock.callArgs, &mm_params)
	mmGetLoginAttempts.GetLoginAttemptsMock.mutex.Unlock()

	for _, e := range mmGetLoginAttempts.GetLoginAttemptsMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.i1, e.results.err
		}
	}

	if mmGetLoginAttempts.GetLoginAttemptsMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetLoginAttempts.GetLoginAttemptsMock.defaultExpectation.Counter, 1)
		mm_want := mmGetLoginAttempts.GetLoginAttemptsMock.defaultExpectation.params
		mm_got := AuthRepositoryMockGetLoginAttemptsParams{ctx, email}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetLoginAttempts.t.Errorf("AuthRepositoryMock.GetLoginAttempts got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetLoginAttempts.GetLoginAttemptsMock.defaultExpectation.results
		if mm_results == nil {
			mmGetLoginAttempts.t.Fatal("No results are set for the AuthRepositoryMock.GetLoginAttempts")
		}
		return (*mm_results).i1, (*mm_results).err
	}
	if mmGetLoginAttempts.funcGetLoginAttempts != nil {
		return mmGetLoginAttempts.funcGetLoginAttempts(ctx, email)
	}
	mmGetLoginAttempts.t.Fatalf("Unexpected call to AuthRepositoryMock.GetLoginAttempts. %v %v", ctx, email)
	return
}

// GetLoginAttemptsAfterCounter returns a count of finished AuthRepositoryMock.GetLoginAttempts invocations
func (mmGetLoginAttempts *AuthRepositoryMock) GetLoginAttemptsAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetLoginAttempts.afterGetLoginAttemptsCounter)
}

// GetLoginAttemptsBeforeCounter returns a count of AuthRepositoryMock.GetLoginAttempts invocations
func (mmGetLoginAttempts *AuthRepositoryMock) GetLoginAttemptsBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetLoginAttempts.beforeGetLoginAttemptsCounter)
}

// Calls returns a list of arguments used in each call to AuthRepositoryMock.GetLoginAttempts.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetLoginAttempts *mAuthRepositoryMockGetLoginAttempts) Calls() []*AuthRepositoryMockGetLoginAttemptsParams {
	mmGetLoginAttempts.mutex.RLock()

	argCopy := make([]*AuthRepositoryMockGetLoginAttemptsParams, len(mmGetLoginAttempts.callArgs))
	copy(argCopy, mmGetLoginAttempts.callArgs)

	mmGetLoginAttempts.mutex.RUnlock()

	return argCopy
}

// MinimockGetLoginAttemptsDone returns true if the count of the GetLoginAttempts invocations corresponds
// the number of defined expectations
func (m *AuthRepositoryMock) MinimockGetLoginAttemptsDone() bool {
	for _, e := range m.GetLoginAttemptsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.GetLoginAttemptsMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterGetLoginAttemptsCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetLoginAttempts != nil && mm_atomic.LoadUint64(&m.afterGetLoginAttemptsCounter) < 1 {
		return false
	}
	return true
}

// MinimockGetLoginAttemptsInspect logs each unmet expectation
func (m *AuthRepositoryMock) MinimockGetLoginAttemptsInspect() {
	for _, e := range m.GetLoginAttemptsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to AuthRepositoryMock.GetLoginAttempts with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.GetLoginAttemptsMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterGetLoginAttemptsCounter) < 1 {
		if m.GetLoginAttemptsMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to AuthRepositoryMock.GetLoginAttempts")
		} else {
			m.t.Errorf("Expected call to AuthRepositoryMock.GetLoginAttempts with params: %#v", *m.GetLoginAttemptsMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetLoginAttempts != nil && mm_atomic.LoadUint64(&m.afterGetLoginAttemptsCounter) < 1 {
		m.t.Error("Expected call to AuthRepositoryMock.GetLoginAttempts")
	}
}

type mAuthRepositoryMockIncrementLoginAttempts struct {
	mock               *AuthRepositoryMock
	defaultExpectation *AuthRepositoryMockIncrementLoginAttemptsExpectation
	expectations       []*AuthRepositoryMockIncrementLoginAttemptsExpectation

	callArgs []*AuthRepositoryMockIncrementLoginAttemptsParams
	mutex    sync.RWMutex
}

// AuthRepositoryMockIncrementLoginAttemptsExpectation specifies expectation struct of the AuthRepository.IncrementLoginAttempts
type AuthRepositoryMockIncrementLoginAttemptsExpectation struct {
	mock    *AuthRepositoryMock
	params  *AuthRepositoryMockIncrementLoginAttemptsParams
	results *AuthRepositoryMockIncrementLoginAttemptsResults
	Counter uint64
}

// AuthRepositoryMockIncrementLoginAttemptsParams contains parameters of the AuthRepository.IncrementLoginAttempts
type AuthRepositoryMockIncrementLoginAttemptsParams struct {
	ctx   context.Context
	email string
}

// AuthRepositoryMockIncrementLoginAttemptsResults contains results of the AuthRepository.IncrementLoginAttempts
type AuthRepositoryMockIncrementLoginAttemptsResults struct {
	i1  int8
	err error
}

// Expect sets up expected params for AuthRepository.IncrementLoginAttempts
func (mmIncrementLoginAttempts *mAuthRepositoryMockIncrementLoginAttempts) Expect(ctx context.Context, email string) *mAuthRepositoryMockIncrementLoginAttempts {
	if mmIncrementLoginAttempts.mock.funcIncrementLoginAttempts != nil {
		mmIncrementLoginAttempts.mock.t.Fatalf("AuthRepositoryMock.IncrementLoginAttempts mock is already set by Set")
	}

	if mmIncrementLoginAttempts.defaultExpectation == nil {
		mmIncrementLoginAttempts.defaultExpectation = &AuthRepositoryMockIncrementLoginAttemptsExpectation{}
	}

	mmIncrementLoginAttempts.defaultExpectation.params = &AuthRepositoryMockIncrementLoginAttemptsParams{ctx, email}
	for _, e := range mmIncrementLoginAttempts.expectations {
		if minimock.Equal(e.params, mmIncrementLoginAttempts.defaultExpectation.params) {
			mmIncrementLoginAttempts.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmIncrementLoginAttempts.defaultExpectation.params)
		}
	}

	return mmIncrementLoginAttempts
}

// Inspect accepts an inspector function that has same arguments as the AuthRepository.IncrementLoginAttempts
func (mmIncrementLoginAttempts *mAuthRepositoryMockIncrementLoginAttempts) Inspect(f func(ctx context.Context, email string)) *mAuthRepositoryMockIncrementLoginAttempts {
	if mmIncrementLoginAttempts.mock.inspectFuncIncrementLoginAttempts != nil {
		mmIncrementLoginAttempts.mock.t.Fatalf("Inspect function is already set for AuthRepositoryMock.IncrementLoginAttempts")
	}

	mmIncrementLoginAttempts.mock.inspectFuncIncrementLoginAttempts = f

	return mmIncrementLoginAttempts
}

// Return sets up results that will be returned by AuthRepository.IncrementLoginAttempts
func (mmIncrementLoginAttempts *mAuthRepositoryMockIncrementLoginAttempts) Return(i1 int8, err error) *AuthRepositoryMock {
	if mmIncrementLoginAttempts.mock.funcIncrementLoginAttempts != nil {
		mmIncrementLoginAttempts.mock.t.Fatalf("AuthRepositoryMock.IncrementLoginAttempts mock is already set by Set")
	}

	if mmIncrementLoginAttempts.defaultExpectation == nil {
		mmIncrementLoginAttempts.defaultExpectation = &AuthRepositoryMockIncrementLoginAttemptsExpectation{mock: mmIncrementLoginAttempts.mock}
	}
	mmIncrementLoginAttempts.defaultExpectation.results = &AuthRepositoryMockIncrementLoginAttemptsResults{i1, err}
	return mmIncrementLoginAttempts.mock
}

// Set uses given function f to mock the AuthRepository.IncrementLoginAttempts method
func (mmIncrementLoginAttempts *mAuthRepositoryMockIncrementLoginAttempts) Set(f func(ctx context.Context, email string) (i1 int8, err error)) *AuthRepositoryMock {
	if mmIncrementLoginAttempts.defaultExpectation != nil {
		mmIncrementLoginAttempts.mock.t.Fatalf("Default expectation is already set for the AuthRepository.IncrementLoginAttempts method")
	}

	if len(mmIncrementLoginAttempts.expectations) > 0 {
		mmIncrementLoginAttempts.mock.t.Fatalf("Some expectations are already set for the AuthRepository.IncrementLoginAttempts method")
	}

	mmIncrementLoginAttempts.mock.funcIncrementLoginAttempts = f
	return mmIncrementLoginAttempts.mock
}

// When sets expectation for the AuthRepository.IncrementLoginAttempts which will trigger the result defined by the following
// Then helper
func (mmIncrementLoginAttempts *mAuthRepositoryMockIncrementLoginAttempts) When(ctx context.Context, email string) *AuthRepositoryMockIncrementLoginAttemptsExpectation {
	if mmIncrementLoginAttempts.mock.funcIncrementLoginAttempts != nil {
		mmIncrementLoginAttempts.mock.t.Fatalf("AuthRepositoryMock.IncrementLoginAttempts mock is already set by Set")
	}

	expectation := &AuthRepositoryMockIncrementLoginAttemptsExpectation{
		mock:   mmIncrementLoginAttempts.mock,
		params: &AuthRepositoryMockIncrementLoginAttemptsParams{ctx, email},
	}
	mmIncrementLoginAttempts.expectations = append(mmIncrementLoginAttempts.expectations, expectation)
	return expectation
}

// Then sets up AuthRepository.IncrementLoginAttempts return parameters for the expectation previously defined by the When method
func (e *AuthRepositoryMockIncrementLoginAttemptsExpectation) Then(i1 int8, err error) *AuthRepositoryMock {
	e.results = &AuthRepositoryMockIncrementLoginAttemptsResults{i1, err}
	return e.mock
}

// IncrementLoginAttempts implements repository.AuthRepository
func (mmIncrementLoginAttempts *AuthRepositoryMock) IncrementLoginAttempts(ctx context.Context, email string) (i1 int8, err error) {
	mm_atomic.AddUint64(&mmIncrementLoginAttempts.beforeIncrementLoginAttemptsCounter, 1)
	defer mm_atomic.AddUint64(&mmIncrementLoginAttempts.afterIncrementLoginAttemptsCounter, 1)

	if mmIncrementLoginAttempts.inspectFuncIncrementLoginAttempts != nil {
		mmIncrementLoginAttempts.inspectFuncIncrementLoginAttempts(ctx, email)
	}

	mm_params := AuthRepositoryMockIncrementLoginAttemptsParams{ctx, email}

	// Record call args
	mmIncrementLoginAttempts.IncrementLoginAttemptsMock.mutex.Lock()
	mmIncrementLoginAttempts.IncrementLoginAttemptsMock.callArgs = append(mmIncrementLoginAttempts.IncrementLoginAttemptsMock.callArgs, &mm_params)
	mmIncrementLoginAttempts.IncrementLoginAttemptsMock.mutex.Unlock()

	for _, e := range mmIncrementLoginAttempts.IncrementLoginAttemptsMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.i1, e.results.err
		}
	}

	if mmIncrementLoginAttempts.IncrementLoginAttemptsMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmIncrementLoginAttempts.IncrementLoginAttemptsMock.defaultExpectation.Counter, 1)
		mm_want := mmIncrementLoginAttempts.IncrementLoginAttemptsMock.defaultExpectation.params
		mm_got := AuthRepositoryMockIncrementLoginAttemptsParams{ctx, email}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmIncrementLoginAttempts.t.Errorf("AuthRepositoryMock.IncrementLoginAttempts got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmIncrementLoginAttempts.IncrementLoginAttemptsMock.defaultExpectation.results
		if mm_results == nil {
			mmIncrementLoginAttempts.t.Fatal("No results are set for the AuthRepositoryMock.IncrementLoginAttempts")
		}
		return (*mm_results).i1, (*mm_results).err
	}
	if mmIncrementLoginAttempts.funcIncrementLoginAttempts != nil {
		return mmIncrementLoginAttempts.funcIncrementLoginAttempts(ctx, email)
	}
	mmIncrementLoginAttempts.t.Fatalf("Unexpected call to AuthRepositoryMock.IncrementLoginAttempts. %v %v", ctx, email)
	return
}

// IncrementLoginAttemptsAfterCounter returns a count of finished AuthRepositoryMock.IncrementLoginAttempts invocations
func (mmIncrementLoginAttempts *AuthRepositoryMock) IncrementLoginAttemptsAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmIncrementLoginAttempts.afterIncrementLoginAttemptsCounter)
}

// IncrementLoginAttemptsBeforeCounter returns a count of AuthRepositoryMock.IncrementLoginAttempts invocations
func (mmIncrementLoginAttempts *AuthRepositoryMock) IncrementLoginAttemptsBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmIncrementLoginAttempts.beforeIncrementLoginAttemptsCounter)
}

// Calls returns a list of arguments used in each call to AuthRepositoryMock.IncrementLoginAttempts.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmIncrementLoginAttempts *mAuthRepositoryMockIncrementLoginAttempts) Calls() []*AuthRepositoryMockIncrementLoginAttemptsParams {
	mmIncrementLoginAttempts.mutex.RLock()

	argCopy := make([]*AuthRepositoryMockIncrementLoginAttemptsParams, len(mmIncrementLoginAttempts.callArgs))
	copy(argCopy, mmIncrementLoginAttempts.callArgs)

	mmIncrementLoginAttempts.mutex.RUnlock()

	return argCopy
}

// MinimockIncrementLoginAttemptsDone returns true if the count of the IncrementLoginAttempts invocations corresponds
// the number of defined expectations
func (m *AuthRepositoryMock) MinimockIncrementLoginAttemptsDone() bool {
	for _, e := range m.IncrementLoginAttemptsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.IncrementLoginAttemptsMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterIncrementLoginAttemptsCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcIncrementLoginAttempts != nil && mm_atomic.LoadUint64(&m.afterIncrementLoginAttemptsCounter) < 1 {
		return false
	}
	return true
}

// MinimockIncrementLoginAttemptsInspect logs each unmet expectation
func (m *AuthRepositoryMock) MinimockIncrementLoginAttemptsInspect() {
	for _, e := range m.IncrementLoginAttemptsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to AuthRepositoryMock.IncrementLoginAttempts with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.IncrementLoginAttemptsMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterIncrementLoginAttemptsCounter) < 1 {
		if m.IncrementLoginAttemptsMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to AuthRepositoryMock.IncrementLoginAttempts")
		} else {
			m.t.Errorf("Expected call to AuthRepositoryMock.IncrementLoginAttempts with params: %#v", *m.IncrementLoginAttemptsMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcIncrementLoginAttempts != nil && mm_atomic.LoadUint64(&m.afterIncrementLoginAttemptsCounter) < 1 {
		m.t.Error("Expected call to AuthRepositoryMock.IncrementLoginAttempts")
	}
}

type mAuthRepositoryMockResetLoginAttempts struct {
	mock               *AuthRepositoryMock
	defaultExpectation *AuthRepositoryMockResetLoginAttemptsExpectation
	expectations       []*AuthRepositoryMockResetLoginAttemptsExpectation

	callArgs []*AuthRepositoryMockResetLoginAttemptsParams
	mutex    sync.RWMutex
}

// AuthRepositoryMockResetLoginAttemptsExpectation specifies expectation struct of the AuthRepository.ResetLoginAttempts
type AuthRepositoryMockResetLoginAttemptsExpectation struct {
	mock    *AuthRepositoryMock
	params  *AuthRepositoryMockResetLoginAttemptsParams
	results *AuthRepositoryMockResetLoginAttemptsResults
	Counter uint64
}

// AuthRepositoryMockResetLoginAttemptsParams contains parameters of the AuthRepository.ResetLoginAttempts
type AuthRepositoryMockResetLoginAttemptsParams struct {
	ctx   context.Context
	email string
}

// AuthRepositoryMockResetLoginAttemptsResults contains results of the AuthRepository.ResetLoginAttempts
type AuthRepositoryMockResetLoginAttemptsResults struct {
	err error
}

// Expect sets up expected params for AuthRepository.ResetLoginAttempts
func (mmResetLoginAttempts *mAuthRepositoryMockResetLoginAttempts) Expect(ctx context.Context, email string) *mAuthRepositoryMockResetLoginAttempts {
	if mmResetLoginAttempts.mock.funcResetLoginAttempts != nil {
		mmResetLoginAttempts.mock.t.Fatalf("AuthRepositoryMock.ResetLoginAttempts mock is already set by Set")
	}

	if mmResetLoginAttempts.defaultExpectation == nil {
		mmResetLoginAttempts.defaultExpectation = &AuthRepositoryMockResetLoginAttemptsExpectation{}
	}

	mmResetLoginAttempts.defaultExpectation.params = &AuthRepositoryMockResetLoginAttemptsParams{ctx, email}
	for _, e := range mmResetLoginAttempts.expectations {
		if minimock.Equal(e.params, mmResetLoginAttempts.defaultExpectation.params) {
			mmResetLoginAttempts.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmResetLoginAttempts.defaultExpectation.params)
		}
	}

	return mmResetLoginAttempts
}

// Inspect accepts an inspector function that has same arguments as the AuthRepository.ResetLoginAttempts
func (mmResetLoginAttempts *mAuthRepositoryMockResetLoginAttempts) Inspect(f func(ctx context.Context, email string)) *mAuthRepositoryMockResetLoginAttempts {
	if mmResetLoginAttempts.mock.inspectFuncResetLoginAttempts != nil {
		mmResetLoginAttempts.mock.t.Fatalf("Inspect function is already set for AuthRepositoryMock.ResetLoginAttempts")
	}

	mmResetLoginAttempts.mock.inspectFuncResetLoginAttempts = f

	return mmResetLoginAttempts
}

// Return sets up results that will be returned by AuthRepository.ResetLoginAttempts
func (mmResetLoginAttempts *mAuthRepositoryMockResetLoginAttempts) Return(err error) *AuthRepositoryMock {
	if mmResetLoginAttempts.mock.funcResetLoginAttempts != nil {
		mmResetLoginAttempts.mock.t.Fatalf("AuthRepositoryMock.ResetLoginAttempts mock is already set by Set")
	}

	if mmResetLoginAttempts.defaultExpectation == nil {
		mmResetLoginAttempts.defaultExpectation = &AuthRepositoryMockResetLoginAttemptsExpectation{mock: mmResetLoginAttempts.mock}
	}
	mmResetLoginAttempts.defaultExpectation.results = &AuthRepositoryMockResetLoginAttemptsResults{err}
	return mmResetLoginAttempts.mock
}

// Set uses given function f to mock the AuthRepository.ResetLoginAttempts method
func (mmResetLoginAttempts *mAuthRepositoryMockResetLoginAttempts) Set(f func(ctx context.Context, email string) (err error)) *AuthRepositoryMock {
	if mmResetLoginAttempts.defaultExpectation != nil {
		mmResetLoginAttempts.mock.t.Fatalf("Default expectation is already set for the AuthRepository.ResetLoginAttempts method")
	}

	if len(mmResetLoginAttempts.expectations) > 0 {
		mmResetLoginAttempts.mock.t.Fatalf("Some expectations are already set for the AuthRepository.ResetLoginAttempts method")
	}

	mmResetLoginAttempts.mock.funcResetLoginAttempts = f
	return mmResetLoginAttempts.mock
}

// When sets expectation for the AuthRepository.ResetLoginAttempts which will trigger the result defined by the following
// Then helper
func (mmResetLoginAttempts *mAuthRepositoryMockResetLoginAttempts) When(ctx context.Context, email string) *AuthRepositoryMockResetLoginAttemptsExpectation {
	if mmResetLoginAttempts.mock.funcResetLoginAttempts != nil {
		mmResetLoginAttempts.mock.t.Fatalf("AuthRepositoryMock.ResetLoginAttempts mock is already set by Set")
	}

	expectation := &AuthRepositoryMockResetLoginAttemptsExpectation{
		mock:   mmResetLoginAttempts.mock,
		params: &AuthRepositoryMockResetLoginAttemptsParams{ctx, email},
	}
	mmResetLoginAttempts.expectations = append(mmResetLoginAttempts.expectations, expectation)
	return expectation
}

// Then sets up AuthRepository.ResetLoginAttempts return parameters for the expectation previously defined by the When method
func (e *AuthRepositoryMockResetLoginAttemptsExpectation) Then(err error) *AuthRepositoryMock {
	e.results = &AuthRepositoryMockResetLoginAttemptsResults{err}
	return e.mock
}

// ResetLoginAttempts implements repository.AuthRepository
func (mmResetLoginAttempts *AuthRepositoryMock) ResetLoginAttempts(ctx context.Context, email string) (err error) {
	mm_atomic.AddUint64(&mmResetLoginAttempts.beforeResetLoginAttemptsCounter, 1)
	defer mm_atomic.AddUint64(&mmResetLoginAttempts.afterResetLoginAttemptsCounter, 1)

	if mmResetLoginAttempts.inspectFuncResetLoginAttempts != nil {
		mmResetLoginAttempts.inspectFuncResetLoginAttempts(ctx, email)
	}

	mm_params := AuthRepositoryMockResetLoginAttemptsParams{ctx, email}

	// Record call args
	mmResetLoginAttempts.ResetLoginAttemptsMock.mutex.Lock()
	mmResetLoginAttempts.ResetLoginAttemptsMock.callArgs = append(mmResetLoginAttempts.ResetLoginAttemptsMock.callArgs, &mm_params)
	mmResetLoginAttempts.ResetLoginAttemptsMock.mutex.Unlock()

	for _, e := range mmResetLoginAttempts.ResetLoginAttemptsMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmResetLoginAttempts.ResetLoginAttemptsMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmResetLoginAttempts.ResetLoginAttemptsMock.defaultExpectation.Counter, 1)
		mm_want := mmResetLoginAttempts.ResetLoginAttemptsMock.defaultExpectation.params
		mm_got := AuthRepositoryMockResetLoginAttemptsParams{ctx, email}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmResetLoginAttempts.t.Errorf("AuthRepositoryMock.ResetLoginAttempts got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmResetLoginAttempts.ResetLoginAttemptsMock.defaultExpectation.results
		if mm_results == nil {
			mmResetLoginAttempts.t.Fatal("No results are set for the AuthRepositoryMock.ResetLoginAttempts")
		}
		return (*mm_results).err
	}
	if mmResetLoginAttempts.funcResetLoginAttempts != nil {
		return mmResetLoginAttempts.funcResetLoginAttempts(ctx, email)
	}
	mmResetLoginAttempts.t.Fatalf("Unexpected call to AuthRepositoryMock.ResetLoginAttempts. %v %v", ctx, email)
	return
}

// ResetLoginAttemptsAfterCounter returns a count of finished AuthRepositoryMock.ResetLoginAttempts invocations
func (mmResetLoginAttempts *AuthRepositoryMock) ResetLoginAttemptsAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmResetLoginAttempts.afterResetLoginAttemptsCounter)
}

// ResetLoginAttemptsBeforeCounter returns a count of AuthRepositoryMock.ResetLoginAttempts invocations
func (mmResetLoginAttempts *AuthRepositoryMock) ResetLoginAttemptsBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmResetLoginAttempts.beforeResetLoginAttemptsCounter)
}

// Calls returns a list of arguments used in each call to AuthRepositoryMock.ResetLoginAttempts.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmResetLoginAttempts *mAuthRepositoryMockResetLoginAttempts) Calls() []*AuthRepositoryMockResetLoginAttemptsParams {
	mmResetLoginAttempts.mutex.RLock()

	argCopy := make([]*AuthRepositoryMockResetLoginAttemptsParams, len(mmResetLoginAttempts.callArgs))
	copy(argCopy, mmResetLoginAttempts.callArgs)

	mmResetLoginAttempts.mutex.RUnlock()

	return argCopy
}

// MinimockResetLoginAttemptsDone returns true if the count of the ResetLoginAttempts invocations corresponds
// the number of defined expectations
func (m *AuthRepositoryMock) MinimockResetLoginAttemptsDone() bool {
	for _, e := range m.ResetLoginAttemptsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.ResetLoginAttemptsMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterResetLoginAttemptsCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcResetLoginAttempts != nil && mm_atomic.LoadUint64(&m.afterResetLoginAttemptsCounter) < 1 {
		return false
	}
	return true
}

// MinimockResetLoginAttemptsInspect logs each unmet expectation
func (m *AuthRepositoryMock) MinimockResetLoginAttemptsInspect() {
	for _, e := range m.ResetLoginAttemptsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to AuthRepositoryMock.ResetLoginAttempts with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.ResetLoginAttemptsMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterResetLoginAttemptsCounter) < 1 {
		if m.ResetLoginAttemptsMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to AuthRepositoryMock.ResetLoginAttempts")
		} else {
			m.t.Errorf("Expected call to AuthRepositoryMock.ResetLoginAttempts with params: %#v", *m.ResetLoginAttemptsMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcResetLoginAttempts != nil && mm_atomic.LoadUint64(&m.afterResetLoginAttemptsCounter) < 1 {
		m.t.Error("Expected call to AuthRepositoryMock.ResetLoginAttempts")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *AuthRepositoryMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockGetLoginAttemptsInspect()

			m.MinimockIncrementLoginAttemptsInspect()

			m.MinimockResetLoginAttemptsInspect()
			m.t.FailNow()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *AuthRepositoryMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *AuthRepositoryMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockGetLoginAttemptsDone() &&
		m.MinimockIncrementLoginAttemptsDone() &&
		m.MinimockResetLoginAttemptsDone()
}
