package mocks

// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

//go:generate minimock -i github.com/alesplll/opens3-rebac/shared/pkg/go-kit/tokens.TokenService -o token_service_minimock.go -n TokenServiceMock

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	mm_tokens "github.com/alesplll/opens3-rebac/shared/pkg/go-kit/tokens"
	"github.com/gojuno/minimock/v3"
)

// TokenServiceMock implements tokens.TokenService
type TokenServiceMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcGenerateAccessToken          func(ctx context.Context, u1 mm_tokens.UserInfo) (s1 string, err error)
	inspectFuncGenerateAccessToken   func(ctx context.Context, u1 mm_tokens.UserInfo)
	afterGenerateAccessTokenCounter  uint64
	beforeGenerateAccessTokenCounter uint64
	GenerateAccessTokenMock          mTokenServiceMockGenerateAccessToken

	funcGenerateRefreshToken          func(ctx context.Context, u1 mm_tokens.UserInfo) (s1 string, err error)
	inspectFuncGenerateRefreshToken   func(ctx context.Context, u1 mm_tokens.UserInfo)
	afterGenerateRefreshTokenCounter  uint64
	beforeGenerateRefreshTokenCounter uint64
	GenerateRefreshTokenMock          mTokenServiceMockGenerateRefreshToken

	funcVerifyAccessToken          func(ctx context.Context, s1 string) (up1 *mm_tokens.UserClaims, err error)
	inspectFuncVerifyAccessToken   func(ctx context.Context, s1 string)
	afterVerifyAccessTokenCounter  uint64
	beforeVerifyAccessTokenCounter uint64
	VerifyAccessTokenMock          mTokenServiceMockVerifyAccessToken

	funcVerifyRefreshToken          func(ctx context.Context, s1 string) (up1 *mm_tokens.UserClaims, err error)
	inspectFuncVerifyRefreshToken   func(ctx context.Context, s1 string)
	afterVerifyRefreshTokenCounter  uint64
	beforeVerifyRefreshTokenCounter uint64
	VerifyRefreshTokenMock          mTokenServiceMockVerifyRefreshToken
}

// NewTokenServiceMock returns a mock for tokens.TokenService
func NewTokenServiceMock(t minimock.Tester) *TokenServiceMock {
	m := &TokenServiceMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.GenerateAccessTokenMock = mTokenServiceMockGenerateAccessToken{mock: m}
	m.GenerateAccessTokenMock.callArgs = []*TokenServiceMockGenerateAccessTokenParams{}

	m.GenerateRefreshTokenMock = mTokenServiceMockGenerateRefreshToken{mock: m}
	m.GenerateRefreshTokenMock.callArgs = []*TokenServiceMockGenerateRefreshTokenParams{}

	m.VerifyAccessTokenMock = mTokenServiceMockVerifyAccessToken{mock: m}
	m.VerifyAccessTokenMock.callArgs = []*TokenServiceMockVerifyAccessTokenParams{}

	m.VerifyRefreshTokenMock = mTokenServiceMockVerifyRefreshToken{mock: m}
	m.VerifyRefreshTokenMock.callArgs = []*TokenServiceMockVerifyRefreshTokenParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mTokenServiceMockGenerateAccessToken struct {
	mock               *TokenServiceMock
	defaultExpectation *TokenServiceMockGenerateAccessTokenExpectation
	expectations       []*TokenServiceMockGenerateAccessTokenExpectation

	callArgs []*TokenServiceMockGenerateAccessTokenParams
	mutex    sync.RWMutex
}

// TokenServiceMockGenerateAccessTokenExpectation specifies expectation struct of the TokenService.GenerateAccessToken
type TokenServiceMockGenerateAccessTokenExpectation struct {
	mock    *TokenServiceMock
	params  *TokenServiceMockGenerateAccessTokenParams
	results *TokenServiceMockGenerateAccessTokenResults
	Counter uint64
}

// TokenServiceMockGenerateAccessTokenParams contains parameters of the TokenService.GenerateAccessToken
type TokenServiceMockGenerateAccessTokenParams struct {
	ctx context.Context
	u1  mm_tokens.UserInfo
}

// TokenServiceMockGenerateAccessTokenResults contains results of the TokenService.GenerateAccessToken
type TokenServiceMockGenerateAccessTokenResults struct {
	s1  string
	err error
}

// Expect sets up expected params for TokenService.GenerateAccessToken
func (mmGenerateAccessToken *mTokenServiceMockGenerateAccessToken) Expect(ctx context.Context, u1 mm_tokens.UserInfo) *mTokenServiceMockGenerateAccessToken {
	if mmGenerateAccessToken.mock.funcGenerateAccessToken != nil {
		mmGenerateAccessToken.mock.t.Fatalf("TokenServiceMock.GenerateAccessToken mock is already set by Set")
	}

	if mmGenerateAccessToken.defaultExpectation == nil {
		mmGenerateAccessToken.defaultExpectation = &TokenServiceMockGenerateAccessTokenExpectation{}
	}

	mmGenerateAccessToken.defaultExpectation.params = &TokenServiceMockGenerateAccessTokenParams{ctx, u1}
	for _, e := range mmGenerateAccessToken.expectations {
		if minimock.Equal(e.params, mmGenerateAccessToken.defaultExpectation.params) {
			mmGenerateAccessToken.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGenerateAccessToken.defaultExpectation.params)
		}
	}

	return mmGenerateAccessToken
}

// Inspect accepts an inspector function that has same arguments as the TokenService.GenerateAccessToken
func (mmGenerateAccessToken *mTokenServiceMockGenerateAccessToken) Inspect(f func(ctx context.Context, u1 mm_tokens.UserInfo)) *mTokenServiceMockGenerateAccessToken {
	if mmGenerateAccessToken.mock.inspectFuncGenerateAccessToken != nil {
		mmGenerateAccessToken.mock.t.Fatalf("Inspect function is already set for TokenServiceMock.GenerateAccessToken")
	}

	mmGenerateAccessToken.mock.inspectFuncGenerateAccessToken = f

	return mmGenerateAccessToken
}

// Return sets up results that will be returned by TokenService.GenerateAccessToken
func (mmGenerateAccessToken *mTokenServiceMockGenerateAccessToken) Return(s1 string, err error) *TokenServiceMock {
	if mmGenerateAccessToken.mock.funcGenerateAccessToken != nil {
		mmGenerateAccessToken.mock.t.Fatalf("TokenServiceMock.GenerateAccessToken mock is already set by Set")
	}

	if mmGenerateAccessToken.defaultExpectation == nil {
		mmGenerateAccessToken.defaultExpectation = &TokenServiceMockGenerateAccessTokenExpectation{mock: mmGenerateAccessToken.mock}
	}
	mmGenerateAccessToken.defaultExpectation.results = &TokenServiceMockGenerateAccessTokenResults{s1, err}
	return mmGenerateAccessToken.mock
}

// Set uses given function f to mock the TokenService.GenerateAccessToken method
func (mmGenerateAccessToken *mTokenServiceMockGenerateAccessToken) Set(f func(ctx context.Context, u1 mm_tokens.UserInfo) (s1 string, err error)) *TokenServiceMock {
	if mmGenerateAccessToken.defaultExpectation != nil {
		mmGenerateAccessToken.mock.t.Fatalf("Default expectation is already set for the TokenService.GenerateAccessToken method")
	}

	if len(mmGenerateAccessToken.expectations) > 0 {
		mmGenerateAccessToken.mock.t.Fatalf("Some expectations are already set for the TokenService.GenerateAccessToken method")
	}

	mmGenerateAccessToken.mock.funcGenerateAccessToken = f
	return mmGenerateAccessToken.mock
}

// When sets expectation for the TokenService.GenerateAccessToken which will trigger the result defined by the following
// Then helper
func (mmGenerateAccessToken *mTokenServiceMockGenerateAccessToken) When(ctx context.Context, u1 mm_tokens.UserInfo) *TokenServiceMockGenerateAccessTokenExpectation {
	if mmGenerateAccessToken.mock.funcGenerateAccessToken != nil {
		mmGenerateAccessToken.mock.t.Fatalf("TokenServiceMock.GenerateAccessToken mock is already set by Set")
	}

	expectation := &TokenServiceMockGenerateAccessTokenExpectation{
		mock:   mmGenerateAccessToken.mock,
		params: &TokenServiceMockGenerateAccessTokenParams{ctx, u1},
	}
	mmGenerateAccessToken.expectations = append(mmGenerateAccessToken.expectations, expectation)
	return expectation
}

// Then sets up TokenService.GenerateAccessToken return parameters for the expectation previously defined by the When method
func (e *TokenServiceMockGenerateAccessTokenExpectation) Then(s1 string, err error) *TokenServiceMock {
	e.results = &TokenServiceMockGenerateAccessTokenResults{s1, err}
	return e.mock
}

// GenerateAccessToken implements tokens.TokenService
func (mmGenerateAccessToken *TokenServiceMock) GenerateAccessToken(ctx context.Context, u1 mm_tokens.UserInfo) (s1 string, err error) {
	mm_atomic.AddUint64(&mmGenerateAccessToken.beforeGenerateAccessTokenCounter, 1)
	defer mm_atomic.AddUint64(&mmGenerateAccessToken.afterGenerateAccessTokenCounter, 1)

	if mmGenerateAccessToken.inspectFuncGenerateAccessToken != nil {
		mmGenerateAccessToken.inspectFuncGenerateAccessToken(ctx, u1)
	}

	mm_params := TokenServiceMockGenerateAccessTokenParams{ctx, u1}

	// Record call args
	mmGenerateAccessToken.GenerateAccessTokenMock.mutex.Lock()
	mmGenerateAccessToken.GenerateAccessTokenMock.callArgs = append(mmGenerateAccessToken.GenerateAccessTokenMock.callArgs, &mm_params)
	mmGenerateAccessToken.GenerateAccessTokenMock.mutex.Unlock()

	for _, e := range mmGenerateAccessToken.GenerateAccessTokenMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.s1, e.results.err
		}
	}

	if mmGenerateAccessToken.GenerateAccessTokenMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGenerateAccessToken.GenerateAccessTokenMock.defaultExpectation.Counter, 1)
		mm_want := mmGenerateAccessToken.GenerateAccessTokenMock.defaultExpectation.params
		mm_got := TokenServiceMockGenerateAccessTokenParams{ctx, u1}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGenerateAccessToken.t.Errorf("TokenServiceMock.GenerateAccessToken got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGenerateAccessToken.GenerateAccessTokenMock.defaultExpectation.results
		if mm_results == nil {
			mmGenerateAccessToken.t.Fatal("No results are set for the TokenServiceMock.GenerateAccessToken")
		}
		return (*mm_results).s1, (*mm_results).err
	}
	if mmGenerateAccessToken.funcGenerateAccessToken != nil {
		return mmGenerateAccessToken.funcGenerateAccessToken(ctx, u1)
	}
	mmGenerateAccessToken.t.Fatalf("Unexpected call to TokenServiceMock.GenerateAccessToken. %v %v", ctx, u1)
	return
}

// GenerateAccessTokenAfterCounter returns a count of finished TokenServiceMock.GenerateAccessToken invocations
func (mmGenerateAccessToken *TokenServiceMock) GenerateAccessTokenAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGenerateAccessToken.afterGenerateAccessTokenCounter)
}

// GenerateAccessTokenBeforeCounter returns a count of TokenServiceMock.GenerateAccessToken invocations
func (mmGenerateAccessToken *TokenServiceMock) GenerateAccessTokenBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGenerateAccessToken.beforeGenerateAccessTokenCounter)
}

// Calls returns a list of arguments used in each call to TokenServiceMock.GenerateAccessToken.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGenerateAccessToken *mTokenServiceMockGenerateAccessToken) Calls() []*TokenServiceMockGenerateAccessTokenParams {
	mmGenerateAccessToken.mutex.RLock()

	argCopy := make([]*TokenServiceMockGenerateAccessTokenParams, len(mmGenerateAccessToken.callArgs))
	copy(argCopy, mmGenerateAccessToken.callArgs)

	mmGenerateAccessToken.mutex.RUnlock()

	return argCopy
}

// MinimockGenerateAccessTokenDone returns true if the count of the GenerateAccessToken invocations corresponds
// the number of defined expectations
func (m *TokenServiceMock) MinimockGenerateAccessTokenDone() bool {
	for _, e := range m.GenerateAccessTokenMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.GenerateAccessTokenMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterGenerateAccessTokenCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGenerateAccessToken != nil && mm_atomic.LoadUint64(&m.afterGenerateAccessTokenCounter) < 1 {
		return false
	}
	return true
}

// MinimockGenerateAccessTokenInspect logs each unmet expectation
func (m *TokenServiceMock) MinimockGenerateAccessTokenInspect() {
	for _, e := range m.GenerateAccessTokenMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to TokenServiceMock.GenerateAccessToken with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.GenerateAccessTokenMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterGenerateAccessTokenCounter) < 1 {
		if m.GenerateAccessTokenMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to TokenServiceMock.GenerateAccessToken")
		} else {
			m.t.Errorf("Expected call to TokenServiceMock.GenerateAccessToken with params: %#v", *m.GenerateAccessTokenMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGenerateAccessToken != nil && mm_atomic.LoadUint64(&m.afterGenerateAccessTokenCounter) < 1 {
		m.t.Error("Expected call to TokenServiceMock.GenerateAccessToken")
	}
}

type mTokenServiceMockGenerateRefreshToken struct {
	mock               *TokenServiceMock
	defaultExpectation *TokenServiceMockGenerateRefreshTokenExpectation
	expectations       []*TokenServiceMockGenerateRefreshTokenExpectation

	callArgs []*TokenServiceMockGenerateRefreshTokenParams
	mutex    sync.RWMutex
}

// TokenServiceMockGenerateRefreshTokenExpectation specifies expectation struct of the TokenService.GenerateRefreshToken
type TokenServiceMockGenerateRefreshTokenExpectation struct {
	mock    *TokenServiceMock
	params  *TokenServiceMockGenerateRefreshTokenParams
	results *TokenServiceMockGenerateRefreshTokenResults
	Counter uint64
}

// TokenServiceMockGenerateRefreshTokenParams contains parameters of the TokenService.GenerateRefreshToken
type TokenServiceMockGenerateRefreshTokenParams struct {
	ctx context.Context
	u1  mm_tokens.UserInfo
}

// TokenServiceMockGenerateRefreshTokenResults contains results of the TokenService.GenerateRefreshToken
type TokenServiceMockGenerateRefreshTokenResults struct {
	s1  string
	err error
}

// Expect sets up expected params for TokenService.GenerateRefreshToken
func (mmGenerateRefreshToken *mTokenServiceMockGenerateRefreshToken) Expect(ctx context.Context, u1 mm_tokens.UserInfo) *mTokenServiceMockGenerateRefreshToken {
	if mmGenerateRefreshToken.mock.funcGenerateRefreshToken != nil {
		mmGenerateRefreshToken.mock.t.Fatalf("TokenServiceMock.GenerateRefreshToken mock is already set by Set")
	}

	if mmGenerateRefreshToken.defaultExpectation == nil {
		mmGenerateRefreshToken.defaultExpectation = &TokenServiceMockGenerateRefreshTokenExpectation{}
	}

	mmGenerateRefreshToken.defaultExpectation.params = &TokenServiceMockGenerateRefreshTokenParams{ctx, u1}
	for _, e := range mmGenerateRefreshToken.expectations {
		if minimock.Equal(e.params, mmGenerateRefreshToken.defaultExpectation.params) {
			mmGenerateRefreshToken.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGenerateRefreshToken.defaultExpectation.params)
		}
	}

	return mmGenerateRefreshToken
}

// Inspect accepts an inspector function that has same arguments as the TokenService.GenerateRefreshToken
func (mmGenerateRefreshToken *mTokenServiceMockGenerateRefreshToken) Inspect(f func(ctx context.Context, u1 mm_tokens.UserInfo)) *mTokenServiceMockGenerateRefreshToken {
	if mmGenerateRefreshToken.mock.inspectFuncGenerateRefreshToken != nil {
		mmGenerateRefreshToken.mock.t.Fatalf("Inspect function is already set for TokenServiceMock.GenerateRefreshToken")
	}

	mmGenerateRefreshToken.mock.inspectFuncGenerateRefreshToken = f

	return mmGenerateRefreshToken
}

// Return sets up results that will be returned by TokenService.GenerateRefreshToken
func (mmGenerateRefreshToken *mTokenServiceMockGenerateRefreshToken) Return(s1 string, err error) *TokenServiceMock {
	if mmGenerateRefreshToken.mock.funcGenerateRefreshToken != nil {
		mmGenerateRefreshToken.mock.t.Fatalf("TokenServiceMock.GenerateRefreshToken mock is already set by Set")
	}

	if mmGenerateRefreshToken.defaultExpectation == nil {
		mmGenerateRefreshToken.defaultExpectation = &TokenServiceMockGenerateRefreshTokenExpectation{mock: mmGenerateRefreshToken.mock}
	}
	mmGenerateRefreshToken.defaultExpectation.results = &TokenServiceMockGenerateRefreshTokenResults{s1, err}
	return mmGenerateRefreshToken.mock
}

// Set uses given function f to mock the TokenService.GenerateRefreshToken method
func (mmGenerateRefreshToken *mTokenServiceMockGenerateRefreshToken) Set(f func(ctx context.Context, u1 mm_tokens.UserInfo) (s1 string, err error)) *TokenServiceMock {
	if mmGenerateRefreshToken.defaultExpectation != nil {
		mmGenerateRefreshToken.mock.t.Fatalf("Default expectation is already set for the TokenService.GenerateRefreshToken method")
	}

	if len(mmGenerateRefreshToken.expectations) > 0 {
		mmGenerateRefreshToken.mock.t.Fatalf("Some expectations are already set for the TokenService.GenerateRefreshToken method")
	}

	mmGenerateRefreshToken.mock.funcGenerateRefreshToken = f
	return mmGenerateRefreshToken.mock
}

// When sets expectation for the TokenService.GenerateRefreshToken which will trigger the result defined by the following
// Then helper
func (mmGenerateRefreshToken *mTokenServiceMockGenerateRefreshToken) When(ctx context.Context, u1 mm_tokens.UserInfo) *TokenServiceMockGenerateRefreshTokenExpectation {
	if mmGenerateRefreshToken.mock.funcGenerateRefreshToken != nil {
		mmGenerateRefreshToken.mock.t.Fatalf("TokenServiceMock.GenerateRefreshToken mock is already set by Set")
	}

	expectation := &TokenServiceMockGenerateRefreshTokenExpectation{
		mock:   mmGenerateRefreshToken.mock,
		params: &TokenServiceMockGenerateRefreshTokenParams{ctx, u1},
	}
	mmGenerateRefreshToken.expectations = append(mmGenerateRefreshToken.expectations, expectation)
	return expectation
}

// Then sets up TokenService.GenerateRefreshToken return parameters for the expectation previously defined by the When method
func (e *TokenServiceMockGenerateRefreshTokenExpectation) Then(s1 string, err error) *TokenServiceMock {
	e.results = &TokenServiceMockGenerateRefreshTokenResults{s1, err}
	return e.mock
}

// GenerateRefreshToken implements tokens.TokenService
func (mmGenerateRefreshToken *TokenServiceMock) GenerateRefreshToken(ctx context.Context, u1 mm_tokens.UserInfo) (s1 string, err error) {
	mm_atomic.AddUint64(&mmGenerateRefreshToken.beforeGenerateRefreshTokenCounter, 1)
	defer mm_atomic.AddUint64(&mmGenerateRefreshToken.afterGenerateRefreshTokenCounter, 1)

	if mmGenerateRefreshToken.inspectFuncGenerateRefreshToken != nil {
		mmGenerateRefreshToken.inspectFuncGenerateRefreshToken(ctx, u1)
	}

	mm_params := TokenServiceMockGenerateRefreshTokenParams{ctx, u1}

	// Record call args
	mmGenerateRefreshToken.GenerateRefreshTokenMock.mutex.Lock()
	mmGenerateRefreshToken.GenerateRefreshTokenMock.callArgs = append(mmGenerateRefreshToken.GenerateRefreshTokenMock.callArgs, &mm_params)
	mmGenerateRefreshToken.GenerateRefreshTokenMock.mutex.Unlock()

	for _, e := range mmGenerateRefreshToken.GenerateRefreshTokenMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.s1, e.results.err
		}
	}

	if mmGenerateRefreshToken.GenerateRefreshTokenMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGenerateRefreshToken.GenerateRefreshTokenMock.defaultExpectation.Counter, 1)
		mm_want := mmGenerateRefreshToken.GenerateRefreshTokenMock.defaultExpectation.params
		mm_got := TokenServiceMockGenerateRefreshTokenParams{ctx, u1}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGenerateRefreshToken.t.Errorf("TokenServiceMock.GenerateRefreshToken got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGenerateRefreshToken.GenerateRefreshTokenMock.defaultExpectation.results
		if mm_results == nil {
			mmGenerateRefreshToken.t.Fatal("No results are set for the TokenServiceMock.GenerateRefreshToken")
		}
		return (*mm_results).s1, (*mm_results).err
	}
	if mmGenerateRefreshToken.funcGenerateRefreshToken != nil {
		return mmGenerateRefreshToken.funcGenerateRefreshToken(ctx, u1)
	}
	mmGenerateRefreshToken.t.Fatalf("Unexpected call to TokenServiceMock.GenerateRefreshToken. %v %v", ctx, u1)
	return
}

// GenerateRefreshTokenAfterCounter returns a count of finished TokenServiceMock.GenerateRefreshToken invocations
func (mmGenerateRefreshToken *TokenServiceMock) GenerateRefreshTokenAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGenerateRefreshToken.afterGenerateRefreshTokenCounter)
}

// GenerateRefreshTokenBeforeCounter returns a count of TokenServiceMock.GenerateRefreshToken invocations
func (mmGenerateRefreshToken *TokenServiceMock) GenerateRefreshTokenBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGenerateRefreshToken.beforeGenerateRefreshTokenCounter)
}

// Calls returns a list of arguments used in each call to TokenServiceMock.GenerateRefreshToken.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGenerateRefreshToken *mTokenServiceMockGenerateRefreshToken) Calls() []*TokenServiceMockGenerateRefreshTokenParams {
	mmGenerateRefreshToken.mutex.RLock()

	argCopy := make([]*TokenServiceMockGenerateRefreshTokenParams, len(mmGenerateRefreshToken.callArgs))
	copy(argCopy, mmGenerateRefreshToken.callArgs)

	mmGenerateRefreshToken.mutex.RUnlock()

	return argCopy
}

// MinimockGenerateRefreshTokenDone returns true if the count of the GenerateRefreshToken invocations corresponds
// the number of defined expectations
func (m *TokenServiceMock) MinimockGenerateRefreshTokenDone() bool {
	for _, e := range m.GenerateRefreshTokenMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.GenerateRefreshTokenMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterGenerateRefreshTokenCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGenerateRefreshToken != nil && mm_atomic.LoadUint64(&m.afterGenerateRefreshTokenCounter) < 1 {
		return false
	}
	return true
}

// MinimockGenerateRefreshTokenInspect logs each unmet expectation
func (m *TokenServiceMock) MinimockGenerateRefreshTokenInspect() {
	for _, e := range m.GenerateRefreshTokenMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to TokenServiceMock.GenerateRefreshToken with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.GenerateRefreshTokenMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterGenerateRefreshTokenCounter) < 1 {
		if m.GenerateRefreshTokenMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to TokenServiceMock.GenerateRefreshToken")
		} else {
			m.t.Errorf("Expected call to TokenServiceMock.GenerateRefreshToken with params: %#v", *m.GenerateRefreshTokenMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGenerateRefreshToken != nil && mm_atomic.LoadUint64(&m.afterGenerateRefreshTokenCounter) < 1 {
		m.t.Error("Expected call to TokenServiceMock.GenerateRefreshToken")
	}
}

type mTokenServiceMockVerifyAccessToken struct {
	mock               *TokenServiceMock
	defaultExpectation *TokenServiceMockVerifyAccessTokenExpectation
	expectations       []*TokenServiceMockVerifyAccessTokenExpectation

	callArgs []*TokenServiceMockVerifyAccessTokenParams
	mutex    sync.RWMutex
}

// TokenServiceMockVerifyAccessTokenExpectation specifies expectation struct of the TokenService.VerifyAccessToken
type TokenServiceMockVerifyAccessTokenExpectation struct {
	mock    *TokenServiceMock
	params  *TokenServiceMockVerifyAccessTokenParams
	results *TokenServiceMockVerifyAccessTokenResults
	Counter uint64
}

// TokenServiceMockVerifyAccessTokenParams contains parameters of the TokenService.VerifyAccessToken
type TokenServiceMockVerifyAccessTokenParams struct {
	ctx context.Context
	s1  string
}

// TokenServiceMockVerifyAccessTokenResults contains results of the TokenService.VerifyAccessToken
type TokenServiceMockVerifyAccessTokenResults struct {
	up1 *mm_tokens.UserClaims
	err error
}

// Expect sets up expected params for TokenService.VerifyAccessToken
func (mmVerifyAccessToken *mTokenServiceMockVerifyAccessToken) Expect(ctx context.Context, s1 string) *mTokenServiceMockVerifyAccessToken {
	if mmVerifyAccessToken.mock.funcVerifyAccessToken != nil {
		mmVerifyAccessToken.mock.t.Fatalf("TokenServiceMock.VerifyAccessToken mock is already set by Set")
	}

	if mmVerifyAccessToken.defaultExpectation == nil {
		mmVerifyAccessToken.defaultExpectation = &TokenServiceMockVerifyAccessTokenExpectation{}
	}

	mmVerifyAccessToken.defaultExpectation.params = &TokenServiceMockVerifyAccessTokenParams{ctx, s1}
	for _, e := range mmVerifyAccessToken.expectations {
		if minimock.Equal(e.params, mmVerifyAccessToken.defaultExpectation.params) {
			mmVerifyAccessToken.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmVerifyAccessToken.defaultExpectation.params)
		}
	}

	return mmVerifyAccessToken
}

// Inspect accepts an inspector function that has same arguments as the TokenService.VerifyAccessToken
func (mmVerifyAccessToken *mTokenServiceMockVerifyAccessToken) Inspect(f func(ctx context.Context, s1 string)) *mTokenServiceMockVerifyAccessToken {
	if mmVerifyAccessToken.mock.inspectFuncVerifyAccessToken != nil {
		mmVerifyAccessToken.mock.t.Fatalf("Inspect function is already set for TokenServiceMock.VerifyAccessToken")
	}

	mmVerifyAccessToken.mock.inspectFuncVerifyAccessToken = f

	return mmVerifyAccessToken
}

// Return sets up results that will be returned by TokenService.VerifyAccessToken
func (mmVerifyAccessToken *mTokenServiceMockVerifyAccessToken) Return(up1 *mm_tokens.UserClaims, err error) *TokenServiceMock {
	if mmVerifyAccessToken.mock.funcVerifyAccessToken != nil {
		mmVerifyAccessToken.mock.t.Fatalf("TokenServiceMock.VerifyAccessToken mock is already set by Set")
	}

	if mmVerifyAccessToken.defaultExpectation == nil {
		mmVerifyAccessToken.defaultExpectation = &TokenServiceMockVerifyAccessTokenExpectation{mock: mmVerifyAccessToken.mock}
	}
	mmVerifyAccessToken.defaultExpectation.results = &TokenServiceMockVerifyAccessTokenResults{up1, err}
	return mmVerifyAccessToken.mock
}

// Set uses given function f to mock the TokenService.VerifyAccessToken method
func (mmVerifyAccessToken *mTokenServiceMockVerifyAccessToken) Set(f func(ctx context.Context, s1 string) (up1 *mm_tokens.UserClaims, err error)) *TokenServiceMock {
	if mmVerifyAccessToken.defaultExpectation != nil {
		mmVerifyAccessToken.mock.t.Fatalf("Default expectation is already set for the TokenService.VerifyAccessToken method")
	}

	if len(mmVerifyAccessToken.expectations) > 0 {
		mmVerifyAccessToken.mock.t.Fatalf("Some expectations are already set for the TokenService.VerifyAccessToken method")
	}

	mmVerifyAccessToken.mock.funcVerifyAccessToken = f
	return mmVerifyAccessToken.mock
}

// When sets expectation for the TokenService.VerifyAccessToken which will trigger the result defined by the following
// Then helper
func (mmVerifyAccessToken *mTokenServiceMockVerifyAccessToken) When(ctx context.Context, s1 string) *TokenServiceMockVerifyAccessTokenExpectation {
	if mmVerifyAccessToken.mock.funcVerifyAccessToken != nil {
		mmVerifyAccessToken.mock.t.Fatalf("TokenServiceMock.VerifyAccessToken mock is already set by Set")
	}

	expectation := &TokenServiceMockVerifyAccessTokenExpectation{
		mock:   mmVerifyAccessToken.mock,
		params: &TokenServiceMockVerifyAccessTokenParams{ctx, s1},
	}
	mmVerifyAccessToken.expectations = append(mmVerifyAccessToken.expectations, expectation)
	return expectation
}

// Then sets up TokenService.VerifyAccessToken return parameters for the expectation previously defined by the When method
func (e *TokenServiceMockVerifyAccessTokenExpectation) Then(up1 *mm_tokens.UserClaims, err error) *TokenServiceMock {
	e.results = &TokenServiceMockVerifyAccessTokenResults{up1, err}
	return e.mock
}

// VerifyAccessToken implements tokens.TokenService
func (mmVerifyAccessToken *TokenServiceMock) VerifyAccessToken(ctx context.Context, s1 string) (up1 *mm_tokens.UserClaims, err error) {
	mm_atomic.AddUint64(&mmVerifyAccessToken.beforeVerifyAccessTokenCounter, 1)
	defer mm_atomic.AddUint64(&mmVerifyAccessToken.afterVerifyAccessTokenCounter, 1)

	if mmVerifyAccessToken.inspectFuncVerifyAccessToken != nil {
		mmVerifyAccessToken.inspectFuncVerifyAccessToken(ctx, s1)
	}

	mm_params := TokenServiceMockVerifyAccessTokenParams{ctx, s1}

	// Record call args
	mmVerifyAccessToken.VerifyAccessTokenMock.mutex.Lock()
	mmVerifyAccessToken.VerifyAccessTokenMock.callArgs = append(mmVerifyAccessToken.VerifyAccessTokenMock.callArgs, &mm_params)
	mmVerifyAccessToken.VerifyAccessTokenMock.mutex.Unlock()

	for _, e := range mmVerifyAccessToken.VerifyAccessTokenMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.up1, e.results.err
		}
	}

	if mmVerifyAccessToken.VerifyAccessTokenMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmVerifyAccessToken.VerifyAccessTokenMock.defaultExpectation.Counter, 1)
		mm_want := mmVerifyAccessToken.VerifyAccessTokenMock.defaultExpectation.params
		mm_got := TokenServiceMockVerifyAccessTokenParams{ctx, s1}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmVerifyAccessToken.t.Errorf("TokenServiceMock.VerifyAccessToken got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmVerifyAccessToken.VerifyAccessTokenMock.defaultExpectation.results
		if mm_results == nil {
			mmVerifyAccessToken.t.Fatal("No results are set for the TokenServiceMock.VerifyAccessToken")
		}
		return (*mm_results).up1, (*mm_results).err
	}
	if mmVerifyAccessToken.funcVerifyAccessToken != nil {
		return mmVerifyAccessToken.funcVerifyAccessToken(ctx, s1)
	}
	mmVerifyAccessToken.t.Fatalf("Unexpected call to TokenServiceMock.VerifyAccessToken. %v %v", ctx, s1)
	return
}

// VerifyAccessTokenAfterCounter returns a count of finished TokenServiceMock.VerifyAccessToken invocations
func (mmVerifyAccessToken *TokenServiceMock) VerifyAccessTokenAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmVerifyAccessToken.afterVerifyAccessTokenCounter)
}

// VerifyAccessTokenBeforeCounter returns a count of TokenServiceMock.VerifyAccessToken invocations
func (mmVerifyAccessToken *TokenServiceMock) VerifyAccessTokenBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmVerifyAccessToken.beforeVerifyAccessTokenCounter)
}

// Calls returns a list of arguments used in each call to TokenServiceMock.VerifyAccessToken.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmVerifyAccessToken *mTokenServiceMockVerifyAccessToken) Calls() []*TokenServiceMockVerifyAccessTokenParams {
	mmVerifyAccessToken.mutex.RLock()

	argCopy := make([]*TokenServiceMockVerifyAccessTokenParams, len(mmVerifyAccessToken.callArgs))
	copy(argCopy, mmVerifyAccessToken.callArgs)

	mmVerifyAccessToken.mutex.RUnlock()

	return argCopy
}

// MinimockVerifyAccessTokenDone returns true if the count of the VerifyAccessToken invocations corresponds
// the number of defined expectations
func (m *TokenServiceMock) MinimockVerifyAccessTokenDone() bool {
	for _, e := range m.VerifyAccessTokenMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.VerifyAccessTokenMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterVerifyAccessTokenCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcVerifyAccessToken != nil && mm_atomic.LoadUint64(&m.afterVerifyAccessTokenCounter) < 1 {
		return false
	}
	return true
}

// MinimockVerifyAccessTokenInspect logs each unmet expectation
func (m *TokenServiceMock) MinimockVerifyAccessTokenInspect() {
	for _, e := range m.VerifyAccessTokenMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to TokenServiceMock.VerifyAccessToken with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.VerifyAccessTokenMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterVerifyAccessTokenCounter) < 1 {
		if m.VerifyAccessTokenMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to TokenServiceMock.VerifyAccessToken")
		} else {
			m.t.Errorf("Expected call to TokenServiceMock.VerifyAccessToken with params: %#v", *m.VerifyAccessTokenMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcVerifyAccessToken != nil && mm_atomic.LoadUint64(&m.afterVerifyAccessTokenCounter) < 1 {
		m.t.Error("Expected call to TokenServiceMock.VerifyAccessToken")
	}
}

type mTokenServiceMockVerifyRefreshToken struct {
	mock               *TokenServiceMock
	defaultExpectation *TokenServiceMockVerifyRefreshTokenExpectation
	expectations       []*TokenServiceMockVerifyRefreshTokenExpectation

	callArgs []*TokenServiceMockVerifyRefreshTokenParams
	mutex    sync.RWMutex
}

// TokenServiceMockVerifyRefreshTokenExpectation specifies expectation struct of the TokenService.VerifyRefreshToken
type TokenServiceMockVerifyRefreshTokenExpectation struct {
	mock    *TokenServiceMock
	params  *TokenServiceMockVerifyRefreshTokenParams
	results *TokenServiceMockVerifyRefreshTokenResults
	Counter uint64
}

// TokenServiceMockVerifyRefreshTokenParams contains parameters of the TokenService.VerifyRefreshToken
type TokenServiceMockVerifyRefreshTokenParams struct {
	ctx context.Context
	s1  string
}

// TokenServiceMockVerifyRefreshTokenResults contains results of the TokenService.VerifyRefreshToken
type TokenServiceMockVerifyRefreshTokenResults struct {
	up1 *mm_tokens.UserClaims
	err error
}

// Expect sets up expected params for TokenService.VerifyRefreshToken
func (mmVerifyRefreshToken *mTokenServiceMockVerifyRefreshToken) Expect(ctx context.Context, s1 string) *mTokenServiceMockVerifyRefreshToken {
	if mmVerifyRefreshToken.mock.funcVerifyRefreshToken != nil {
		mmVerifyRefreshToken.mock.t.Fatalf("TokenServiceMock.VerifyRefreshToken mock is already set by Set")
	}

	if mmVerifyRefreshToken.defaultExpectation == nil {
		mmVerifyRefreshToken.defaultExpectation = &TokenServiceMockVerifyRefreshTokenExpectation{}
	}

	mmVerifyRefreshToken.defaultExpectation.params = &TokenServiceMockVerifyRefreshTokenParams{ctx, s1}
	for _, e := range mmVerifyRefreshToken.expectations {
		if minimock.Equal(e.params, mmVerifyRefreshToken.defaultExpectation.params) {
			mmVerifyRefreshToken.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmVerifyRefreshToken.defaultExpectation.params)
		}
	}

	return mmVerifyRefreshToken
}

// Inspect accepts an inspector function that has same arguments as the TokenService.VerifyRefreshToken
func (mmVerifyRefreshToken *mTokenServiceMockVerifyRefreshToken) Inspect(f func(ctx context.Context, s1 string)) *mTokenServiceMockVerifyRefreshToken {
	if mmVerifyRefreshToken.mock.inspectFuncVerifyRefreshToken != nil {
		mmVerifyRefreshToken.mock.t.Fatalf("Inspect function is already set for TokenServiceMock.VerifyRefreshToken")
	}

	mmVerifyRefreshToken.mock.inspectFuncVerifyRefreshToken = f

	return mmVerifyRefreshToken
}

// Return sets up results that will be returned by TokenService.VerifyRefreshToken
func (mmVerifyRefreshToken *mTokenServiceMockVerifyRefreshToken) Return(up1 *mm_tokens.UserClaims, err error) *TokenServiceMock {
	if mmVerifyRefreshToken.mock.funcVerifyRefreshToken != nil {
		mmVerifyRefreshToken.mock.t.Fatalf("TokenServiceMock.VerifyRefreshToken mock is already set by Set")
	}

	if mmVerifyRefreshToken.defaultExpectation == nil {
		mmVerifyRefreshToken.defaultExpectation = &TokenServiceMockVerifyRefreshTokenExpectation{mock: mmVerifyRefreshToken.mock}
	}
	mmVerifyRefreshToken.defaultExpectation.results = &TokenServiceMockVerifyRefreshTokenResults{up1, err}
	return mmVerifyRefreshToken.mock
}

// Set uses given function f to mock the TokenService.VerifyRefreshToken method
func (mmVerifyRefreshToken *mTokenServiceMockVerifyRefreshToken) Set(f func(ctx context.Context, s1 string) (up1 *mm_tokens.UserClaims, err error)) *TokenServiceMock {
	if mmVerifyRefreshToken.defaultExpectation != nil {
		mmVerifyRefreshToken.mock.t.Fatalf("Default expectation is already set for the TokenService.VerifyRefreshToken method")
	}

	if len(mmVerifyRefreshToken.expectations) > 0 {
		mmVerifyRefreshToken.mock.t.Fatalf("Some expectations are already set for the TokenService.VerifyRefreshToken method")
	}

	mmVerifyRefreshToken.mock.funcVerifyRefreshToken = f
	return mmVerifyRefreshToken.mock
}

// When sets expectation for the TokenService.VerifyRefreshToken which will trigger the result defined by the following
// Then helper
func (mmVerifyRefreshToken *mTokenServiceMockVerifyRefreshToken) When(ctx context.Context, s1 string) *TokenServiceMockVerifyRefreshTokenExpectation {
	if mmVerifyRefreshToken.mock.funcVerifyRefreshToken != nil {
		mmVerifyRefreshToken.mock.t.Fatalf("TokenServiceMock.VerifyRefreshToken mock is already set by Set")
	}

	expectation := &TokenServiceMockVerifyRefreshTokenExpectation{
		mock:   mmVerifyRefreshToken.mock,
		params: &TokenServiceMockVerifyRefreshTokenParams{ctx, s1},
	}
	mmVerifyRefreshToken.expectations = append(mmVerifyRefreshToken.expectations, expectation)
	return expectation
}

// Then sets up TokenService.VerifyRefreshToken return parameters for the expectation previously defined by the When method
func (e *TokenServiceMockVerifyRefreshTokenExpectation) Then(up1 *mm_tokens.UserClaims, err error) *TokenServiceMock {
	e.results = &TokenServiceMockVerifyRefreshTokenResults{up1, err}
	return e.mock
}

// VerifyRefreshToken implements tokens.TokenService
func (mmVerifyRefreshToken *TokenServiceMock) VerifyRefreshToken(ctx context.Context, s1 string) (up1 *mm_tokens.UserClaims, err error) {
	mm_atomic.AddUint64(&mmVerifyRefreshToken.beforeVerifyRefreshTokenCounter, 1)
	defer mm_atomic.AddUint64(&mmVerifyRefreshToken.afterVerifyRefreshTokenCounter, 1)

	if mmVerifyRefreshToken.inspectFuncVerifyRefreshToken != nil {
		mmVerifyRefreshToken.inspectFuncVerifyRefreshToken(ctx, s1)
	}

	mm_params := TokenServiceMockVerifyRefreshTokenParams{ctx, s1}

	// Record call args
	mmVerifyRefreshToken.VerifyRefreshTokenMock.mutex.Lock()
	mmVerifyRefreshToken.VerifyRefreshTokenMock.callArgs = append(mmVerifyRefreshToken.VerifyRefreshTokenMock.callArgs, &mm_params)
	mmVerifyRefreshToken.VerifyRefreshTokenMock.mutex.Unlock()

	for _, e := range mmVerifyRefreshToken.VerifyRefreshTokenMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.up1, e.results.err
		}
	}

	if mmVerifyRefreshToken.VerifyRefreshTokenMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmVerifyRefreshToken.VerifyRefreshTokenMock.defaultExpectation.Counter, 1)
		mm_want := mmVerifyRefreshToken.VerifyRefreshTokenMock.defaultExpectation.params
		mm_got := TokenServiceMockVerifyRefreshTokenParams{ctx, s1}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmVerifyRefreshToken.t.Errorf("TokenServiceMock.VerifyRefreshToken got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmVerifyRefreshToken.VerifyRefreshTokenMock.defaultExpectation.results
		if mm_results == nil {
			mmVerifyRefreshToken.t.Fatal("No results are set for the TokenServiceMock.VerifyRefreshToken")
		}
		return (*mm_results).up1, (*mm_results).err
	}
	if mmVerifyRefreshToken.funcVerifyRefreshToken != nil {
		return mmVerifyRefreshToken.funcVerifyRefreshToken(ctx, s1)
	}
	mmVerifyRefreshToken.t.Fatalf("Unexpected call to TokenServiceMock.VerifyRefreshToken. %v %v", ctx, s1)
	return
}

// VerifyRefreshTokenAfterCounter returns a count of finished TokenServiceMock.VerifyRefreshToken invocations
func (mmVerifyRefreshToken *TokenServiceMock) VerifyRefreshTokenAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmVerifyRefreshToken.afterVerifyRefreshTokenCounter)
}

// VerifyRefreshTokenBeforeCounter returns a count of TokenServiceMock.VerifyRefreshToken invocations
func (mmVerifyRefreshToken *TokenServiceMock) VerifyRefreshTokenBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmVerifyRefreshToken.beforeVerifyRefreshTokenCounter)
}

// Calls returns a list of arguments used in each call to TokenServiceMock.VerifyRefreshToken.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmVerifyRefreshToken *mTokenServiceMockVerifyRefreshToken) Calls() []*TokenServiceMockVerifyRefreshTokenParams {
	mmVerifyRefreshToken.mutex.RLock()

	argCopy := make([]*TokenServiceMockVerifyRefreshTokenParams, len(mmVerifyRefreshToken.callArgs))
	copy(argCopy, mmVerifyRefreshToken.callArgs)

	mmVerifyRefreshToken.mutex.RUnlock()

	return argCopy
}

// MinimockVerifyRefreshTokenDone returns true if the count of the VerifyRefreshToken invocations corresponds
// the number of defined expectations
func (m *TokenServiceMock) MinimockVerifyRefreshTokenDone() bool {
	for _, e := range m.VerifyRefreshTokenMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.VerifyRefreshTokenMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterVerifyRefreshTokenCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcVerifyRefreshToken != nil && mm_atomic.LoadUint64(&m.afterVerifyRefreshTokenCounter) < 1 {
		return false
	}
	return true
}

// MinimockVerifyRefreshTokenInspect logs each unmet expectation
func (m *TokenServiceMock) MinimockVerifyRefreshTokenInspect() {
	for _, e := range m.VerifyRefreshTokenMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to TokenServiceMock.VerifyRefreshToken with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.VerifyRefreshTokenMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterVerifyRefreshTokenCounter) < 1 {
		if m.VerifyRefreshTokenMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to TokenServiceMock.VerifyRefreshToken")
		} else {
			m.t.Errorf("Expected call to TokenServiceMock.VerifyRefreshToken with params: %#v", *m.VerifyRefreshTokenMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcVerifyRefreshToken != nil && mm_atomic.LoadUint64(&m.afterVerifyRefreshTokenCounter) < 1 {
		m.t.Error("Expected call to TokenServiceMock.VerifyRefreshToken")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *TokenServiceMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockGenerateAccessTokenInspect()

			m.MinimockGenerateRefreshTokenInspect()

			m.MinimockVerifyAccessTokenInspect()

			m.MinimockVerifyRefreshTokenInspect()
			m.t.FailNow()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *TokenServiceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *TokenServiceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockGenerateAccessTokenDone() &&
		m.MinimockGenerateRefreshTokenDone() &&
		m.MinimockVerifyAccessTokenDone() &&
		m.MinimockVerifyRefreshTokenDone()
}
