// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: storage.proto

package storagev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataStorageService_StoreObject_FullMethodName             = "/opens3.storage.v1.DataStorageService/StoreObject"
	DataStorageService_RetrieveObject_FullMethodName          = "/opens3.storage.v1.DataStorageService/RetrieveObject"
	DataStorageService_DeleteObject_FullMethodName            = "/opens3.storage.v1.DataStorageService/DeleteObject"
	DataStorageService_InitiateMultipartUpload_FullMethodName = "/opens3.storage.v1.DataStorageService/InitiateMultipartUpload"
	DataStorageService_UploadPart_FullMethodName              = "/opens3.storage.v1.DataStorageService/UploadPart"
	DataStorageService_CompleteMultipartUpload_FullMethodName = "/opens3.storage.v1.DataStorageService/CompleteMultipartUpload"
	DataStorageService_AbortMultipartUpload_FullMethodName    = "/opens3.storage.v1.DataStorageService/AbortMultipartUpload"
	DataStorageService_HealthCheck_FullMethodName             = "/opens3.storage.v1.DataStorageService/HealthCheck"
)

// DataStorageServiceClient is the client API for DataStorageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DataStorageService — единственный сервис, хранящий байты на диске.
// Работает только с blob_id (UUID) и не знает о S3 API, бакетах, ключах или правах доступа.
// Вызывается только Gateway.
//
// Порт: 50053 (конфигурируется через GRPC_PORT)
//
// Структура хранилища на диске:
//
//	{DATA_DIR}/{shard}/{blob_id}                       — готовые объекты
//	{MULTIPART_DIR}/uploads/{upload_id}/               — multipart session + parts
//	{MULTIPART_DIR}/uploads/{blob_id}/                 — staging single-part upload
//	{MULTIPART_DIR}/completed/{shard}/{upload_id}.json — marker для идемпотентного CompleteMultipartUpload
//
// Kafka:
//
//	Потребляет ← object-deleted: получает blob_id → удаляет файл с диска (идемпотентно)
//	Публикует  → object-stored:  после успешного StoreObject (резервный путь для Metadata)
type DataStorageServiceClient interface {
	// StoreObject принимает поток байт и сохраняет их как blob на диск.
	// Client-streaming: первое сообщение должно быть header, все последующие — chunk.
	// Header содержит metadata и может также содержать первые байты файла.
	// Возвращает blob_id (UUID) и MD5 для последующей регистрации в Metadata.
	// Ошибки: RESOURCE_EXHAUSTED (недостаточно места), INTERNAL.
	StoreObject(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[StoreObjectRequest, StoreObjectResponse], error)
	// RetrieveObject читает blob с диска и стримит байты в Gateway.
	// Server-streaming: сервис отправляет файл чанками.
	// Поддерживает range-запросы (для HTTP Range-заголовка).
	// Ошибки: NOT_FOUND (blob_id не существует), INTERNAL.
	RetrieveObject(ctx context.Context, in *RetrieveObjectRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RetrieveObjectResponse], error)
	// DeleteObject удаляет blob с диска по blob_id.
	// Как правило, вызывается из Kafka-консьюмера при получении object-deleted, не напрямую.
	// Идемпотентен: удаление несуществующего blob_id — не ошибка, возвращает success=true.
	DeleteObject(ctx context.Context, in *DeleteObjectRequest, opts ...grpc.CallOption) (*DeleteObjectResponse, error)
	// InitiateMultipartUpload открывает новую сессию составной загрузки.
	// Возвращает upload_id для последующих вызовов UploadPart.
	InitiateMultipartUpload(ctx context.Context, in *InitiateMultipartUploadRequest, opts ...grpc.CallOption) (*InitiateMultipartUploadResponse, error)
	// UploadPart сохраняет одну часть multipart-загрузки.
	// Client-streaming: первое сообщение должно быть header, все последующие — chunk.
	// Header содержит upload_id/part_number и может также содержать первые байты части.
	// Части хранятся как {MULTIPART_DIR}/uploads/{upload_id}/part_{part_number}.
	// Ошибки: NOT_FOUND (upload_id не существует), INVALID_ARGUMENT (неверный part_number).
	UploadPart(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadPartRequest, UploadPartResponse], error)
	// CompleteMultipartUpload склеивает все загруженные части в единый blob.
	// Возвращает итоговый blob_id и MD5 для регистрации в Metadata.
	// Удаляет временные файлы частей после склейки.
	// Ошибки: NOT_FOUND (upload_id не существует), INVALID_ARGUMENT (несовпадение чексумм).
	CompleteMultipartUpload(ctx context.Context, in *CompleteMultipartUploadRequest, opts ...grpc.CallOption) (*CompleteMultipartUploadResponse, error)
	// AbortMultipartUpload отменяет multipart-загрузку и удаляет все временные части.
	// Идемпотентен: отмена несуществующего upload_id — не ошибка.
	AbortMultipartUpload(ctx context.Context, in *AbortMultipartUploadRequest, opts ...grpc.CallOption) (*AbortMultipartUploadResponse, error)
	// HealthCheck — стандартный gRPC Health Checking Protocol.
	// Используется Kubernetes liveness/readiness probe и Gateway /ready.
	// NOT_SERVING возвращается если DATA_DIR недоступна или недостаточно места (RESOURCE_EXHAUSTED).
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type dataStorageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataStorageServiceClient(cc grpc.ClientConnInterface) DataStorageServiceClient {
	return &dataStorageServiceClient{cc}
}

func (c *dataStorageServiceClient) StoreObject(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[StoreObjectRequest, StoreObjectResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataStorageService_ServiceDesc.Streams[0], DataStorageService_StoreObject_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StoreObjectRequest, StoreObjectResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataStorageService_StoreObjectClient = grpc.ClientStreamingClient[StoreObjectRequest, StoreObjectResponse]

func (c *dataStorageServiceClient) RetrieveObject(ctx context.Context, in *RetrieveObjectRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RetrieveObjectResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataStorageService_ServiceDesc.Streams[1], DataStorageService_RetrieveObject_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RetrieveObjectRequest, RetrieveObjectResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataStorageService_RetrieveObjectClient = grpc.ServerStreamingClient[RetrieveObjectResponse]

func (c *dataStorageServiceClient) DeleteObject(ctx context.Context, in *DeleteObjectRequest, opts ...grpc.CallOption) (*DeleteObjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteObjectResponse)
	err := c.cc.Invoke(ctx, DataStorageService_DeleteObject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataStorageServiceClient) InitiateMultipartUpload(ctx context.Context, in *InitiateMultipartUploadRequest, opts ...grpc.CallOption) (*InitiateMultipartUploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitiateMultipartUploadResponse)
	err := c.cc.Invoke(ctx, DataStorageService_InitiateMultipartUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataStorageServiceClient) UploadPart(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadPartRequest, UploadPartResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataStorageService_ServiceDesc.Streams[2], DataStorageService_UploadPart_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadPartRequest, UploadPartResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataStorageService_UploadPartClient = grpc.ClientStreamingClient[UploadPartRequest, UploadPartResponse]

func (c *dataStorageServiceClient) CompleteMultipartUpload(ctx context.Context, in *CompleteMultipartUploadRequest, opts ...grpc.CallOption) (*CompleteMultipartUploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteMultipartUploadResponse)
	err := c.cc.Invoke(ctx, DataStorageService_CompleteMultipartUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataStorageServiceClient) AbortMultipartUpload(ctx context.Context, in *AbortMultipartUploadRequest, opts ...grpc.CallOption) (*AbortMultipartUploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AbortMultipartUploadResponse)
	err := c.cc.Invoke(ctx, DataStorageService_AbortMultipartUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataStorageServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, DataStorageService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataStorageServiceServer is the server API for DataStorageService service.
// All implementations must embed UnimplementedDataStorageServiceServer
// for forward compatibility.
//
// DataStorageService — единственный сервис, хранящий байты на диске.
// Работает только с blob_id (UUID) и не знает о S3 API, бакетах, ключах или правах доступа.
// Вызывается только Gateway.
//
// Порт: 50053 (конфигурируется через GRPC_PORT)
//
// Структура хранилища на диске:
//
//	{DATA_DIR}/{shard}/{blob_id}                       — готовые объекты
//	{MULTIPART_DIR}/uploads/{upload_id}/               — multipart session + parts
//	{MULTIPART_DIR}/uploads/{blob_id}/                 — staging single-part upload
//	{MULTIPART_DIR}/completed/{shard}/{upload_id}.json — marker для идемпотентного CompleteMultipartUpload
//
// Kafka:
//
//	Потребляет ← object-deleted: получает blob_id → удаляет файл с диска (идемпотентно)
//	Публикует  → object-stored:  после успешного StoreObject (резервный путь для Metadata)
type DataStorageServiceServer interface {
	// StoreObject принимает поток байт и сохраняет их как blob на диск.
	// Client-streaming: первое сообщение должно быть header, все последующие — chunk.
	// Header содержит metadata и может также содержать первые байты файла.
	// Возвращает blob_id (UUID) и MD5 для последующей регистрации в Metadata.
	// Ошибки: RESOURCE_EXHAUSTED (недостаточно места), INTERNAL.
	StoreObject(grpc.ClientStreamingServer[StoreObjectRequest, StoreObjectResponse]) error
	// RetrieveObject читает blob с диска и стримит байты в Gateway.
	// Server-streaming: сервис отправляет файл чанками.
	// Поддерживает range-запросы (для HTTP Range-заголовка).
	// Ошибки: NOT_FOUND (blob_id не существует), INTERNAL.
	RetrieveObject(*RetrieveObjectRequest, grpc.ServerStreamingServer[RetrieveObjectResponse]) error
	// DeleteObject удаляет blob с диска по blob_id.
	// Как правило, вызывается из Kafka-консьюмера при получении object-deleted, не напрямую.
	// Идемпотентен: удаление несуществующего blob_id — не ошибка, возвращает success=true.
	DeleteObject(context.Context, *DeleteObjectRequest) (*DeleteObjectResponse, error)
	// InitiateMultipartUpload открывает новую сессию составной загрузки.
	// Возвращает upload_id для последующих вызовов UploadPart.
	InitiateMultipartUpload(context.Context, *InitiateMultipartUploadRequest) (*InitiateMultipartUploadResponse, error)
	// UploadPart сохраняет одну часть multipart-загрузки.
	// Client-streaming: первое сообщение должно быть header, все последующие — chunk.
	// Header содержит upload_id/part_number и может также содержать первые байты части.
	// Части хранятся как {MULTIPART_DIR}/uploads/{upload_id}/part_{part_number}.
	// Ошибки: NOT_FOUND (upload_id не существует), INVALID_ARGUMENT (неверный part_number).
	UploadPart(grpc.ClientStreamingServer[UploadPartRequest, UploadPartResponse]) error
	// CompleteMultipartUpload склеивает все загруженные части в единый blob.
	// Возвращает итоговый blob_id и MD5 для регистрации в Metadata.
	// Удаляет временные файлы частей после склейки.
	// Ошибки: NOT_FOUND (upload_id не существует), INVALID_ARGUMENT (несовпадение чексумм).
	CompleteMultipartUpload(context.Context, *CompleteMultipartUploadRequest) (*CompleteMultipartUploadResponse, error)
	// AbortMultipartUpload отменяет multipart-загрузку и удаляет все временные части.
	// Идемпотентен: отмена несуществующего upload_id — не ошибка.
	AbortMultipartUpload(context.Context, *AbortMultipartUploadRequest) (*AbortMultipartUploadResponse, error)
	// HealthCheck — стандартный gRPC Health Checking Protocol.
	// Используется Kubernetes liveness/readiness probe и Gateway /ready.
	// NOT_SERVING возвращается если DATA_DIR недоступна или недостаточно места (RESOURCE_EXHAUSTED).
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedDataStorageServiceServer()
}

// UnimplementedDataStorageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataStorageServiceServer struct{}

func (UnimplementedDataStorageServiceServer) StoreObject(grpc.ClientStreamingServer[StoreObjectRequest, StoreObjectResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StoreObject not implemented")
}
func (UnimplementedDataStorageServiceServer) RetrieveObject(*RetrieveObjectRequest, grpc.ServerStreamingServer[RetrieveObjectResponse]) error {
	return status.Errorf(codes.Unimplemented, "method RetrieveObject not implemented")
}
func (UnimplementedDataStorageServiceServer) DeleteObject(context.Context, *DeleteObjectRequest) (*DeleteObjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteObject not implemented")
}
func (UnimplementedDataStorageServiceServer) InitiateMultipartUpload(context.Context, *InitiateMultipartUploadRequest) (*InitiateMultipartUploadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitiateMultipartUpload not implemented")
}
func (UnimplementedDataStorageServiceServer) UploadPart(grpc.ClientStreamingServer[UploadPartRequest, UploadPartResponse]) error {
	return status.Errorf(codes.Unimplemented, "method UploadPart not implemented")
}
func (UnimplementedDataStorageServiceServer) CompleteMultipartUpload(context.Context, *CompleteMultipartUploadRequest) (*CompleteMultipartUploadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteMultipartUpload not implemented")
}
func (UnimplementedDataStorageServiceServer) AbortMultipartUpload(context.Context, *AbortMultipartUploadRequest) (*AbortMultipartUploadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AbortMultipartUpload not implemented")
}
func (UnimplementedDataStorageServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedDataStorageServiceServer) mustEmbedUnimplementedDataStorageServiceServer() {}
func (UnimplementedDataStorageServiceServer) testEmbeddedByValue()                            {}

// UnsafeDataStorageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataStorageServiceServer will
// result in compilation errors.
type UnsafeDataStorageServiceServer interface {
	mustEmbedUnimplementedDataStorageServiceServer()
}

func RegisterDataStorageServiceServer(s grpc.ServiceRegistrar, srv DataStorageServiceServer) {
	// If the following call pancis, it indicates UnimplementedDataStorageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataStorageService_ServiceDesc, srv)
}

func _DataStorageService_StoreObject_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DataStorageServiceServer).StoreObject(&grpc.GenericServerStream[StoreObjectRequest, StoreObjectResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataStorageService_StoreObjectServer = grpc.ClientStreamingServer[StoreObjectRequest, StoreObjectResponse]

func _DataStorageService_RetrieveObject_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RetrieveObjectRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DataStorageServiceServer).RetrieveObject(m, &grpc.GenericServerStream[RetrieveObjectRequest, RetrieveObjectResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataStorageService_RetrieveObjectServer = grpc.ServerStreamingServer[RetrieveObjectResponse]

func _DataStorageService_DeleteObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataStorageServiceServer).DeleteObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataStorageService_DeleteObject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataStorageServiceServer).DeleteObject(ctx, req.(*DeleteObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataStorageService_InitiateMultipartUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitiateMultipartUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataStorageServiceServer).InitiateMultipartUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataStorageService_InitiateMultipartUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataStorageServiceServer).InitiateMultipartUpload(ctx, req.(*InitiateMultipartUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataStorageService_UploadPart_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DataStorageServiceServer).UploadPart(&grpc.GenericServerStream[UploadPartRequest, UploadPartResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataStorageService_UploadPartServer = grpc.ClientStreamingServer[UploadPartRequest, UploadPartResponse]

func _DataStorageService_CompleteMultipartUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteMultipartUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataStorageServiceServer).CompleteMultipartUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataStorageService_CompleteMultipartUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataStorageServiceServer).CompleteMultipartUpload(ctx, req.(*CompleteMultipartUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataStorageService_AbortMultipartUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbortMultipartUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataStorageServiceServer).AbortMultipartUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataStorageService_AbortMultipartUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataStorageServiceServer).AbortMultipartUpload(ctx, req.(*AbortMultipartUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataStorageService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataStorageServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataStorageService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataStorageServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataStorageService_ServiceDesc is the grpc.ServiceDesc for DataStorageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataStorageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "opens3.storage.v1.DataStorageService",
	HandlerType: (*DataStorageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeleteObject",
			Handler:    _DataStorageService_DeleteObject_Handler,
		},
		{
			MethodName: "InitiateMultipartUpload",
			Handler:    _DataStorageService_InitiateMultipartUpload_Handler,
		},
		{
			MethodName: "CompleteMultipartUpload",
			Handler:    _DataStorageService_CompleteMultipartUpload_Handler,
		},
		{
			MethodName: "AbortMultipartUpload",
			Handler:    _DataStorageService_AbortMultipartUpload_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _DataStorageService_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StoreObject",
			Handler:       _DataStorageService_StoreObject_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "RetrieveObject",
			Handler:       _DataStorageService_RetrieveObject_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "UploadPart",
			Handler:       _DataStorageService_UploadPart_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "storage.proto",
}
