# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import authz_pb2 as authz__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in authz_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PermissionServiceStub(object):
    """AuthZService — ReBAC-движок авторизации для OpenS3.
    Отвечает на вопрос: "может ли <subject> выполнить <action> над <object>?"

    ─── Формат Entity ID ────────────────────────────────────────────────────────
    user:<uuid>               — пользователь (UUID из JWT sub, напр. "user:550e8400-...")
    group:<name>              — логическая группа (напр. "group:devops")
    bucket:<name>             — S3 бакет (напр. "bucket:my-photos")
    object:<bucket>/<key>     — S3 объект (напр. "object:my-photos/2024/cat.jpg")

    ─── Маппинг S3 операций → action ────────────────────────────────────────────
    read    → GetObject, HeadObject, ListObjects, HeadBucket, ListBuckets
    write   → PutObject, UploadPart, CompleteMultipartUpload
    delete  → DeleteObject
    create  → CreateBucket, CreateMultipartUpload, AbortMultipartUpload
    admin   → DeleteBucket, выдача/отзыв прав

    ─── Иерархия уровней HAS_PERMISSION ─────────────────────────────────────────
    admin > delete > create > write > read
    (каждый уровень включает все нижестоящие)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Check = channel.unary_unary(
                '/opens3.authz.v1.PermissionService/Check',
                request_serializer=authz__pb2.CheckRequest.SerializeToString,
                response_deserializer=authz__pb2.CheckResponse.FromString,
                _registered_method=True)
        self.WriteTuple = channel.unary_unary(
                '/opens3.authz.v1.PermissionService/WriteTuple',
                request_serializer=authz__pb2.WriteTupleRequest.SerializeToString,
                response_deserializer=authz__pb2.WriteTupleResponse.FromString,
                _registered_method=True)
        self.DeleteTuple = channel.unary_unary(
                '/opens3.authz.v1.PermissionService/DeleteTuple',
                request_serializer=authz__pb2.DeleteTupleRequest.SerializeToString,
                response_deserializer=authz__pb2.DeleteTupleResponse.FromString,
                _registered_method=True)
        self.Read = channel.unary_unary(
                '/opens3.authz.v1.PermissionService/Read',
                request_serializer=authz__pb2.ReadRequest.SerializeToString,
                response_deserializer=authz__pb2.ReadResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/opens3.authz.v1.PermissionService/HealthCheck',
                request_serializer=authz__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=authz__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class PermissionServiceServicer(object):
    """AuthZService — ReBAC-движок авторизации для OpenS3.
    Отвечает на вопрос: "может ли <subject> выполнить <action> над <object>?"

    ─── Формат Entity ID ────────────────────────────────────────────────────────
    user:<uuid>               — пользователь (UUID из JWT sub, напр. "user:550e8400-...")
    group:<name>              — логическая группа (напр. "group:devops")
    bucket:<name>             — S3 бакет (напр. "bucket:my-photos")
    object:<bucket>/<key>     — S3 объект (напр. "object:my-photos/2024/cat.jpg")

    ─── Маппинг S3 операций → action ────────────────────────────────────────────
    read    → GetObject, HeadObject, ListObjects, HeadBucket, ListBuckets
    write   → PutObject, UploadPart, CompleteMultipartUpload
    delete  → DeleteObject
    create  → CreateBucket, CreateMultipartUpload, AbortMultipartUpload
    admin   → DeleteBucket, выдача/отзыв прав

    ─── Иерархия уровней HAS_PERMISSION ─────────────────────────────────────────
    admin > delete > create > write > read
    (каждый уровень включает все нижестоящие)
    """

    def Check(self, request, context):
        """Check проверяет, разрешено ли действие.
        Вызывается Gateway перед каждой S3-операцией.
        Сначала проверяет кэш Redis (TTL ~30 с), при промахе — обходит граф Neo4j.
        Публикует аудит-событие (ACCESS_GRANTED / ACCESS_DENIED) в топик auth-audit.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteTuple(self, request, context):
        """WriteTuple создаёт ребро в графе прав.
        Использование:
        — назначить владельца бакета при CreateBucket:
        subject=user:<id>, relation=OWNER_OF, object=bucket:<name>
        — связать объект с бакетом после PutObject:
        subject=bucket:<name>, relation=PARENT_OF, object=object:<bucket>/<key>
        — выдать права пользователю/группе:
        subject=user:<id>, relation=HAS_PERMISSION, object=bucket:<name>, level=read
        — добавить пользователя в группу:
        subject=user:<id>, relation=MEMBER_OF, object=group:<name>
        После записи публикует событие tuple_written в топик auth-changes (инвалидация кэша).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTuple(self, request, context):
        """DeleteTuple удаляет ребро из графа прав.
        Используется для отзыва прав или исключения из группы.
        После удаления публикует событие tuple_removed в топик auth-changes (инвалидация кэша).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Read(self, request, context):
        """Read возвращает все прямые (не транзитивные) исходящие связи subject'а.
        Полезно для ответа на вопрос "куда у пользователя есть доступ" без знания конкретных ресурсов.
        Примеры результатов:
        subject=user:alice, relation=MEMBER_OF, object=group:devops
        subject=user:alice, relation=OWNER_OF,  object=bucket:my-photos
        subject=user:alice, relation=HAS_PERMISSION, object=bucket:shared, level=read
        Используется в админском UI, при отладке, при отображении "мои права".
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """HealthCheck — стандартный gRPC Health Checking Protocol.
        Используется Kubernetes liveness/readiness probe и Gateway /ready.
        service="" проверяет весь процесс; service="PermissionService" — конкретный сервис.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PermissionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Check': grpc.unary_unary_rpc_method_handler(
                    servicer.Check,
                    request_deserializer=authz__pb2.CheckRequest.FromString,
                    response_serializer=authz__pb2.CheckResponse.SerializeToString,
            ),
            'WriteTuple': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteTuple,
                    request_deserializer=authz__pb2.WriteTupleRequest.FromString,
                    response_serializer=authz__pb2.WriteTupleResponse.SerializeToString,
            ),
            'DeleteTuple': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTuple,
                    request_deserializer=authz__pb2.DeleteTupleRequest.FromString,
                    response_serializer=authz__pb2.DeleteTupleResponse.SerializeToString,
            ),
            'Read': grpc.unary_unary_rpc_method_handler(
                    servicer.Read,
                    request_deserializer=authz__pb2.ReadRequest.FromString,
                    response_serializer=authz__pb2.ReadResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=authz__pb2.HealthCheckRequest.FromString,
                    response_serializer=authz__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'opens3.authz.v1.PermissionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('opens3.authz.v1.PermissionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PermissionService(object):
    """AuthZService — ReBAC-движок авторизации для OpenS3.
    Отвечает на вопрос: "может ли <subject> выполнить <action> над <object>?"

    ─── Формат Entity ID ────────────────────────────────────────────────────────
    user:<uuid>               — пользователь (UUID из JWT sub, напр. "user:550e8400-...")
    group:<name>              — логическая группа (напр. "group:devops")
    bucket:<name>             — S3 бакет (напр. "bucket:my-photos")
    object:<bucket>/<key>     — S3 объект (напр. "object:my-photos/2024/cat.jpg")

    ─── Маппинг S3 операций → action ────────────────────────────────────────────
    read    → GetObject, HeadObject, ListObjects, HeadBucket, ListBuckets
    write   → PutObject, UploadPart, CompleteMultipartUpload
    delete  → DeleteObject
    create  → CreateBucket, CreateMultipartUpload, AbortMultipartUpload
    admin   → DeleteBucket, выдача/отзыв прав

    ─── Иерархия уровней HAS_PERMISSION ─────────────────────────────────────────
    admin > delete > create > write > read
    (каждый уровень включает все нижестоящие)
    """

    @staticmethod
    def Check(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/opens3.authz.v1.PermissionService/Check',
            authz__pb2.CheckRequest.SerializeToString,
            authz__pb2.CheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteTuple(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/opens3.authz.v1.PermissionService/WriteTuple',
            authz__pb2.WriteTupleRequest.SerializeToString,
            authz__pb2.WriteTupleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteTuple(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/opens3.authz.v1.PermissionService/DeleteTuple',
            authz__pb2.DeleteTupleRequest.SerializeToString,
            authz__pb2.DeleteTupleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Read(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/opens3.authz.v1.PermissionService/Read',
            authz__pb2.ReadRequest.SerializeToString,
            authz__pb2.ReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/opens3.authz.v1.PermissionService/HealthCheck',
            authz__pb2.HealthCheckRequest.SerializeToString,
            authz__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
