{
 "title": "New dashboard Copy",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Request (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(grpc_chat_server_requests_total[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(grpc_user_server_requests_total[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(grpc_auth_service_requests_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Chat Server Response (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by (status) (rate(grpc_chat_server_response_total[3m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User Server Response (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "sum by (status) (rate(grpc_user_server_response_total[3m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AuthService Quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \n  sum by (le) (rate(grpc_auth_service_histogram_response_time_seconds_bucket[5m]))\n)",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, \n  sum by (le) (rate(grpc_auth_service_histogram_response_time_seconds_bucket[5m]))\n)",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.50, \n  sum by (le) (rate(grpc_auth_service_histogram_response_time_seconds_bucket[5m]))\n)",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "User Server Quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 19 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, \n  sum by (le) (rate(grpc_user_server_histogram_response_time_seconds_bucket[5m]))\n)",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, \n  sum by (le) (rate(grpc_user_server_histogram_response_time_seconds_bucket[5m]))\n)",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, \n  sum by (le) (rate(grpc_user_server_histogram_response_time_seconds_bucket[5m]))\n)",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Auth Service Response (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum by (status) (rate(grpc_auth_service_response_total[3m]))\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}