{
 "title": "Opens3 — Storage",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Requests / Repsonses",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(grpc_storage_server_requests_total[$__rate_interval]))",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(rate(grpc_storage_server_response_total[$__rate_interval]))",
     "legendFormat": "Responses"
    }
   ]
  },
  {
   "title": "Disk Usage (GiB)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "storage_disk_usage_bytes / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success vs Errors",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (method) (rate(grpc_storage_server_response_total{status=\"success\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (method) (rate(grpc_storage_server_response_total{status=\"error\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read / Write",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 6, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(storage_write_bytes_total[$__rate_interval]))",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(rate(storage_read_bytes_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Прирост занятого метса",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 10 },
   "targets": [
    {
     "expr": "deriv(storage_disk_usage_bytes[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}