# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x07\x61uth_v1\x1a\x1bgoogle/protobuf/empty.proto\"/\n\x0cLoginRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"&\n\rLoginResponse\x12\x15\n\rrefresh_token\x18\x01 \x01(\t\"/\n\x16GetRefreshTokenRequest\x12\x15\n\rrefresh_token\x18\x01 \x01(\t\"0\n\x17GetRefreshTokenResponse\x12\x15\n\rrefresh_token\x18\x01 \x01(\t\".\n\x15GetAccessTokenRequest\x12\x15\n\rrefresh_token\x18\x01 \x01(\t\".\n\x16GetAccessTokenResponse\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t2\xaa\x02\n\x06\x41uthV1\x12\x36\n\x05Login\x12\x15.auth_v1.LoginRequest\x1a\x16.auth_v1.LoginResponse\x12T\n\x0fGetRefreshToken\x12\x1f.auth_v1.GetRefreshTokenRequest\x1a .auth_v1.GetRefreshTokenResponse\x12Q\n\x0eGetAccessToken\x12\x1e.auth_v1.GetAccessTokenRequest\x1a\x1f.auth_v1.GetAccessTokenResponse\x12?\n\rValidateToken\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.EmptyB@Z>github.com/alesplll/opens3-rebac/shared/pkg/go/auth/v1;auth_v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z>github.com/alesplll/opens3-rebac/shared/pkg/go/auth/v1;auth_v1'
  _globals['_LOGINREQUEST']._serialized_start=52
  _globals['_LOGINREQUEST']._serialized_end=99
  _globals['_LOGINRESPONSE']._serialized_start=101
  _globals['_LOGINRESPONSE']._serialized_end=139
  _globals['_GETREFRESHTOKENREQUEST']._serialized_start=141
  _globals['_GETREFRESHTOKENREQUEST']._serialized_end=188
  _globals['_GETREFRESHTOKENRESPONSE']._serialized_start=190
  _globals['_GETREFRESHTOKENRESPONSE']._serialized_end=238
  _globals['_GETACCESSTOKENREQUEST']._serialized_start=240
  _globals['_GETACCESSTOKENREQUEST']._serialized_end=286
  _globals['_GETACCESSTOKENRESPONSE']._serialized_start=288
  _globals['_GETACCESSTOKENRESPONSE']._serialized_end=334
  _globals['_AUTHV1']._serialized_start=337
  _globals['_AUTHV1']._serialized_end=635
# @@protoc_insertion_point(module_scope)
