// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: authz.proto

package authzv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_UNKNOWN     HealthCheckResponse_ServingStatus = 0 // Статус неизвестен (не инициализирован)
	HealthCheckResponse_SERVING     HealthCheckResponse_ServingStatus = 1 // Сервис готов принимать запросы
	HealthCheckResponse_NOT_SERVING HealthCheckResponse_ServingStatus = 2 // Сервис не готов (зависимость недоступна: Neo4j, Redis)
)

// Enum value maps for HealthCheckResponse_ServingStatus.
var (
	HealthCheckResponse_ServingStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
	}
	HealthCheckResponse_ServingStatus_value = map[string]int32{
		"UNKNOWN":     0,
		"SERVING":     1,
		"NOT_SERVING": 2,
	}
)

func (x HealthCheckResponse_ServingStatus) Enum() *HealthCheckResponse_ServingStatus {
	p := new(HealthCheckResponse_ServingStatus)
	*p = x
	return p
}

func (x HealthCheckResponse_ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_authz_proto_enumTypes[0].Descriptor()
}

func (HealthCheckResponse_ServingStatus) Type() protoreflect.EnumType {
	return &file_authz_proto_enumTypes[0]
}

func (x HealthCheckResponse_ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_ServingStatus.Descriptor instead.
func (HealthCheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_authz_proto_rawDescGZIP(), []int{10, 0}
}

type CheckRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Субъект, выполняющий действие.
	// Формат: "user:<uuid>" или "group:<name>".
	// Пример: "user:550e8400-e29b-41d4-a716-446655440000"
	Subject string `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	// Выполняемое действие. Одно из: read, write, delete, create, admin.
	// См. таблицу маппинга S3 операций в комментарии к сервису.
	Action string `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	// Объект, над которым выполняется действие.
	// Формат: "bucket:<name>" или "object:<bucket>/<key>".
	// Пример: "bucket:my-photos" или "object:my-photos/2024/cat.jpg"
	Object        string `protobuf:"bytes,3,opt,name=object,proto3" json:"object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_authz_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authz_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_authz_proto_rawDescGZIP(), []int{0}
}

func (x *CheckRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *CheckRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *CheckRequest) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

type CheckResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// true — действие разрешено, false — запрещено.
	Allowed bool `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	// Читаемое пояснение решения (для отладки, не для клиента).
	// Примеры: "owner access", "member of group:devops via HAS_PERMISSION{write}",
	//
	//	"no path in graph", "cache hit"
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_authz_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authz_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_authz_proto_rawDescGZIP(), []int{1}
}

func (x *CheckResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type WriteTupleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Subject отношения. Формат: "user:<uuid>" или "group:<name>".
	Subject string `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	// Тип ребра в графе. Допустимые значения:
	//
	//	MEMBER_OF      — user/group является членом group
	//	HAS_PERMISSION — subject имеет явные права на ресурс (нужен level)
	//	OWNER_OF       — subject является владельцем ресурса (подразумевает admin)
	//	PARENT_OF      — ресурс является родителем другого (bucket→object для наследования прав)
	Relation string `protobuf:"bytes,2,opt,name=relation,proto3" json:"relation,omitempty"`
	// Object отношения. Формат: "group:<name>", "bucket:<name>", "object:<bucket>/<key>".
	Object string `protobuf:"bytes,3,opt,name=object,proto3" json:"object,omitempty"`
	// Уровень прав. Обязателен при relation = HAS_PERMISSION.
	// Допустимые значения: "read" | "write" | "create" | "delete" | "admin"
	// Иерархия (каждый уровень включает нижестоящие): admin > delete > create > write > read
	Level         string `protobuf:"bytes,4,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteTupleRequest) Reset() {
	*x = WriteTupleRequest{}
	mi := &file_authz_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteTupleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteTupleRequest) ProtoMessage() {}

func (x *WriteTupleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authz_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteTupleRequest.ProtoReflect.Descriptor instead.
func (*WriteTupleRequest) Descriptor() ([]byte, []int) {
	return file_authz_proto_rawDescGZIP(), []int{2}
}

func (x *WriteTupleRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *WriteTupleRequest) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *WriteTupleRequest) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *WriteTupleRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

type WriteTupleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteTupleResponse) Reset() {
	*x = WriteTupleResponse{}
	mi := &file_authz_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteTupleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteTupleResponse) ProtoMessage() {}

func (x *WriteTupleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authz_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteTupleResponse.ProtoReflect.Descriptor instead.
func (*WriteTupleResponse) Descriptor() ([]byte, []int) {
	return file_authz_proto_rawDescGZIP(), []int{3}
}

func (x *WriteTupleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteTupleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Relation      string                 `protobuf:"bytes,2,opt,name=relation,proto3" json:"relation,omitempty"`
	Object        string                 `protobuf:"bytes,3,opt,name=object,proto3" json:"object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTupleRequest) Reset() {
	*x = DeleteTupleRequest{}
	mi := &file_authz_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTupleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTupleRequest) ProtoMessage() {}

func (x *DeleteTupleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authz_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTupleRequest.ProtoReflect.Descriptor instead.
func (*DeleteTupleRequest) Descriptor() ([]byte, []int) {
	return file_authz_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteTupleRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *DeleteTupleRequest) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *DeleteTupleRequest) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

type DeleteTupleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTupleResponse) Reset() {
	*x = DeleteTupleResponse{}
	mi := &file_authz_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTupleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTupleResponse) ProtoMessage() {}

func (x *DeleteTupleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authz_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTupleResponse.ProtoReflect.Descriptor instead.
func (*DeleteTupleResponse) Descriptor() ([]byte, []int) {
	return file_authz_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteTupleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ReadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Subject для получения связей. Формат: "user:<uuid>" или "group:<name>".
	Subject       string `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_authz_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authz_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_authz_proto_rawDescGZIP(), []int{6}
}

func (x *ReadRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

type ReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tuples        []*RelationTuple       `protobuf:"bytes,1,rep,name=tuples,proto3" json:"tuples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	mi := &file_authz_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authz_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_authz_proto_rawDescGZIP(), []int{7}
}

func (x *ReadResponse) GetTuples() []*RelationTuple {
	if x != nil {
		return x.Tuples
	}
	return nil
}

// RelationTuple — единица хранения прав в графе.
type RelationTuple struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Subject  string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Relation string                 `protobuf:"bytes,2,opt,name=relation,proto3" json:"relation,omitempty"`
	Object   string                 `protobuf:"bytes,3,opt,name=object,proto3" json:"object,omitempty"`
	// Заполняется только при relation = HAS_PERMISSION.
	Level         string `protobuf:"bytes,4,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelationTuple) Reset() {
	*x = RelationTuple{}
	mi := &file_authz_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationTuple) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationTuple) ProtoMessage() {}

func (x *RelationTuple) ProtoReflect() protoreflect.Message {
	mi := &file_authz_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationTuple.ProtoReflect.Descriptor instead.
func (*RelationTuple) Descriptor() ([]byte, []int) {
	return file_authz_proto_rawDescGZIP(), []int{8}
}

func (x *RelationTuple) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *RelationTuple) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *RelationTuple) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *RelationTuple) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

// HealthCheckRequest — запрос проверки состояния сервиса.
// Следует стандарту gRPC Health Checking Protocol (grpc.health.v1).
type HealthCheckRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Имя сервиса. Пустая строка — проверить весь процесс.
	Service       string `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_authz_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authz_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_authz_proto_rawDescGZIP(), []int{9}
}

func (x *HealthCheckRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Status        HealthCheckResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=opens3.authz.v1.HealthCheckResponse_ServingStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_authz_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authz_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_authz_proto_rawDescGZIP(), []int{10}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_ServingStatus {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_UNKNOWN
}

var File_authz_proto protoreflect.FileDescriptor

const file_authz_proto_rawDesc = "" +
	"\n" +
	"\vauthz.proto\x12\x0fopens3.authz.v1\"X\n" +
	"\fCheckRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x16\n" +
	"\x06object\x18\x03 \x01(\tR\x06object\"A\n" +
	"\rCheckResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"w\n" +
	"\x11WriteTupleRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x1a\n" +
	"\brelation\x18\x02 \x01(\tR\brelation\x12\x16\n" +
	"\x06object\x18\x03 \x01(\tR\x06object\x12\x14\n" +
	"\x05level\x18\x04 \x01(\tR\x05level\".\n" +
	"\x12WriteTupleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"b\n" +
	"\x12DeleteTupleRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x1a\n" +
	"\brelation\x18\x02 \x01(\tR\brelation\x12\x16\n" +
	"\x06object\x18\x03 \x01(\tR\x06object\"/\n" +
	"\x13DeleteTupleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"'\n" +
	"\vReadRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\"F\n" +
	"\fReadResponse\x126\n" +
	"\x06tuples\x18\x01 \x03(\v2\x1e.opens3.authz.v1.RelationTupleR\x06tuples\"s\n" +
	"\rRelationTuple\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x1a\n" +
	"\brelation\x18\x02 \x01(\tR\brelation\x12\x16\n" +
	"\x06object\x18\x03 \x01(\tR\x06object\x12\x14\n" +
	"\x05level\x18\x04 \x01(\tR\x05level\".\n" +
	"\x12HealthCheckRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\"\x9d\x01\n" +
	"\x13HealthCheckResponse\x12J\n" +
	"\x06status\x18\x01 \x01(\x0e22.opens3.authz.v1.HealthCheckResponse.ServingStatusR\x06status\":\n" +
	"\rServingStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x022\xab\x03\n" +
	"\x11PermissionService\x12F\n" +
	"\x05Check\x12\x1d.opens3.authz.v1.CheckRequest\x1a\x1e.opens3.authz.v1.CheckResponse\x12U\n" +
	"\n" +
	"WriteTuple\x12\".opens3.authz.v1.WriteTupleRequest\x1a#.opens3.authz.v1.WriteTupleResponse\x12X\n" +
	"\vDeleteTuple\x12#.opens3.authz.v1.DeleteTupleRequest\x1a$.opens3.authz.v1.DeleteTupleResponse\x12C\n" +
	"\x04Read\x12\x1c.opens3.authz.v1.ReadRequest\x1a\x1d.opens3.authz.v1.ReadResponse\x12X\n" +
	"\vHealthCheck\x12#.opens3.authz.v1.HealthCheckRequest\x1a$.opens3.authz.v1.HealthCheckResponseBAZ?github.com/alesplll/opens3-rebac/shared/pkg/go/authz/v1;authzv1b\x06proto3"

var (
	file_authz_proto_rawDescOnce sync.Once
	file_authz_proto_rawDescData []byte
)

func file_authz_proto_rawDescGZIP() []byte {
	file_authz_proto_rawDescOnce.Do(func() {
		file_authz_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_authz_proto_rawDesc), len(file_authz_proto_rawDesc)))
	})
	return file_authz_proto_rawDescData
}

var file_authz_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_authz_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_authz_proto_goTypes = []any{
	(HealthCheckResponse_ServingStatus)(0), // 0: opens3.authz.v1.HealthCheckResponse.ServingStatus
	(*CheckRequest)(nil),                   // 1: opens3.authz.v1.CheckRequest
	(*CheckResponse)(nil),                  // 2: opens3.authz.v1.CheckResponse
	(*WriteTupleRequest)(nil),              // 3: opens3.authz.v1.WriteTupleRequest
	(*WriteTupleResponse)(nil),             // 4: opens3.authz.v1.WriteTupleResponse
	(*DeleteTupleRequest)(nil),             // 5: opens3.authz.v1.DeleteTupleRequest
	(*DeleteTupleResponse)(nil),            // 6: opens3.authz.v1.DeleteTupleResponse
	(*ReadRequest)(nil),                    // 7: opens3.authz.v1.ReadRequest
	(*ReadResponse)(nil),                   // 8: opens3.authz.v1.ReadResponse
	(*RelationTuple)(nil),                  // 9: opens3.authz.v1.RelationTuple
	(*HealthCheckRequest)(nil),             // 10: opens3.authz.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),            // 11: opens3.authz.v1.HealthCheckResponse
}
var file_authz_proto_depIdxs = []int32{
	9,  // 0: opens3.authz.v1.ReadResponse.tuples:type_name -> opens3.authz.v1.RelationTuple
	0,  // 1: opens3.authz.v1.HealthCheckResponse.status:type_name -> opens3.authz.v1.HealthCheckResponse.ServingStatus
	1,  // 2: opens3.authz.v1.PermissionService.Check:input_type -> opens3.authz.v1.CheckRequest
	3,  // 3: opens3.authz.v1.PermissionService.WriteTuple:input_type -> opens3.authz.v1.WriteTupleRequest
	5,  // 4: opens3.authz.v1.PermissionService.DeleteTuple:input_type -> opens3.authz.v1.DeleteTupleRequest
	7,  // 5: opens3.authz.v1.PermissionService.Read:input_type -> opens3.authz.v1.ReadRequest
	10, // 6: opens3.authz.v1.PermissionService.HealthCheck:input_type -> opens3.authz.v1.HealthCheckRequest
	2,  // 7: opens3.authz.v1.PermissionService.Check:output_type -> opens3.authz.v1.CheckResponse
	4,  // 8: opens3.authz.v1.PermissionService.WriteTuple:output_type -> opens3.authz.v1.WriteTupleResponse
	6,  // 9: opens3.authz.v1.PermissionService.DeleteTuple:output_type -> opens3.authz.v1.DeleteTupleResponse
	8,  // 10: opens3.authz.v1.PermissionService.Read:output_type -> opens3.authz.v1.ReadResponse
	11, // 11: opens3.authz.v1.PermissionService.HealthCheck:output_type -> opens3.authz.v1.HealthCheckResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_authz_proto_init() }
func file_authz_proto_init() {
	if File_authz_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authz_proto_rawDesc), len(file_authz_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_authz_proto_goTypes,
		DependencyIndexes: file_authz_proto_depIdxs,
		EnumInfos:         file_authz_proto_enumTypes,
		MessageInfos:      file_authz_proto_msgTypes,
	}.Build()
	File_authz_proto = out.File
	file_authz_proto_goTypes = nil
	file_authz_proto_depIdxs = nil
}
