// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: authz.proto

package authzv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PermissionService_Check_FullMethodName       = "/opens3.authz.v1.PermissionService/Check"
	PermissionService_WriteTuple_FullMethodName  = "/opens3.authz.v1.PermissionService/WriteTuple"
	PermissionService_DeleteTuple_FullMethodName = "/opens3.authz.v1.PermissionService/DeleteTuple"
	PermissionService_Read_FullMethodName        = "/opens3.authz.v1.PermissionService/Read"
	PermissionService_HealthCheck_FullMethodName = "/opens3.authz.v1.PermissionService/HealthCheck"
)

// PermissionServiceClient is the client API for PermissionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AuthZService — ReBAC-движок авторизации для OpenS3.
// Отвечает на вопрос: "может ли <subject> выполнить <action> над <object>?"
//
// ─── Формат Entity ID ────────────────────────────────────────────────────────
//
//	user:<uuid>               — пользователь (UUID из JWT sub, напр. "user:550e8400-...")
//	group:<name>              — логическая группа (напр. "group:devops")
//	bucket:<name>             — S3 бакет (напр. "bucket:my-photos")
//	object:<bucket>/<key>     — S3 объект (напр. "object:my-photos/2024/cat.jpg")
//
// ─── Маппинг S3 операций → action ────────────────────────────────────────────
//
//	read    → GetObject, HeadObject, ListObjects, HeadBucket, ListBuckets
//	write   → PutObject, UploadPart, CompleteMultipartUpload
//	delete  → DeleteObject
//	create  → CreateBucket, CreateMultipartUpload, AbortMultipartUpload
//	admin   → DeleteBucket, выдача/отзыв прав
//
// ─── Иерархия уровней HAS_PERMISSION ─────────────────────────────────────────
//
//	admin > delete > create > write > read
//	(каждый уровень включает все нижестоящие)
type PermissionServiceClient interface {
	// Check проверяет, разрешено ли действие.
	// Вызывается Gateway перед каждой S3-операцией.
	// Сначала проверяет кэш Redis (TTL ~30 с), при промахе — обходит граф Neo4j.
	// Публикует аудит-событие (ACCESS_GRANTED / ACCESS_DENIED) в топик auth-audit.
	Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error)
	// WriteTuple создаёт ребро в графе прав.
	// Использование:
	//
	//	— назначить владельца бакета при CreateBucket:
	//	    subject=user:<id>, relation=OWNER_OF, object=bucket:<name>
	//	— связать объект с бакетом после PutObject:
	//	    subject=bucket:<name>, relation=PARENT_OF, object=object:<bucket>/<key>
	//	— выдать права пользователю/группе:
	//	    subject=user:<id>, relation=HAS_PERMISSION, object=bucket:<name>, level=read
	//	— добавить пользователя в группу:
	//	    subject=user:<id>, relation=MEMBER_OF, object=group:<name>
	//
	// После записи публикует событие tuple_written в топик auth-changes (инвалидация кэша).
	WriteTuple(ctx context.Context, in *WriteTupleRequest, opts ...grpc.CallOption) (*WriteTupleResponse, error)
	// DeleteTuple удаляет ребро из графа прав.
	// Используется для отзыва прав или исключения из группы.
	// После удаления публикует событие tuple_removed в топик auth-changes (инвалидация кэша).
	DeleteTuple(ctx context.Context, in *DeleteTupleRequest, opts ...grpc.CallOption) (*DeleteTupleResponse, error)
	// Read возвращает все прямые (не транзитивные) исходящие связи subject'а.
	// Полезно для ответа на вопрос "куда у пользователя есть доступ" без знания конкретных ресурсов.
	// Примеры результатов:
	//
	//	subject=user:alice, relation=MEMBER_OF, object=group:devops
	//	subject=user:alice, relation=OWNER_OF,  object=bucket:my-photos
	//	subject=user:alice, relation=HAS_PERMISSION, object=bucket:shared, level=read
	//
	// Используется в админском UI, при отладке, при отображении "мои права".
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
	// HealthCheck — стандартный gRPC Health Checking Protocol.
	// Используется Kubernetes liveness/readiness probe и Gateway /ready.
	// service="" проверяет весь процесс; service="PermissionService" — конкретный сервис.
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type permissionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPermissionServiceClient(cc grpc.ClientConnInterface) PermissionServiceClient {
	return &permissionServiceClient{cc}
}

func (c *permissionServiceClient) Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckResponse)
	err := c.cc.Invoke(ctx, PermissionService_Check_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionServiceClient) WriteTuple(ctx context.Context, in *WriteTupleRequest, opts ...grpc.CallOption) (*WriteTupleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteTupleResponse)
	err := c.cc.Invoke(ctx, PermissionService_WriteTuple_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionServiceClient) DeleteTuple(ctx context.Context, in *DeleteTupleRequest, opts ...grpc.CallOption) (*DeleteTupleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTupleResponse)
	err := c.cc.Invoke(ctx, PermissionService_DeleteTuple_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionServiceClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadResponse)
	err := c.cc.Invoke(ctx, PermissionService_Read_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, PermissionService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PermissionServiceServer is the server API for PermissionService service.
// All implementations must embed UnimplementedPermissionServiceServer
// for forward compatibility.
//
// AuthZService — ReBAC-движок авторизации для OpenS3.
// Отвечает на вопрос: "может ли <subject> выполнить <action> над <object>?"
//
// ─── Формат Entity ID ────────────────────────────────────────────────────────
//
//	user:<uuid>               — пользователь (UUID из JWT sub, напр. "user:550e8400-...")
//	group:<name>              — логическая группа (напр. "group:devops")
//	bucket:<name>             — S3 бакет (напр. "bucket:my-photos")
//	object:<bucket>/<key>     — S3 объект (напр. "object:my-photos/2024/cat.jpg")
//
// ─── Маппинг S3 операций → action ────────────────────────────────────────────
//
//	read    → GetObject, HeadObject, ListObjects, HeadBucket, ListBuckets
//	write   → PutObject, UploadPart, CompleteMultipartUpload
//	delete  → DeleteObject
//	create  → CreateBucket, CreateMultipartUpload, AbortMultipartUpload
//	admin   → DeleteBucket, выдача/отзыв прав
//
// ─── Иерархия уровней HAS_PERMISSION ─────────────────────────────────────────
//
//	admin > delete > create > write > read
//	(каждый уровень включает все нижестоящие)
type PermissionServiceServer interface {
	// Check проверяет, разрешено ли действие.
	// Вызывается Gateway перед каждой S3-операцией.
	// Сначала проверяет кэш Redis (TTL ~30 с), при промахе — обходит граф Neo4j.
	// Публикует аудит-событие (ACCESS_GRANTED / ACCESS_DENIED) в топик auth-audit.
	Check(context.Context, *CheckRequest) (*CheckResponse, error)
	// WriteTuple создаёт ребро в графе прав.
	// Использование:
	//
	//	— назначить владельца бакета при CreateBucket:
	//	    subject=user:<id>, relation=OWNER_OF, object=bucket:<name>
	//	— связать объект с бакетом после PutObject:
	//	    subject=bucket:<name>, relation=PARENT_OF, object=object:<bucket>/<key>
	//	— выдать права пользователю/группе:
	//	    subject=user:<id>, relation=HAS_PERMISSION, object=bucket:<name>, level=read
	//	— добавить пользователя в группу:
	//	    subject=user:<id>, relation=MEMBER_OF, object=group:<name>
	//
	// После записи публикует событие tuple_written в топик auth-changes (инвалидация кэша).
	WriteTuple(context.Context, *WriteTupleRequest) (*WriteTupleResponse, error)
	// DeleteTuple удаляет ребро из графа прав.
	// Используется для отзыва прав или исключения из группы.
	// После удаления публикует событие tuple_removed в топик auth-changes (инвалидация кэша).
	DeleteTuple(context.Context, *DeleteTupleRequest) (*DeleteTupleResponse, error)
	// Read возвращает все прямые (не транзитивные) исходящие связи subject'а.
	// Полезно для ответа на вопрос "куда у пользователя есть доступ" без знания конкретных ресурсов.
	// Примеры результатов:
	//
	//	subject=user:alice, relation=MEMBER_OF, object=group:devops
	//	subject=user:alice, relation=OWNER_OF,  object=bucket:my-photos
	//	subject=user:alice, relation=HAS_PERMISSION, object=bucket:shared, level=read
	//
	// Используется в админском UI, при отладке, при отображении "мои права".
	Read(context.Context, *ReadRequest) (*ReadResponse, error)
	// HealthCheck — стандартный gRPC Health Checking Protocol.
	// Используется Kubernetes liveness/readiness probe и Gateway /ready.
	// service="" проверяет весь процесс; service="PermissionService" — конкретный сервис.
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedPermissionServiceServer()
}

// UnimplementedPermissionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPermissionServiceServer struct{}

func (UnimplementedPermissionServiceServer) Check(context.Context, *CheckRequest) (*CheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedPermissionServiceServer) WriteTuple(context.Context, *WriteTupleRequest) (*WriteTupleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteTuple not implemented")
}
func (UnimplementedPermissionServiceServer) DeleteTuple(context.Context, *DeleteTupleRequest) (*DeleteTupleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTuple not implemented")
}
func (UnimplementedPermissionServiceServer) Read(context.Context, *ReadRequest) (*ReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedPermissionServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedPermissionServiceServer) mustEmbedUnimplementedPermissionServiceServer() {}
func (UnimplementedPermissionServiceServer) testEmbeddedByValue()                           {}

// UnsafePermissionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PermissionServiceServer will
// result in compilation errors.
type UnsafePermissionServiceServer interface {
	mustEmbedUnimplementedPermissionServiceServer()
}

func RegisterPermissionServiceServer(s grpc.ServiceRegistrar, srv PermissionServiceServer) {
	// If the following call pancis, it indicates UnimplementedPermissionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PermissionService_ServiceDesc, srv)
}

func _PermissionService_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServiceServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionService_Check_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServiceServer).Check(ctx, req.(*CheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionService_WriteTuple_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteTupleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServiceServer).WriteTuple(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionService_WriteTuple_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServiceServer).WriteTuple(ctx, req.(*WriteTupleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionService_DeleteTuple_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTupleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServiceServer).DeleteTuple(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionService_DeleteTuple_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServiceServer).DeleteTuple(ctx, req.(*DeleteTupleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionService_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServiceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionService_Read_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServiceServer).Read(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PermissionService_ServiceDesc is the grpc.ServiceDesc for PermissionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PermissionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "opens3.authz.v1.PermissionService",
	HandlerType: (*PermissionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _PermissionService_Check_Handler,
		},
		{
			MethodName: "WriteTuple",
			Handler:    _PermissionService_WriteTuple_Handler,
		},
		{
			MethodName: "DeleteTuple",
			Handler:    _PermissionService_DeleteTuple_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _PermissionService_Read_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _PermissionService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "authz.proto",
}
