// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

//go:generate minimock -i github.com/alesplll/opens3-rebac/services/metadata/internal/repository.BucketRepository -o bucket_repository_minimock.go -n BucketRepositoryMock -p mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/alesplll/opens3-rebac/services/metadata/internal/model"
	"github.com/gojuno/minimock/v3"
)

// BucketRepositoryMock implements mm_repository.BucketRepository
type BucketRepositoryMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcCountObjects          func(ctx context.Context, bucketID string) (i1 int64, err error)
	funcCountObjectsOrigin    string
	inspectFuncCountObjects   func(ctx context.Context, bucketID string)
	afterCountObjectsCounter  uint64
	beforeCountObjectsCounter uint64
	CountObjectsMock          mBucketRepositoryMockCountObjects

	funcCreate          func(ctx context.Context, name string, ownerID string) (bp1 *model.Bucket, err error)
	funcCreateOrigin    string
	inspectFuncCreate   func(ctx context.Context, name string, ownerID string)
	afterCreateCounter  uint64
	beforeCreateCounter uint64
	CreateMock          mBucketRepositoryMockCreate

	funcDelete          func(ctx context.Context, bucketID string) (err error)
	funcDeleteOrigin    string
	inspectFuncDelete   func(ctx context.Context, bucketID string)
	afterDeleteCounter  uint64
	beforeDeleteCounter uint64
	DeleteMock          mBucketRepositoryMockDelete

	funcGet          func(ctx context.Context, name string) (bp1 *model.Bucket, err error)
	funcGetOrigin    string
	inspectFuncGet   func(ctx context.Context, name string)
	afterGetCounter  uint64
	beforeGetCounter uint64
	GetMock          mBucketRepositoryMockGet

	funcHead          func(ctx context.Context, name string) (b1 bool, s1 string, s2 string, err error)
	funcHeadOrigin    string
	inspectFuncHead   func(ctx context.Context, name string)
	afterHeadCounter  uint64
	beforeHeadCounter uint64
	HeadMock          mBucketRepositoryMockHead

	funcList          func(ctx context.Context, ownerID string) (bpa1 []*model.Bucket, err error)
	funcListOrigin    string
	inspectFuncList   func(ctx context.Context, ownerID string)
	afterListCounter  uint64
	beforeListCounter uint64
	ListMock          mBucketRepositoryMockList
}

// NewBucketRepositoryMock returns a mock for mm_repository.BucketRepository
func NewBucketRepositoryMock(t minimock.Tester) *BucketRepositoryMock {
	m := &BucketRepositoryMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CountObjectsMock = mBucketRepositoryMockCountObjects{mock: m}
	m.CountObjectsMock.callArgs = []*BucketRepositoryMockCountObjectsParams{}

	m.CreateMock = mBucketRepositoryMockCreate{mock: m}
	m.CreateMock.callArgs = []*BucketRepositoryMockCreateParams{}

	m.DeleteMock = mBucketRepositoryMockDelete{mock: m}
	m.DeleteMock.callArgs = []*BucketRepositoryMockDeleteParams{}

	m.GetMock = mBucketRepositoryMockGet{mock: m}
	m.GetMock.callArgs = []*BucketRepositoryMockGetParams{}

	m.HeadMock = mBucketRepositoryMockHead{mock: m}
	m.HeadMock.callArgs = []*BucketRepositoryMockHeadParams{}

	m.ListMock = mBucketRepositoryMockList{mock: m}
	m.ListMock.callArgs = []*BucketRepositoryMockListParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mBucketRepositoryMockCountObjects struct {
	optional           bool
	mock               *BucketRepositoryMock
	defaultExpectation *BucketRepositoryMockCountObjectsExpectation
	expectations       []*BucketRepositoryMockCountObjectsExpectation

	callArgs []*BucketRepositoryMockCountObjectsParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// BucketRepositoryMockCountObjectsExpectation specifies expectation struct of the BucketRepository.CountObjects
type BucketRepositoryMockCountObjectsExpectation struct {
	mock               *BucketRepositoryMock
	params             *BucketRepositoryMockCountObjectsParams
	paramPtrs          *BucketRepositoryMockCountObjectsParamPtrs
	expectationOrigins BucketRepositoryMockCountObjectsExpectationOrigins
	results            *BucketRepositoryMockCountObjectsResults
	returnOrigin       string
	Counter            uint64
}

// BucketRepositoryMockCountObjectsParams contains parameters of the BucketRepository.CountObjects
type BucketRepositoryMockCountObjectsParams struct {
	ctx      context.Context
	bucketID string
}

// BucketRepositoryMockCountObjectsParamPtrs contains pointers to parameters of the BucketRepository.CountObjects
type BucketRepositoryMockCountObjectsParamPtrs struct {
	ctx      *context.Context
	bucketID *string
}

// BucketRepositoryMockCountObjectsResults contains results of the BucketRepository.CountObjects
type BucketRepositoryMockCountObjectsResults struct {
	i1  int64
	err error
}

// BucketRepositoryMockCountObjectsOrigins contains origins of expectations of the BucketRepository.CountObjects
type BucketRepositoryMockCountObjectsExpectationOrigins struct {
	origin         string
	originCtx      string
	originBucketID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCountObjects *mBucketRepositoryMockCountObjects) Optional() *mBucketRepositoryMockCountObjects {
	mmCountObjects.optional = true
	return mmCountObjects
}

// Expect sets up expected params for BucketRepository.CountObjects
func (mmCountObjects *mBucketRepositoryMockCountObjects) Expect(ctx context.Context, bucketID string) *mBucketRepositoryMockCountObjects {
	if mmCountObjects.mock.funcCountObjects != nil {
		mmCountObjects.mock.t.Fatalf("BucketRepositoryMock.CountObjects mock is already set by Set")
	}

	if mmCountObjects.defaultExpectation == nil {
		mmCountObjects.defaultExpectation = &BucketRepositoryMockCountObjectsExpectation{}
	}

	if mmCountObjects.defaultExpectation.paramPtrs != nil {
		mmCountObjects.mock.t.Fatalf("BucketRepositoryMock.CountObjects mock is already set by ExpectParams functions")
	}

	mmCountObjects.defaultExpectation.params = &BucketRepositoryMockCountObjectsParams{ctx, bucketID}
	mmCountObjects.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCountObjects.expectations {
		if minimock.Equal(e.params, mmCountObjects.defaultExpectation.params) {
			mmCountObjects.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCountObjects.defaultExpectation.params)
		}
	}

	return mmCountObjects
}

// ExpectCtxParam1 sets up expected param ctx for BucketRepository.CountObjects
func (mmCountObjects *mBucketRepositoryMockCountObjects) ExpectCtxParam1(ctx context.Context) *mBucketRepositoryMockCountObjects {
	if mmCountObjects.mock.funcCountObjects != nil {
		mmCountObjects.mock.t.Fatalf("BucketRepositoryMock.CountObjects mock is already set by Set")
	}

	if mmCountObjects.defaultExpectation == nil {
		mmCountObjects.defaultExpectation = &BucketRepositoryMockCountObjectsExpectation{}
	}

	if mmCountObjects.defaultExpectation.params != nil {
		mmCountObjects.mock.t.Fatalf("BucketRepositoryMock.CountObjects mock is already set by Expect")
	}

	if mmCountObjects.defaultExpectation.paramPtrs == nil {
		mmCountObjects.defaultExpectation.paramPtrs = &BucketRepositoryMockCountObjectsParamPtrs{}
	}
	mmCountObjects.defaultExpectation.paramPtrs.ctx = &ctx
	mmCountObjects.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmCountObjects
}

// ExpectBucketIDParam2 sets up expected param bucketID for BucketRepository.CountObjects
func (mmCountObjects *mBucketRepositoryMockCountObjects) ExpectBucketIDParam2(bucketID string) *mBucketRepositoryMockCountObjects {
	if mmCountObjects.mock.funcCountObjects != nil {
		mmCountObjects.mock.t.Fatalf("BucketRepositoryMock.CountObjects mock is already set by Set")
	}

	if mmCountObjects.defaultExpectation == nil {
		mmCountObjects.defaultExpectation = &BucketRepositoryMockCountObjectsExpectation{}
	}

	if mmCountObjects.defaultExpectation.params != nil {
		mmCountObjects.mock.t.Fatalf("BucketRepositoryMock.CountObjects mock is already set by Expect")
	}

	if mmCountObjects.defaultExpectation.paramPtrs == nil {
		mmCountObjects.defaultExpectation.paramPtrs = &BucketRepositoryMockCountObjectsParamPtrs{}
	}
	mmCountObjects.defaultExpectation.paramPtrs.bucketID = &bucketID
	mmCountObjects.defaultExpectation.expectationOrigins.originBucketID = minimock.CallerInfo(1)

	return mmCountObjects
}

// Inspect accepts an inspector function that has same arguments as the BucketRepository.CountObjects
func (mmCountObjects *mBucketRepositoryMockCountObjects) Inspect(f func(ctx context.Context, bucketID string)) *mBucketRepositoryMockCountObjects {
	if mmCountObjects.mock.inspectFuncCountObjects != nil {
		mmCountObjects.mock.t.Fatalf("Inspect function is already set for BucketRepositoryMock.CountObjects")
	}

	mmCountObjects.mock.inspectFuncCountObjects = f

	return mmCountObjects
}

// Return sets up results that will be returned by BucketRepository.CountObjects
func (mmCountObjects *mBucketRepositoryMockCountObjects) Return(i1 int64, err error) *BucketRepositoryMock {
	if mmCountObjects.mock.funcCountObjects != nil {
		mmCountObjects.mock.t.Fatalf("BucketRepositoryMock.CountObjects mock is already set by Set")
	}

	if mmCountObjects.defaultExpectation == nil {
		mmCountObjects.defaultExpectation = &BucketRepositoryMockCountObjectsExpectation{mock: mmCountObjects.mock}
	}
	mmCountObjects.defaultExpectation.results = &BucketRepositoryMockCountObjectsResults{i1, err}
	mmCountObjects.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCountObjects.mock
}

// Set uses given function f to mock the BucketRepository.CountObjects method
func (mmCountObjects *mBucketRepositoryMockCountObjects) Set(f func(ctx context.Context, bucketID string) (i1 int64, err error)) *BucketRepositoryMock {
	if mmCountObjects.defaultExpectation != nil {
		mmCountObjects.mock.t.Fatalf("Default expectation is already set for the BucketRepository.CountObjects method")
	}

	if len(mmCountObjects.expectations) > 0 {
		mmCountObjects.mock.t.Fatalf("Some expectations are already set for the BucketRepository.CountObjects method")
	}

	mmCountObjects.mock.funcCountObjects = f
	mmCountObjects.mock.funcCountObjectsOrigin = minimock.CallerInfo(1)
	return mmCountObjects.mock
}

// When sets expectation for the BucketRepository.CountObjects which will trigger the result defined by the following
// Then helper
func (mmCountObjects *mBucketRepositoryMockCountObjects) When(ctx context.Context, bucketID string) *BucketRepositoryMockCountObjectsExpectation {
	if mmCountObjects.mock.funcCountObjects != nil {
		mmCountObjects.mock.t.Fatalf("BucketRepositoryMock.CountObjects mock is already set by Set")
	}

	expectation := &BucketRepositoryMockCountObjectsExpectation{
		mock:               mmCountObjects.mock,
		params:             &BucketRepositoryMockCountObjectsParams{ctx, bucketID},
		expectationOrigins: BucketRepositoryMockCountObjectsExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCountObjects.expectations = append(mmCountObjects.expectations, expectation)
	return expectation
}

// Then sets up BucketRepository.CountObjects return parameters for the expectation previously defined by the When method
func (e *BucketRepositoryMockCountObjectsExpectation) Then(i1 int64, err error) *BucketRepositoryMock {
	e.results = &BucketRepositoryMockCountObjectsResults{i1, err}
	return e.mock
}

// Times sets number of times BucketRepository.CountObjects should be invoked
func (mmCountObjects *mBucketRepositoryMockCountObjects) Times(n uint64) *mBucketRepositoryMockCountObjects {
	if n == 0 {
		mmCountObjects.mock.t.Fatalf("Times of BucketRepositoryMock.CountObjects mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCountObjects.expectedInvocations, n)
	mmCountObjects.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCountObjects
}

func (mmCountObjects *mBucketRepositoryMockCountObjects) invocationsDone() bool {
	if len(mmCountObjects.expectations) == 0 && mmCountObjects.defaultExpectation == nil && mmCountObjects.mock.funcCountObjects == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCountObjects.mock.afterCountObjectsCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCountObjects.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// CountObjects implements mm_repository.BucketRepository
func (mmCountObjects *BucketRepositoryMock) CountObjects(ctx context.Context, bucketID string) (i1 int64, err error) {
	mm_atomic.AddUint64(&mmCountObjects.beforeCountObjectsCounter, 1)
	defer mm_atomic.AddUint64(&mmCountObjects.afterCountObjectsCounter, 1)

	mmCountObjects.t.Helper()

	if mmCountObjects.inspectFuncCountObjects != nil {
		mmCountObjects.inspectFuncCountObjects(ctx, bucketID)
	}

	mm_params := BucketRepositoryMockCountObjectsParams{ctx, bucketID}

	// Record call args
	mmCountObjects.CountObjectsMock.mutex.Lock()
	mmCountObjects.CountObjectsMock.callArgs = append(mmCountObjects.CountObjectsMock.callArgs, &mm_params)
	mmCountObjects.CountObjectsMock.mutex.Unlock()

	for _, e := range mmCountObjects.CountObjectsMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.i1, e.results.err
		}
	}

	if mmCountObjects.CountObjectsMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCountObjects.CountObjectsMock.defaultExpectation.Counter, 1)
		mm_want := mmCountObjects.CountObjectsMock.defaultExpectation.params
		mm_want_ptrs := mmCountObjects.CountObjectsMock.defaultExpectation.paramPtrs

		mm_got := BucketRepositoryMockCountObjectsParams{ctx, bucketID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmCountObjects.t.Errorf("BucketRepositoryMock.CountObjects got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCountObjects.CountObjectsMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.bucketID != nil && !minimock.Equal(*mm_want_ptrs.bucketID, mm_got.bucketID) {
				mmCountObjects.t.Errorf("BucketRepositoryMock.CountObjects got unexpected parameter bucketID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCountObjects.CountObjectsMock.defaultExpectation.expectationOrigins.originBucketID, *mm_want_ptrs.bucketID, mm_got.bucketID, minimock.Diff(*mm_want_ptrs.bucketID, mm_got.bucketID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCountObjects.t.Errorf("BucketRepositoryMock.CountObjects got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCountObjects.CountObjectsMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCountObjects.CountObjectsMock.defaultExpectation.results
		if mm_results == nil {
			mmCountObjects.t.Fatal("No results are set for the BucketRepositoryMock.CountObjects")
		}
		return (*mm_results).i1, (*mm_results).err
	}
	if mmCountObjects.funcCountObjects != nil {
		return mmCountObjects.funcCountObjects(ctx, bucketID)
	}
	mmCountObjects.t.Fatalf("Unexpected call to BucketRepositoryMock.CountObjects. %v %v", ctx, bucketID)
	return
}

// CountObjectsAfterCounter returns a count of finished BucketRepositoryMock.CountObjects invocations
func (mmCountObjects *BucketRepositoryMock) CountObjectsAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCountObjects.afterCountObjectsCounter)
}

// CountObjectsBeforeCounter returns a count of BucketRepositoryMock.CountObjects invocations
func (mmCountObjects *BucketRepositoryMock) CountObjectsBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCountObjects.beforeCountObjectsCounter)
}

// Calls returns a list of arguments used in each call to BucketRepositoryMock.CountObjects.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCountObjects *mBucketRepositoryMockCountObjects) Calls() []*BucketRepositoryMockCountObjectsParams {
	mmCountObjects.mutex.RLock()

	argCopy := make([]*BucketRepositoryMockCountObjectsParams, len(mmCountObjects.callArgs))
	copy(argCopy, mmCountObjects.callArgs)

	mmCountObjects.mutex.RUnlock()

	return argCopy
}

// MinimockCountObjectsDone returns true if the count of the CountObjects invocations corresponds
// the number of defined expectations
func (m *BucketRepositoryMock) MinimockCountObjectsDone() bool {
	if m.CountObjectsMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CountObjectsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CountObjectsMock.invocationsDone()
}

// MinimockCountObjectsInspect logs each unmet expectation
func (m *BucketRepositoryMock) MinimockCountObjectsInspect() {
	for _, e := range m.CountObjectsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to BucketRepositoryMock.CountObjects at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCountObjectsCounter := mm_atomic.LoadUint64(&m.afterCountObjectsCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CountObjectsMock.defaultExpectation != nil && afterCountObjectsCounter < 1 {
		if m.CountObjectsMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to BucketRepositoryMock.CountObjects at\n%s", m.CountObjectsMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to BucketRepositoryMock.CountObjects at\n%s with params: %#v", m.CountObjectsMock.defaultExpectation.expectationOrigins.origin, *m.CountObjectsMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCountObjects != nil && afterCountObjectsCounter < 1 {
		m.t.Errorf("Expected call to BucketRepositoryMock.CountObjects at\n%s", m.funcCountObjectsOrigin)
	}

	if !m.CountObjectsMock.invocationsDone() && afterCountObjectsCounter > 0 {
		m.t.Errorf("Expected %d calls to BucketRepositoryMock.CountObjects at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CountObjectsMock.expectedInvocations), m.CountObjectsMock.expectedInvocationsOrigin, afterCountObjectsCounter)
	}
}

type mBucketRepositoryMockCreate struct {
	optional           bool
	mock               *BucketRepositoryMock
	defaultExpectation *BucketRepositoryMockCreateExpectation
	expectations       []*BucketRepositoryMockCreateExpectation

	callArgs []*BucketRepositoryMockCreateParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// BucketRepositoryMockCreateExpectation specifies expectation struct of the BucketRepository.Create
type BucketRepositoryMockCreateExpectation struct {
	mock               *BucketRepositoryMock
	params             *BucketRepositoryMockCreateParams
	paramPtrs          *BucketRepositoryMockCreateParamPtrs
	expectationOrigins BucketRepositoryMockCreateExpectationOrigins
	results            *BucketRepositoryMockCreateResults
	returnOrigin       string
	Counter            uint64
}

// BucketRepositoryMockCreateParams contains parameters of the BucketRepository.Create
type BucketRepositoryMockCreateParams struct {
	ctx     context.Context
	name    string
	ownerID string
}

// BucketRepositoryMockCreateParamPtrs contains pointers to parameters of the BucketRepository.Create
type BucketRepositoryMockCreateParamPtrs struct {
	ctx     *context.Context
	name    *string
	ownerID *string
}

// BucketRepositoryMockCreateResults contains results of the BucketRepository.Create
type BucketRepositoryMockCreateResults struct {
	bp1 *model.Bucket
	err error
}

// BucketRepositoryMockCreateOrigins contains origins of expectations of the BucketRepository.Create
type BucketRepositoryMockCreateExpectationOrigins struct {
	origin        string
	originCtx     string
	originName    string
	originOwnerID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCreate *mBucketRepositoryMockCreate) Optional() *mBucketRepositoryMockCreate {
	mmCreate.optional = true
	return mmCreate
}

// Expect sets up expected params for BucketRepository.Create
func (mmCreate *mBucketRepositoryMockCreate) Expect(ctx context.Context, name string, ownerID string) *mBucketRepositoryMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("BucketRepositoryMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &BucketRepositoryMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.paramPtrs != nil {
		mmCreate.mock.t.Fatalf("BucketRepositoryMock.Create mock is already set by ExpectParams functions")
	}

	mmCreate.defaultExpectation.params = &BucketRepositoryMockCreateParams{ctx, name, ownerID}
	mmCreate.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCreate.expectations {
		if minimock.Equal(e.params, mmCreate.defaultExpectation.params) {
			mmCreate.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreate.defaultExpectation.params)
		}
	}

	return mmCreate
}

// ExpectCtxParam1 sets up expected param ctx for BucketRepository.Create
func (mmCreate *mBucketRepositoryMockCreate) ExpectCtxParam1(ctx context.Context) *mBucketRepositoryMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("BucketRepositoryMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &BucketRepositoryMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("BucketRepositoryMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &BucketRepositoryMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.ctx = &ctx
	mmCreate.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmCreate
}

// ExpectNameParam2 sets up expected param name for BucketRepository.Create
func (mmCreate *mBucketRepositoryMockCreate) ExpectNameParam2(name string) *mBucketRepositoryMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("BucketRepositoryMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &BucketRepositoryMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("BucketRepositoryMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &BucketRepositoryMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.name = &name
	mmCreate.defaultExpectation.expectationOrigins.originName = minimock.CallerInfo(1)

	return mmCreate
}

// ExpectOwnerIDParam3 sets up expected param ownerID for BucketRepository.Create
func (mmCreate *mBucketRepositoryMockCreate) ExpectOwnerIDParam3(ownerID string) *mBucketRepositoryMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("BucketRepositoryMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &BucketRepositoryMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("BucketRepositoryMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &BucketRepositoryMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.ownerID = &ownerID
	mmCreate.defaultExpectation.expectationOrigins.originOwnerID = minimock.CallerInfo(1)

	return mmCreate
}

// Inspect accepts an inspector function that has same arguments as the BucketRepository.Create
func (mmCreate *mBucketRepositoryMockCreate) Inspect(f func(ctx context.Context, name string, ownerID string)) *mBucketRepositoryMockCreate {
	if mmCreate.mock.inspectFuncCreate != nil {
		mmCreate.mock.t.Fatalf("Inspect function is already set for BucketRepositoryMock.Create")
	}

	mmCreate.mock.inspectFuncCreate = f

	return mmCreate
}

// Return sets up results that will be returned by BucketRepository.Create
func (mmCreate *mBucketRepositoryMockCreate) Return(bp1 *model.Bucket, err error) *BucketRepositoryMock {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("BucketRepositoryMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &BucketRepositoryMockCreateExpectation{mock: mmCreate.mock}
	}
	mmCreate.defaultExpectation.results = &BucketRepositoryMockCreateResults{bp1, err}
	mmCreate.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCreate.mock
}

// Set uses given function f to mock the BucketRepository.Create method
func (mmCreate *mBucketRepositoryMockCreate) Set(f func(ctx context.Context, name string, ownerID string) (bp1 *model.Bucket, err error)) *BucketRepositoryMock {
	if mmCreate.defaultExpectation != nil {
		mmCreate.mock.t.Fatalf("Default expectation is already set for the BucketRepository.Create method")
	}

	if len(mmCreate.expectations) > 0 {
		mmCreate.mock.t.Fatalf("Some expectations are already set for the BucketRepository.Create method")
	}

	mmCreate.mock.funcCreate = f
	mmCreate.mock.funcCreateOrigin = minimock.CallerInfo(1)
	return mmCreate.mock
}

// When sets expectation for the BucketRepository.Create which will trigger the result defined by the following
// Then helper
func (mmCreate *mBucketRepositoryMockCreate) When(ctx context.Context, name string, ownerID string) *BucketRepositoryMockCreateExpectation {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("BucketRepositoryMock.Create mock is already set by Set")
	}

	expectation := &BucketRepositoryMockCreateExpectation{
		mock:               mmCreate.mock,
		params:             &BucketRepositoryMockCreateParams{ctx, name, ownerID},
		expectationOrigins: BucketRepositoryMockCreateExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCreate.expectations = append(mmCreate.expectations, expectation)
	return expectation
}

// Then sets up BucketRepository.Create return parameters for the expectation previously defined by the When method
func (e *BucketRepositoryMockCreateExpectation) Then(bp1 *model.Bucket, err error) *BucketRepositoryMock {
	e.results = &BucketRepositoryMockCreateResults{bp1, err}
	return e.mock
}

// Times sets number of times BucketRepository.Create should be invoked
func (mmCreate *mBucketRepositoryMockCreate) Times(n uint64) *mBucketRepositoryMockCreate {
	if n == 0 {
		mmCreate.mock.t.Fatalf("Times of BucketRepositoryMock.Create mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCreate.expectedInvocations, n)
	mmCreate.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCreate
}

func (mmCreate *mBucketRepositoryMockCreate) invocationsDone() bool {
	if len(mmCreate.expectations) == 0 && mmCreate.defaultExpectation == nil && mmCreate.mock.funcCreate == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCreate.mock.afterCreateCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCreate.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Create implements mm_repository.BucketRepository
func (mmCreate *BucketRepositoryMock) Create(ctx context.Context, name string, ownerID string) (bp1 *model.Bucket, err error) {
	mm_atomic.AddUint64(&mmCreate.beforeCreateCounter, 1)
	defer mm_atomic.AddUint64(&mmCreate.afterCreateCounter, 1)

	mmCreate.t.Helper()

	if mmCreate.inspectFuncCreate != nil {
		mmCreate.inspectFuncCreate(ctx, name, ownerID)
	}

	mm_params := BucketRepositoryMockCreateParams{ctx, name, ownerID}

	// Record call args
	mmCreate.CreateMock.mutex.Lock()
	mmCreate.CreateMock.callArgs = append(mmCreate.CreateMock.callArgs, &mm_params)
	mmCreate.CreateMock.mutex.Unlock()

	for _, e := range mmCreate.CreateMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.bp1, e.results.err
		}
	}

	if mmCreate.CreateMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreate.CreateMock.defaultExpectation.Counter, 1)
		mm_want := mmCreate.CreateMock.defaultExpectation.params
		mm_want_ptrs := mmCreate.CreateMock.defaultExpectation.paramPtrs

		mm_got := BucketRepositoryMockCreateParams{ctx, name, ownerID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmCreate.t.Errorf("BucketRepositoryMock.Create got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreate.CreateMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.name != nil && !minimock.Equal(*mm_want_ptrs.name, mm_got.name) {
				mmCreate.t.Errorf("BucketRepositoryMock.Create got unexpected parameter name, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreate.CreateMock.defaultExpectation.expectationOrigins.originName, *mm_want_ptrs.name, mm_got.name, minimock.Diff(*mm_want_ptrs.name, mm_got.name))
			}

			if mm_want_ptrs.ownerID != nil && !minimock.Equal(*mm_want_ptrs.ownerID, mm_got.ownerID) {
				mmCreate.t.Errorf("BucketRepositoryMock.Create got unexpected parameter ownerID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreate.CreateMock.defaultExpectation.expectationOrigins.originOwnerID, *mm_want_ptrs.ownerID, mm_got.ownerID, minimock.Diff(*mm_want_ptrs.ownerID, mm_got.ownerID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreate.t.Errorf("BucketRepositoryMock.Create got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCreate.CreateMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreate.CreateMock.defaultExpectation.results
		if mm_results == nil {
			mmCreate.t.Fatal("No results are set for the BucketRepositoryMock.Create")
		}
		return (*mm_results).bp1, (*mm_results).err
	}
	if mmCreate.funcCreate != nil {
		return mmCreate.funcCreate(ctx, name, ownerID)
	}
	mmCreate.t.Fatalf("Unexpected call to BucketRepositoryMock.Create. %v %v %v", ctx, name, ownerID)
	return
}

// CreateAfterCounter returns a count of finished BucketRepositoryMock.Create invocations
func (mmCreate *BucketRepositoryMock) CreateAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreate.afterCreateCounter)
}

// CreateBeforeCounter returns a count of BucketRepositoryMock.Create invocations
func (mmCreate *BucketRepositoryMock) CreateBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreate.beforeCreateCounter)
}

// Calls returns a list of arguments used in each call to BucketRepositoryMock.Create.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreate *mBucketRepositoryMockCreate) Calls() []*BucketRepositoryMockCreateParams {
	mmCreate.mutex.RLock()

	argCopy := make([]*BucketRepositoryMockCreateParams, len(mmCreate.callArgs))
	copy(argCopy, mmCreate.callArgs)

	mmCreate.mutex.RUnlock()

	return argCopy
}

// MinimockCreateDone returns true if the count of the Create invocations corresponds
// the number of defined expectations
func (m *BucketRepositoryMock) MinimockCreateDone() bool {
	if m.CreateMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CreateMock.invocationsDone()
}

// MinimockCreateInspect logs each unmet expectation
func (m *BucketRepositoryMock) MinimockCreateInspect() {
	for _, e := range m.CreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to BucketRepositoryMock.Create at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCreateCounter := mm_atomic.LoadUint64(&m.afterCreateCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CreateMock.defaultExpectation != nil && afterCreateCounter < 1 {
		if m.CreateMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to BucketRepositoryMock.Create at\n%s", m.CreateMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to BucketRepositoryMock.Create at\n%s with params: %#v", m.CreateMock.defaultExpectation.expectationOrigins.origin, *m.CreateMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreate != nil && afterCreateCounter < 1 {
		m.t.Errorf("Expected call to BucketRepositoryMock.Create at\n%s", m.funcCreateOrigin)
	}

	if !m.CreateMock.invocationsDone() && afterCreateCounter > 0 {
		m.t.Errorf("Expected %d calls to BucketRepositoryMock.Create at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CreateMock.expectedInvocations), m.CreateMock.expectedInvocationsOrigin, afterCreateCounter)
	}
}

type mBucketRepositoryMockDelete struct {
	optional           bool
	mock               *BucketRepositoryMock
	defaultExpectation *BucketRepositoryMockDeleteExpectation
	expectations       []*BucketRepositoryMockDeleteExpectation

	callArgs []*BucketRepositoryMockDeleteParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// BucketRepositoryMockDeleteExpectation specifies expectation struct of the BucketRepository.Delete
type BucketRepositoryMockDeleteExpectation struct {
	mock               *BucketRepositoryMock
	params             *BucketRepositoryMockDeleteParams
	paramPtrs          *BucketRepositoryMockDeleteParamPtrs
	expectationOrigins BucketRepositoryMockDeleteExpectationOrigins
	results            *BucketRepositoryMockDeleteResults
	returnOrigin       string
	Counter            uint64
}

// BucketRepositoryMockDeleteParams contains parameters of the BucketRepository.Delete
type BucketRepositoryMockDeleteParams struct {
	ctx      context.Context
	bucketID string
}

// BucketRepositoryMockDeleteParamPtrs contains pointers to parameters of the BucketRepository.Delete
type BucketRepositoryMockDeleteParamPtrs struct {
	ctx      *context.Context
	bucketID *string
}

// BucketRepositoryMockDeleteResults contains results of the BucketRepository.Delete
type BucketRepositoryMockDeleteResults struct {
	err error
}

// BucketRepositoryMockDeleteOrigins contains origins of expectations of the BucketRepository.Delete
type BucketRepositoryMockDeleteExpectationOrigins struct {
	origin         string
	originCtx      string
	originBucketID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmDelete *mBucketRepositoryMockDelete) Optional() *mBucketRepositoryMockDelete {
	mmDelete.optional = true
	return mmDelete
}

// Expect sets up expected params for BucketRepository.Delete
func (mmDelete *mBucketRepositoryMockDelete) Expect(ctx context.Context, bucketID string) *mBucketRepositoryMockDelete {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("BucketRepositoryMock.Delete mock is already set by Set")
	}

	if mmDelete.defaultExpectation == nil {
		mmDelete.defaultExpectation = &BucketRepositoryMockDeleteExpectation{}
	}

	if mmDelete.defaultExpectation.paramPtrs != nil {
		mmDelete.mock.t.Fatalf("BucketRepositoryMock.Delete mock is already set by ExpectParams functions")
	}

	mmDelete.defaultExpectation.params = &BucketRepositoryMockDeleteParams{ctx, bucketID}
	mmDelete.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmDelete.expectations {
		if minimock.Equal(e.params, mmDelete.defaultExpectation.params) {
			mmDelete.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmDelete.defaultExpectation.params)
		}
	}

	return mmDelete
}

// ExpectCtxParam1 sets up expected param ctx for BucketRepository.Delete
func (mmDelete *mBucketRepositoryMockDelete) ExpectCtxParam1(ctx context.Context) *mBucketRepositoryMockDelete {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("BucketRepositoryMock.Delete mock is already set by Set")
	}

	if mmDelete.defaultExpectation == nil {
		mmDelete.defaultExpectation = &BucketRepositoryMockDeleteExpectation{}
	}

	if mmDelete.defaultExpectation.params != nil {
		mmDelete.mock.t.Fatalf("BucketRepositoryMock.Delete mock is already set by Expect")
	}

	if mmDelete.defaultExpectation.paramPtrs == nil {
		mmDelete.defaultExpectation.paramPtrs = &BucketRepositoryMockDeleteParamPtrs{}
	}
	mmDelete.defaultExpectation.paramPtrs.ctx = &ctx
	mmDelete.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmDelete
}

// ExpectBucketIDParam2 sets up expected param bucketID for BucketRepository.Delete
func (mmDelete *mBucketRepositoryMockDelete) ExpectBucketIDParam2(bucketID string) *mBucketRepositoryMockDelete {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("BucketRepositoryMock.Delete mock is already set by Set")
	}

	if mmDelete.defaultExpectation == nil {
		mmDelete.defaultExpectation = &BucketRepositoryMockDeleteExpectation{}
	}

	if mmDelete.defaultExpectation.params != nil {
		mmDelete.mock.t.Fatalf("BucketRepositoryMock.Delete mock is already set by Expect")
	}

	if mmDelete.defaultExpectation.paramPtrs == nil {
		mmDelete.defaultExpectation.paramPtrs = &BucketRepositoryMockDeleteParamPtrs{}
	}
	mmDelete.defaultExpectation.paramPtrs.bucketID = &bucketID
	mmDelete.defaultExpectation.expectationOrigins.originBucketID = minimock.CallerInfo(1)

	return mmDelete
}

// Inspect accepts an inspector function that has same arguments as the BucketRepository.Delete
func (mmDelete *mBucketRepositoryMockDelete) Inspect(f func(ctx context.Context, bucketID string)) *mBucketRepositoryMockDelete {
	if mmDelete.mock.inspectFuncDelete != nil {
		mmDelete.mock.t.Fatalf("Inspect function is already set for BucketRepositoryMock.Delete")
	}

	mmDelete.mock.inspectFuncDelete = f

	return mmDelete
}

// Return sets up results that will be returned by BucketRepository.Delete
func (mmDelete *mBucketRepositoryMockDelete) Return(err error) *BucketRepositoryMock {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("BucketRepositoryMock.Delete mock is already set by Set")
	}

	if mmDelete.defaultExpectation == nil {
		mmDelete.defaultExpectation = &BucketRepositoryMockDeleteExpectation{mock: mmDelete.mock}
	}
	mmDelete.defaultExpectation.results = &BucketRepositoryMockDeleteResults{err}
	mmDelete.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmDelete.mock
}

// Set uses given function f to mock the BucketRepository.Delete method
func (mmDelete *mBucketRepositoryMockDelete) Set(f func(ctx context.Context, bucketID string) (err error)) *BucketRepositoryMock {
	if mmDelete.defaultExpectation != nil {
		mmDelete.mock.t.Fatalf("Default expectation is already set for the BucketRepository.Delete method")
	}

	if len(mmDelete.expectations) > 0 {
		mmDelete.mock.t.Fatalf("Some expectations are already set for the BucketRepository.Delete method")
	}

	mmDelete.mock.funcDelete = f
	mmDelete.mock.funcDeleteOrigin = minimock.CallerInfo(1)
	return mmDelete.mock
}

// When sets expectation for the BucketRepository.Delete which will trigger the result defined by the following
// Then helper
func (mmDelete *mBucketRepositoryMockDelete) When(ctx context.Context, bucketID string) *BucketRepositoryMockDeleteExpectation {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("BucketRepositoryMock.Delete mock is already set by Set")
	}

	expectation := &BucketRepositoryMockDeleteExpectation{
		mock:               mmDelete.mock,
		params:             &BucketRepositoryMockDeleteParams{ctx, bucketID},
		expectationOrigins: BucketRepositoryMockDeleteExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmDelete.expectations = append(mmDelete.expectations, expectation)
	return expectation
}

// Then sets up BucketRepository.Delete return parameters for the expectation previously defined by the When method
func (e *BucketRepositoryMockDeleteExpectation) Then(err error) *BucketRepositoryMock {
	e.results = &BucketRepositoryMockDeleteResults{err}
	return e.mock
}

// Times sets number of times BucketRepository.Delete should be invoked
func (mmDelete *mBucketRepositoryMockDelete) Times(n uint64) *mBucketRepositoryMockDelete {
	if n == 0 {
		mmDelete.mock.t.Fatalf("Times of BucketRepositoryMock.Delete mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmDelete.expectedInvocations, n)
	mmDelete.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmDelete
}

func (mmDelete *mBucketRepositoryMockDelete) invocationsDone() bool {
	if len(mmDelete.expectations) == 0 && mmDelete.defaultExpectation == nil && mmDelete.mock.funcDelete == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmDelete.mock.afterDeleteCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmDelete.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Delete implements mm_repository.BucketRepository
func (mmDelete *BucketRepositoryMock) Delete(ctx context.Context, bucketID string) (err error) {
	mm_atomic.AddUint64(&mmDelete.beforeDeleteCounter, 1)
	defer mm_atomic.AddUint64(&mmDelete.afterDeleteCounter, 1)

	mmDelete.t.Helper()

	if mmDelete.inspectFuncDelete != nil {
		mmDelete.inspectFuncDelete(ctx, bucketID)
	}

	mm_params := BucketRepositoryMockDeleteParams{ctx, bucketID}

	// Record call args
	mmDelete.DeleteMock.mutex.Lock()
	mmDelete.DeleteMock.callArgs = append(mmDelete.DeleteMock.callArgs, &mm_params)
	mmDelete.DeleteMock.mutex.Unlock()

	for _, e := range mmDelete.DeleteMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmDelete.DeleteMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmDelete.DeleteMock.defaultExpectation.Counter, 1)
		mm_want := mmDelete.DeleteMock.defaultExpectation.params
		mm_want_ptrs := mmDelete.DeleteMock.defaultExpectation.paramPtrs

		mm_got := BucketRepositoryMockDeleteParams{ctx, bucketID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmDelete.t.Errorf("BucketRepositoryMock.Delete got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDelete.DeleteMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.bucketID != nil && !minimock.Equal(*mm_want_ptrs.bucketID, mm_got.bucketID) {
				mmDelete.t.Errorf("BucketRepositoryMock.Delete got unexpected parameter bucketID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDelete.DeleteMock.defaultExpectation.expectationOrigins.originBucketID, *mm_want_ptrs.bucketID, mm_got.bucketID, minimock.Diff(*mm_want_ptrs.bucketID, mm_got.bucketID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmDelete.t.Errorf("BucketRepositoryMock.Delete got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmDelete.DeleteMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmDelete.DeleteMock.defaultExpectation.results
		if mm_results == nil {
			mmDelete.t.Fatal("No results are set for the BucketRepositoryMock.Delete")
		}
		return (*mm_results).err
	}
	if mmDelete.funcDelete != nil {
		return mmDelete.funcDelete(ctx, bucketID)
	}
	mmDelete.t.Fatalf("Unexpected call to BucketRepositoryMock.Delete. %v %v", ctx, bucketID)
	return
}

// DeleteAfterCounter returns a count of finished BucketRepositoryMock.Delete invocations
func (mmDelete *BucketRepositoryMock) DeleteAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDelete.afterDeleteCounter)
}

// DeleteBeforeCounter returns a count of BucketRepositoryMock.Delete invocations
func (mmDelete *BucketRepositoryMock) DeleteBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDelete.beforeDeleteCounter)
}

// Calls returns a list of arguments used in each call to BucketRepositoryMock.Delete.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmDelete *mBucketRepositoryMockDelete) Calls() []*BucketRepositoryMockDeleteParams {
	mmDelete.mutex.RLock()

	argCopy := make([]*BucketRepositoryMockDeleteParams, len(mmDelete.callArgs))
	copy(argCopy, mmDelete.callArgs)

	mmDelete.mutex.RUnlock()

	return argCopy
}

// MinimockDeleteDone returns true if the count of the Delete invocations corresponds
// the number of defined expectations
func (m *BucketRepositoryMock) MinimockDeleteDone() bool {
	if m.DeleteMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.DeleteMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.DeleteMock.invocationsDone()
}

// MinimockDeleteInspect logs each unmet expectation
func (m *BucketRepositoryMock) MinimockDeleteInspect() {
	for _, e := range m.DeleteMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to BucketRepositoryMock.Delete at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterDeleteCounter := mm_atomic.LoadUint64(&m.afterDeleteCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.DeleteMock.defaultExpectation != nil && afterDeleteCounter < 1 {
		if m.DeleteMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to BucketRepositoryMock.Delete at\n%s", m.DeleteMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to BucketRepositoryMock.Delete at\n%s with params: %#v", m.DeleteMock.defaultExpectation.expectationOrigins.origin, *m.DeleteMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcDelete != nil && afterDeleteCounter < 1 {
		m.t.Errorf("Expected call to BucketRepositoryMock.Delete at\n%s", m.funcDeleteOrigin)
	}

	if !m.DeleteMock.invocationsDone() && afterDeleteCounter > 0 {
		m.t.Errorf("Expected %d calls to BucketRepositoryMock.Delete at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.DeleteMock.expectedInvocations), m.DeleteMock.expectedInvocationsOrigin, afterDeleteCounter)
	}
}

type mBucketRepositoryMockGet struct {
	optional           bool
	mock               *BucketRepositoryMock
	defaultExpectation *BucketRepositoryMockGetExpectation
	expectations       []*BucketRepositoryMockGetExpectation

	callArgs []*BucketRepositoryMockGetParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// BucketRepositoryMockGetExpectation specifies expectation struct of the BucketRepository.Get
type BucketRepositoryMockGetExpectation struct {
	mock               *BucketRepositoryMock
	params             *BucketRepositoryMockGetParams
	paramPtrs          *BucketRepositoryMockGetParamPtrs
	expectationOrigins BucketRepositoryMockGetExpectationOrigins
	results            *BucketRepositoryMockGetResults
	returnOrigin       string
	Counter            uint64
}

// BucketRepositoryMockGetParams contains parameters of the BucketRepository.Get
type BucketRepositoryMockGetParams struct {
	ctx  context.Context
	name string
}

// BucketRepositoryMockGetParamPtrs contains pointers to parameters of the BucketRepository.Get
type BucketRepositoryMockGetParamPtrs struct {
	ctx  *context.Context
	name *string
}

// BucketRepositoryMockGetResults contains results of the BucketRepository.Get
type BucketRepositoryMockGetResults struct {
	bp1 *model.Bucket
	err error
}

// BucketRepositoryMockGetOrigins contains origins of expectations of the BucketRepository.Get
type BucketRepositoryMockGetExpectationOrigins struct {
	origin     string
	originCtx  string
	originName string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGet *mBucketRepositoryMockGet) Optional() *mBucketRepositoryMockGet {
	mmGet.optional = true
	return mmGet
}

// Expect sets up expected params for BucketRepository.Get
func (mmGet *mBucketRepositoryMockGet) Expect(ctx context.Context, name string) *mBucketRepositoryMockGet {
	if mmGet.mock.funcGet != nil {
		mmGet.mock.t.Fatalf("BucketRepositoryMock.Get mock is already set by Set")
	}

	if mmGet.defaultExpectation == nil {
		mmGet.defaultExpectation = &BucketRepositoryMockGetExpectation{}
	}

	if mmGet.defaultExpectation.paramPtrs != nil {
		mmGet.mock.t.Fatalf("BucketRepositoryMock.Get mock is already set by ExpectParams functions")
	}

	mmGet.defaultExpectation.params = &BucketRepositoryMockGetParams{ctx, name}
	mmGet.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGet.expectations {
		if minimock.Equal(e.params, mmGet.defaultExpectation.params) {
			mmGet.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGet.defaultExpectation.params)
		}
	}

	return mmGet
}

// ExpectCtxParam1 sets up expected param ctx for BucketRepository.Get
func (mmGet *mBucketRepositoryMockGet) ExpectCtxParam1(ctx context.Context) *mBucketRepositoryMockGet {
	if mmGet.mock.funcGet != nil {
		mmGet.mock.t.Fatalf("BucketRepositoryMock.Get mock is already set by Set")
	}

	if mmGet.defaultExpectation == nil {
		mmGet.defaultExpectation = &BucketRepositoryMockGetExpectation{}
	}

	if mmGet.defaultExpectation.params != nil {
		mmGet.mock.t.Fatalf("BucketRepositoryMock.Get mock is already set by Expect")
	}

	if mmGet.defaultExpectation.paramPtrs == nil {
		mmGet.defaultExpectation.paramPtrs = &BucketRepositoryMockGetParamPtrs{}
	}
	mmGet.defaultExpectation.paramPtrs.ctx = &ctx
	mmGet.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGet
}

// ExpectNameParam2 sets up expected param name for BucketRepository.Get
func (mmGet *mBucketRepositoryMockGet) ExpectNameParam2(name string) *mBucketRepositoryMockGet {
	if mmGet.mock.funcGet != nil {
		mmGet.mock.t.Fatalf("BucketRepositoryMock.Get mock is already set by Set")
	}

	if mmGet.defaultExpectation == nil {
		mmGet.defaultExpectation = &BucketRepositoryMockGetExpectation{}
	}

	if mmGet.defaultExpectation.params != nil {
		mmGet.mock.t.Fatalf("BucketRepositoryMock.Get mock is already set by Expect")
	}

	if mmGet.defaultExpectation.paramPtrs == nil {
		mmGet.defaultExpectation.paramPtrs = &BucketRepositoryMockGetParamPtrs{}
	}
	mmGet.defaultExpectation.paramPtrs.name = &name
	mmGet.defaultExpectation.expectationOrigins.originName = minimock.CallerInfo(1)

	return mmGet
}

// Inspect accepts an inspector function that has same arguments as the BucketRepository.Get
func (mmGet *mBucketRepositoryMockGet) Inspect(f func(ctx context.Context, name string)) *mBucketRepositoryMockGet {
	if mmGet.mock.inspectFuncGet != nil {
		mmGet.mock.t.Fatalf("Inspect function is already set for BucketRepositoryMock.Get")
	}

	mmGet.mock.inspectFuncGet = f

	return mmGet
}

// Return sets up results that will be returned by BucketRepository.Get
func (mmGet *mBucketRepositoryMockGet) Return(bp1 *model.Bucket, err error) *BucketRepositoryMock {
	if mmGet.mock.funcGet != nil {
		mmGet.mock.t.Fatalf("BucketRepositoryMock.Get mock is already set by Set")
	}

	if mmGet.defaultExpectation == nil {
		mmGet.defaultExpectation = &BucketRepositoryMockGetExpectation{mock: mmGet.mock}
	}
	mmGet.defaultExpectation.results = &BucketRepositoryMockGetResults{bp1, err}
	mmGet.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGet.mock
}

// Set uses given function f to mock the BucketRepository.Get method
func (mmGet *mBucketRepositoryMockGet) Set(f func(ctx context.Context, name string) (bp1 *model.Bucket, err error)) *BucketRepositoryMock {
	if mmGet.defaultExpectation != nil {
		mmGet.mock.t.Fatalf("Default expectation is already set for the BucketRepository.Get method")
	}

	if len(mmGet.expectations) > 0 {
		mmGet.mock.t.Fatalf("Some expectations are already set for the BucketRepository.Get method")
	}

	mmGet.mock.funcGet = f
	mmGet.mock.funcGetOrigin = minimock.CallerInfo(1)
	return mmGet.mock
}

// When sets expectation for the BucketRepository.Get which will trigger the result defined by the following
// Then helper
func (mmGet *mBucketRepositoryMockGet) When(ctx context.Context, name string) *BucketRepositoryMockGetExpectation {
	if mmGet.mock.funcGet != nil {
		mmGet.mock.t.Fatalf("BucketRepositoryMock.Get mock is already set by Set")
	}

	expectation := &BucketRepositoryMockGetExpectation{
		mock:               mmGet.mock,
		params:             &BucketRepositoryMockGetParams{ctx, name},
		expectationOrigins: BucketRepositoryMockGetExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGet.expectations = append(mmGet.expectations, expectation)
	return expectation
}

// Then sets up BucketRepository.Get return parameters for the expectation previously defined by the When method
func (e *BucketRepositoryMockGetExpectation) Then(bp1 *model.Bucket, err error) *BucketRepositoryMock {
	e.results = &BucketRepositoryMockGetResults{bp1, err}
	return e.mock
}

// Times sets number of times BucketRepository.Get should be invoked
func (mmGet *mBucketRepositoryMockGet) Times(n uint64) *mBucketRepositoryMockGet {
	if n == 0 {
		mmGet.mock.t.Fatalf("Times of BucketRepositoryMock.Get mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGet.expectedInvocations, n)
	mmGet.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGet
}

func (mmGet *mBucketRepositoryMockGet) invocationsDone() bool {
	if len(mmGet.expectations) == 0 && mmGet.defaultExpectation == nil && mmGet.mock.funcGet == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGet.mock.afterGetCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGet.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Get implements mm_repository.BucketRepository
func (mmGet *BucketRepositoryMock) Get(ctx context.Context, name string) (bp1 *model.Bucket, err error) {
	mm_atomic.AddUint64(&mmGet.beforeGetCounter, 1)
	defer mm_atomic.AddUint64(&mmGet.afterGetCounter, 1)

	mmGet.t.Helper()

	if mmGet.inspectFuncGet != nil {
		mmGet.inspectFuncGet(ctx, name)
	}

	mm_params := BucketRepositoryMockGetParams{ctx, name}

	// Record call args
	mmGet.GetMock.mutex.Lock()
	mmGet.GetMock.callArgs = append(mmGet.GetMock.callArgs, &mm_params)
	mmGet.GetMock.mutex.Unlock()

	for _, e := range mmGet.GetMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.bp1, e.results.err
		}
	}

	if mmGet.GetMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGet.GetMock.defaultExpectation.Counter, 1)
		mm_want := mmGet.GetMock.defaultExpectation.params
		mm_want_ptrs := mmGet.GetMock.defaultExpectation.paramPtrs

		mm_got := BucketRepositoryMockGetParams{ctx, name}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGet.t.Errorf("BucketRepositoryMock.Get got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGet.GetMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.name != nil && !minimock.Equal(*mm_want_ptrs.name, mm_got.name) {
				mmGet.t.Errorf("BucketRepositoryMock.Get got unexpected parameter name, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGet.GetMock.defaultExpectation.expectationOrigins.originName, *mm_want_ptrs.name, mm_got.name, minimock.Diff(*mm_want_ptrs.name, mm_got.name))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGet.t.Errorf("BucketRepositoryMock.Get got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGet.GetMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGet.GetMock.defaultExpectation.results
		if mm_results == nil {
			mmGet.t.Fatal("No results are set for the BucketRepositoryMock.Get")
		}
		return (*mm_results).bp1, (*mm_results).err
	}
	if mmGet.funcGet != nil {
		return mmGet.funcGet(ctx, name)
	}
	mmGet.t.Fatalf("Unexpected call to BucketRepositoryMock.Get. %v %v", ctx, name)
	return
}

// GetAfterCounter returns a count of finished BucketRepositoryMock.Get invocations
func (mmGet *BucketRepositoryMock) GetAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGet.afterGetCounter)
}

// GetBeforeCounter returns a count of BucketRepositoryMock.Get invocations
func (mmGet *BucketRepositoryMock) GetBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGet.beforeGetCounter)
}

// Calls returns a list of arguments used in each call to BucketRepositoryMock.Get.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGet *mBucketRepositoryMockGet) Calls() []*BucketRepositoryMockGetParams {
	mmGet.mutex.RLock()

	argCopy := make([]*BucketRepositoryMockGetParams, len(mmGet.callArgs))
	copy(argCopy, mmGet.callArgs)

	mmGet.mutex.RUnlock()

	return argCopy
}

// MinimockGetDone returns true if the count of the Get invocations corresponds
// the number of defined expectations
func (m *BucketRepositoryMock) MinimockGetDone() bool {
	if m.GetMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetMock.invocationsDone()
}

// MinimockGetInspect logs each unmet expectation
func (m *BucketRepositoryMock) MinimockGetInspect() {
	for _, e := range m.GetMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to BucketRepositoryMock.Get at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetCounter := mm_atomic.LoadUint64(&m.afterGetCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetMock.defaultExpectation != nil && afterGetCounter < 1 {
		if m.GetMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to BucketRepositoryMock.Get at\n%s", m.GetMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to BucketRepositoryMock.Get at\n%s with params: %#v", m.GetMock.defaultExpectation.expectationOrigins.origin, *m.GetMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGet != nil && afterGetCounter < 1 {
		m.t.Errorf("Expected call to BucketRepositoryMock.Get at\n%s", m.funcGetOrigin)
	}

	if !m.GetMock.invocationsDone() && afterGetCounter > 0 {
		m.t.Errorf("Expected %d calls to BucketRepositoryMock.Get at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetMock.expectedInvocations), m.GetMock.expectedInvocationsOrigin, afterGetCounter)
	}
}

type mBucketRepositoryMockHead struct {
	optional           bool
	mock               *BucketRepositoryMock
	defaultExpectation *BucketRepositoryMockHeadExpectation
	expectations       []*BucketRepositoryMockHeadExpectation

	callArgs []*BucketRepositoryMockHeadParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// BucketRepositoryMockHeadExpectation specifies expectation struct of the BucketRepository.Head
type BucketRepositoryMockHeadExpectation struct {
	mock               *BucketRepositoryMock
	params             *BucketRepositoryMockHeadParams
	paramPtrs          *BucketRepositoryMockHeadParamPtrs
	expectationOrigins BucketRepositoryMockHeadExpectationOrigins
	results            *BucketRepositoryMockHeadResults
	returnOrigin       string
	Counter            uint64
}

// BucketRepositoryMockHeadParams contains parameters of the BucketRepository.Head
type BucketRepositoryMockHeadParams struct {
	ctx  context.Context
	name string
}

// BucketRepositoryMockHeadParamPtrs contains pointers to parameters of the BucketRepository.Head
type BucketRepositoryMockHeadParamPtrs struct {
	ctx  *context.Context
	name *string
}

// BucketRepositoryMockHeadResults contains results of the BucketRepository.Head
type BucketRepositoryMockHeadResults struct {
	b1  bool
	s1  string
	s2  string
	err error
}

// BucketRepositoryMockHeadOrigins contains origins of expectations of the BucketRepository.Head
type BucketRepositoryMockHeadExpectationOrigins struct {
	origin     string
	originCtx  string
	originName string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmHead *mBucketRepositoryMockHead) Optional() *mBucketRepositoryMockHead {
	mmHead.optional = true
	return mmHead
}

// Expect sets up expected params for BucketRepository.Head
func (mmHead *mBucketRepositoryMockHead) Expect(ctx context.Context, name string) *mBucketRepositoryMockHead {
	if mmHead.mock.funcHead != nil {
		mmHead.mock.t.Fatalf("BucketRepositoryMock.Head mock is already set by Set")
	}

	if mmHead.defaultExpectation == nil {
		mmHead.defaultExpectation = &BucketRepositoryMockHeadExpectation{}
	}

	if mmHead.defaultExpectation.paramPtrs != nil {
		mmHead.mock.t.Fatalf("BucketRepositoryMock.Head mock is already set by ExpectParams functions")
	}

	mmHead.defaultExpectation.params = &BucketRepositoryMockHeadParams{ctx, name}
	mmHead.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmHead.expectations {
		if minimock.Equal(e.params, mmHead.defaultExpectation.params) {
			mmHead.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmHead.defaultExpectation.params)
		}
	}

	return mmHead
}

// ExpectCtxParam1 sets up expected param ctx for BucketRepository.Head
func (mmHead *mBucketRepositoryMockHead) ExpectCtxParam1(ctx context.Context) *mBucketRepositoryMockHead {
	if mmHead.mock.funcHead != nil {
		mmHead.mock.t.Fatalf("BucketRepositoryMock.Head mock is already set by Set")
	}

	if mmHead.defaultExpectation == nil {
		mmHead.defaultExpectation = &BucketRepositoryMockHeadExpectation{}
	}

	if mmHead.defaultExpectation.params != nil {
		mmHead.mock.t.Fatalf("BucketRepositoryMock.Head mock is already set by Expect")
	}

	if mmHead.defaultExpectation.paramPtrs == nil {
		mmHead.defaultExpectation.paramPtrs = &BucketRepositoryMockHeadParamPtrs{}
	}
	mmHead.defaultExpectation.paramPtrs.ctx = &ctx
	mmHead.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmHead
}

// ExpectNameParam2 sets up expected param name for BucketRepository.Head
func (mmHead *mBucketRepositoryMockHead) ExpectNameParam2(name string) *mBucketRepositoryMockHead {
	if mmHead.mock.funcHead != nil {
		mmHead.mock.t.Fatalf("BucketRepositoryMock.Head mock is already set by Set")
	}

	if mmHead.defaultExpectation == nil {
		mmHead.defaultExpectation = &BucketRepositoryMockHeadExpectation{}
	}

	if mmHead.defaultExpectation.params != nil {
		mmHead.mock.t.Fatalf("BucketRepositoryMock.Head mock is already set by Expect")
	}

	if mmHead.defaultExpectation.paramPtrs == nil {
		mmHead.defaultExpectation.paramPtrs = &BucketRepositoryMockHeadParamPtrs{}
	}
	mmHead.defaultExpectation.paramPtrs.name = &name
	mmHead.defaultExpectation.expectationOrigins.originName = minimock.CallerInfo(1)

	return mmHead
}

// Inspect accepts an inspector function that has same arguments as the BucketRepository.Head
func (mmHead *mBucketRepositoryMockHead) Inspect(f func(ctx context.Context, name string)) *mBucketRepositoryMockHead {
	if mmHead.mock.inspectFuncHead != nil {
		mmHead.mock.t.Fatalf("Inspect function is already set for BucketRepositoryMock.Head")
	}

	mmHead.mock.inspectFuncHead = f

	return mmHead
}

// Return sets up results that will be returned by BucketRepository.Head
func (mmHead *mBucketRepositoryMockHead) Return(b1 bool, s1 string, s2 string, err error) *BucketRepositoryMock {
	if mmHead.mock.funcHead != nil {
		mmHead.mock.t.Fatalf("BucketRepositoryMock.Head mock is already set by Set")
	}

	if mmHead.defaultExpectation == nil {
		mmHead.defaultExpectation = &BucketRepositoryMockHeadExpectation{mock: mmHead.mock}
	}
	mmHead.defaultExpectation.results = &BucketRepositoryMockHeadResults{b1, s1, s2, err}
	mmHead.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmHead.mock
}

// Set uses given function f to mock the BucketRepository.Head method
func (mmHead *mBucketRepositoryMockHead) Set(f func(ctx context.Context, name string) (b1 bool, s1 string, s2 string, err error)) *BucketRepositoryMock {
	if mmHead.defaultExpectation != nil {
		mmHead.mock.t.Fatalf("Default expectation is already set for the BucketRepository.Head method")
	}

	if len(mmHead.expectations) > 0 {
		mmHead.mock.t.Fatalf("Some expectations are already set for the BucketRepository.Head method")
	}

	mmHead.mock.funcHead = f
	mmHead.mock.funcHeadOrigin = minimock.CallerInfo(1)
	return mmHead.mock
}

// When sets expectation for the BucketRepository.Head which will trigger the result defined by the following
// Then helper
func (mmHead *mBucketRepositoryMockHead) When(ctx context.Context, name string) *BucketRepositoryMockHeadExpectation {
	if mmHead.mock.funcHead != nil {
		mmHead.mock.t.Fatalf("BucketRepositoryMock.Head mock is already set by Set")
	}

	expectation := &BucketRepositoryMockHeadExpectation{
		mock:               mmHead.mock,
		params:             &BucketRepositoryMockHeadParams{ctx, name},
		expectationOrigins: BucketRepositoryMockHeadExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmHead.expectations = append(mmHead.expectations, expectation)
	return expectation
}

// Then sets up BucketRepository.Head return parameters for the expectation previously defined by the When method
func (e *BucketRepositoryMockHeadExpectation) Then(b1 bool, s1 string, s2 string, err error) *BucketRepositoryMock {
	e.results = &BucketRepositoryMockHeadResults{b1, s1, s2, err}
	return e.mock
}

// Times sets number of times BucketRepository.Head should be invoked
func (mmHead *mBucketRepositoryMockHead) Times(n uint64) *mBucketRepositoryMockHead {
	if n == 0 {
		mmHead.mock.t.Fatalf("Times of BucketRepositoryMock.Head mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmHead.expectedInvocations, n)
	mmHead.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmHead
}

func (mmHead *mBucketRepositoryMockHead) invocationsDone() bool {
	if len(mmHead.expectations) == 0 && mmHead.defaultExpectation == nil && mmHead.mock.funcHead == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmHead.mock.afterHeadCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmHead.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Head implements mm_repository.BucketRepository
func (mmHead *BucketRepositoryMock) Head(ctx context.Context, name string) (b1 bool, s1 string, s2 string, err error) {
	mm_atomic.AddUint64(&mmHead.beforeHeadCounter, 1)
	defer mm_atomic.AddUint64(&mmHead.afterHeadCounter, 1)

	mmHead.t.Helper()

	if mmHead.inspectFuncHead != nil {
		mmHead.inspectFuncHead(ctx, name)
	}

	mm_params := BucketRepositoryMockHeadParams{ctx, name}

	// Record call args
	mmHead.HeadMock.mutex.Lock()
	mmHead.HeadMock.callArgs = append(mmHead.HeadMock.callArgs, &mm_params)
	mmHead.HeadMock.mutex.Unlock()

	for _, e := range mmHead.HeadMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.b1, e.results.s1, e.results.s2, e.results.err
		}
	}

	if mmHead.HeadMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmHead.HeadMock.defaultExpectation.Counter, 1)
		mm_want := mmHead.HeadMock.defaultExpectation.params
		mm_want_ptrs := mmHead.HeadMock.defaultExpectation.paramPtrs

		mm_got := BucketRepositoryMockHeadParams{ctx, name}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmHead.t.Errorf("BucketRepositoryMock.Head got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmHead.HeadMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.name != nil && !minimock.Equal(*mm_want_ptrs.name, mm_got.name) {
				mmHead.t.Errorf("BucketRepositoryMock.Head got unexpected parameter name, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmHead.HeadMock.defaultExpectation.expectationOrigins.originName, *mm_want_ptrs.name, mm_got.name, minimock.Diff(*mm_want_ptrs.name, mm_got.name))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmHead.t.Errorf("BucketRepositoryMock.Head got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmHead.HeadMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmHead.HeadMock.defaultExpectation.results
		if mm_results == nil {
			mmHead.t.Fatal("No results are set for the BucketRepositoryMock.Head")
		}
		return (*mm_results).b1, (*mm_results).s1, (*mm_results).s2, (*mm_results).err
	}
	if mmHead.funcHead != nil {
		return mmHead.funcHead(ctx, name)
	}
	mmHead.t.Fatalf("Unexpected call to BucketRepositoryMock.Head. %v %v", ctx, name)
	return
}

// HeadAfterCounter returns a count of finished BucketRepositoryMock.Head invocations
func (mmHead *BucketRepositoryMock) HeadAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmHead.afterHeadCounter)
}

// HeadBeforeCounter returns a count of BucketRepositoryMock.Head invocations
func (mmHead *BucketRepositoryMock) HeadBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmHead.beforeHeadCounter)
}

// Calls returns a list of arguments used in each call to BucketRepositoryMock.Head.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmHead *mBucketRepositoryMockHead) Calls() []*BucketRepositoryMockHeadParams {
	mmHead.mutex.RLock()

	argCopy := make([]*BucketRepositoryMockHeadParams, len(mmHead.callArgs))
	copy(argCopy, mmHead.callArgs)

	mmHead.mutex.RUnlock()

	return argCopy
}

// MinimockHeadDone returns true if the count of the Head invocations corresponds
// the number of defined expectations
func (m *BucketRepositoryMock) MinimockHeadDone() bool {
	if m.HeadMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.HeadMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.HeadMock.invocationsDone()
}

// MinimockHeadInspect logs each unmet expectation
func (m *BucketRepositoryMock) MinimockHeadInspect() {
	for _, e := range m.HeadMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to BucketRepositoryMock.Head at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterHeadCounter := mm_atomic.LoadUint64(&m.afterHeadCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.HeadMock.defaultExpectation != nil && afterHeadCounter < 1 {
		if m.HeadMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to BucketRepositoryMock.Head at\n%s", m.HeadMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to BucketRepositoryMock.Head at\n%s with params: %#v", m.HeadMock.defaultExpectation.expectationOrigins.origin, *m.HeadMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcHead != nil && afterHeadCounter < 1 {
		m.t.Errorf("Expected call to BucketRepositoryMock.Head at\n%s", m.funcHeadOrigin)
	}

	if !m.HeadMock.invocationsDone() && afterHeadCounter > 0 {
		m.t.Errorf("Expected %d calls to BucketRepositoryMock.Head at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.HeadMock.expectedInvocations), m.HeadMock.expectedInvocationsOrigin, afterHeadCounter)
	}
}

type mBucketRepositoryMockList struct {
	optional           bool
	mock               *BucketRepositoryMock
	defaultExpectation *BucketRepositoryMockListExpectation
	expectations       []*BucketRepositoryMockListExpectation

	callArgs []*BucketRepositoryMockListParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// BucketRepositoryMockListExpectation specifies expectation struct of the BucketRepository.List
type BucketRepositoryMockListExpectation struct {
	mock               *BucketRepositoryMock
	params             *BucketRepositoryMockListParams
	paramPtrs          *BucketRepositoryMockListParamPtrs
	expectationOrigins BucketRepositoryMockListExpectationOrigins
	results            *BucketRepositoryMockListResults
	returnOrigin       string
	Counter            uint64
}

// BucketRepositoryMockListParams contains parameters of the BucketRepository.List
type BucketRepositoryMockListParams struct {
	ctx     context.Context
	ownerID string
}

// BucketRepositoryMockListParamPtrs contains pointers to parameters of the BucketRepository.List
type BucketRepositoryMockListParamPtrs struct {
	ctx     *context.Context
	ownerID *string
}

// BucketRepositoryMockListResults contains results of the BucketRepository.List
type BucketRepositoryMockListResults struct {
	bpa1 []*model.Bucket
	err  error
}

// BucketRepositoryMockListOrigins contains origins of expectations of the BucketRepository.List
type BucketRepositoryMockListExpectationOrigins struct {
	origin        string
	originCtx     string
	originOwnerID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmList *mBucketRepositoryMockList) Optional() *mBucketRepositoryMockList {
	mmList.optional = true
	return mmList
}

// Expect sets up expected params for BucketRepository.List
func (mmList *mBucketRepositoryMockList) Expect(ctx context.Context, ownerID string) *mBucketRepositoryMockList {
	if mmList.mock.funcList != nil {
		mmList.mock.t.Fatalf("BucketRepositoryMock.List mock is already set by Set")
	}

	if mmList.defaultExpectation == nil {
		mmList.defaultExpectation = &BucketRepositoryMockListExpectation{}
	}

	if mmList.defaultExpectation.paramPtrs != nil {
		mmList.mock.t.Fatalf("BucketRepositoryMock.List mock is already set by ExpectParams functions")
	}

	mmList.defaultExpectation.params = &BucketRepositoryMockListParams{ctx, ownerID}
	mmList.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmList.expectations {
		if minimock.Equal(e.params, mmList.defaultExpectation.params) {
			mmList.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmList.defaultExpectation.params)
		}
	}

	return mmList
}

// ExpectCtxParam1 sets up expected param ctx for BucketRepository.List
func (mmList *mBucketRepositoryMockList) ExpectCtxParam1(ctx context.Context) *mBucketRepositoryMockList {
	if mmList.mock.funcList != nil {
		mmList.mock.t.Fatalf("BucketRepositoryMock.List mock is already set by Set")
	}

	if mmList.defaultExpectation == nil {
		mmList.defaultExpectation = &BucketRepositoryMockListExpectation{}
	}

	if mmList.defaultExpectation.params != nil {
		mmList.mock.t.Fatalf("BucketRepositoryMock.List mock is already set by Expect")
	}

	if mmList.defaultExpectation.paramPtrs == nil {
		mmList.defaultExpectation.paramPtrs = &BucketRepositoryMockListParamPtrs{}
	}
	mmList.defaultExpectation.paramPtrs.ctx = &ctx
	mmList.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmList
}

// ExpectOwnerIDParam2 sets up expected param ownerID for BucketRepository.List
func (mmList *mBucketRepositoryMockList) ExpectOwnerIDParam2(ownerID string) *mBucketRepositoryMockList {
	if mmList.mock.funcList != nil {
		mmList.mock.t.Fatalf("BucketRepositoryMock.List mock is already set by Set")
	}

	if mmList.defaultExpectation == nil {
		mmList.defaultExpectation = &BucketRepositoryMockListExpectation{}
	}

	if mmList.defaultExpectation.params != nil {
		mmList.mock.t.Fatalf("BucketRepositoryMock.List mock is already set by Expect")
	}

	if mmList.defaultExpectation.paramPtrs == nil {
		mmList.defaultExpectation.paramPtrs = &BucketRepositoryMockListParamPtrs{}
	}
	mmList.defaultExpectation.paramPtrs.ownerID = &ownerID
	mmList.defaultExpectation.expectationOrigins.originOwnerID = minimock.CallerInfo(1)

	return mmList
}

// Inspect accepts an inspector function that has same arguments as the BucketRepository.List
func (mmList *mBucketRepositoryMockList) Inspect(f func(ctx context.Context, ownerID string)) *mBucketRepositoryMockList {
	if mmList.mock.inspectFuncList != nil {
		mmList.mock.t.Fatalf("Inspect function is already set for BucketRepositoryMock.List")
	}

	mmList.mock.inspectFuncList = f

	return mmList
}

// Return sets up results that will be returned by BucketRepository.List
func (mmList *mBucketRepositoryMockList) Return(bpa1 []*model.Bucket, err error) *BucketRepositoryMock {
	if mmList.mock.funcList != nil {
		mmList.mock.t.Fatalf("BucketRepositoryMock.List mock is already set by Set")
	}

	if mmList.defaultExpectation == nil {
		mmList.defaultExpectation = &BucketRepositoryMockListExpectation{mock: mmList.mock}
	}
	mmList.defaultExpectation.results = &BucketRepositoryMockListResults{bpa1, err}
	mmList.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmList.mock
}

// Set uses given function f to mock the BucketRepository.List method
func (mmList *mBucketRepositoryMockList) Set(f func(ctx context.Context, ownerID string) (bpa1 []*model.Bucket, err error)) *BucketRepositoryMock {
	if mmList.defaultExpectation != nil {
		mmList.mock.t.Fatalf("Default expectation is already set for the BucketRepository.List method")
	}

	if len(mmList.expectations) > 0 {
		mmList.mock.t.Fatalf("Some expectations are already set for the BucketRepository.List method")
	}

	mmList.mock.funcList = f
	mmList.mock.funcListOrigin = minimock.CallerInfo(1)
	return mmList.mock
}

// When sets expectation for the BucketRepository.List which will trigger the result defined by the following
// Then helper
func (mmList *mBucketRepositoryMockList) When(ctx context.Context, ownerID string) *BucketRepositoryMockListExpectation {
	if mmList.mock.funcList != nil {
		mmList.mock.t.Fatalf("BucketRepositoryMock.List mock is already set by Set")
	}

	expectation := &BucketRepositoryMockListExpectation{
		mock:               mmList.mock,
		params:             &BucketRepositoryMockListParams{ctx, ownerID},
		expectationOrigins: BucketRepositoryMockListExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmList.expectations = append(mmList.expectations, expectation)
	return expectation
}

// Then sets up BucketRepository.List return parameters for the expectation previously defined by the When method
func (e *BucketRepositoryMockListExpectation) Then(bpa1 []*model.Bucket, err error) *BucketRepositoryMock {
	e.results = &BucketRepositoryMockListResults{bpa1, err}
	return e.mock
}

// Times sets number of times BucketRepository.List should be invoked
func (mmList *mBucketRepositoryMockList) Times(n uint64) *mBucketRepositoryMockList {
	if n == 0 {
		mmList.mock.t.Fatalf("Times of BucketRepositoryMock.List mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmList.expectedInvocations, n)
	mmList.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmList
}

func (mmList *mBucketRepositoryMockList) invocationsDone() bool {
	if len(mmList.expectations) == 0 && mmList.defaultExpectation == nil && mmList.mock.funcList == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmList.mock.afterListCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmList.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// List implements mm_repository.BucketRepository
func (mmList *BucketRepositoryMock) List(ctx context.Context, ownerID string) (bpa1 []*model.Bucket, err error) {
	mm_atomic.AddUint64(&mmList.beforeListCounter, 1)
	defer mm_atomic.AddUint64(&mmList.afterListCounter, 1)

	mmList.t.Helper()

	if mmList.inspectFuncList != nil {
		mmList.inspectFuncList(ctx, ownerID)
	}

	mm_params := BucketRepositoryMockListParams{ctx, ownerID}

	// Record call args
	mmList.ListMock.mutex.Lock()
	mmList.ListMock.callArgs = append(mmList.ListMock.callArgs, &mm_params)
	mmList.ListMock.mutex.Unlock()

	for _, e := range mmList.ListMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.bpa1, e.results.err
		}
	}

	if mmList.ListMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmList.ListMock.defaultExpectation.Counter, 1)
		mm_want := mmList.ListMock.defaultExpectation.params
		mm_want_ptrs := mmList.ListMock.defaultExpectation.paramPtrs

		mm_got := BucketRepositoryMockListParams{ctx, ownerID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmList.t.Errorf("BucketRepositoryMock.List got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmList.ListMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.ownerID != nil && !minimock.Equal(*mm_want_ptrs.ownerID, mm_got.ownerID) {
				mmList.t.Errorf("BucketRepositoryMock.List got unexpected parameter ownerID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmList.ListMock.defaultExpectation.expectationOrigins.originOwnerID, *mm_want_ptrs.ownerID, mm_got.ownerID, minimock.Diff(*mm_want_ptrs.ownerID, mm_got.ownerID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmList.t.Errorf("BucketRepositoryMock.List got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmList.ListMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmList.ListMock.defaultExpectation.results
		if mm_results == nil {
			mmList.t.Fatal("No results are set for the BucketRepositoryMock.List")
		}
		return (*mm_results).bpa1, (*mm_results).err
	}
	if mmList.funcList != nil {
		return mmList.funcList(ctx, ownerID)
	}
	mmList.t.Fatalf("Unexpected call to BucketRepositoryMock.List. %v %v", ctx, ownerID)
	return
}

// ListAfterCounter returns a count of finished BucketRepositoryMock.List invocations
func (mmList *BucketRepositoryMock) ListAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmList.afterListCounter)
}

// ListBeforeCounter returns a count of BucketRepositoryMock.List invocations
func (mmList *BucketRepositoryMock) ListBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmList.beforeListCounter)
}

// Calls returns a list of arguments used in each call to BucketRepositoryMock.List.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmList *mBucketRepositoryMockList) Calls() []*BucketRepositoryMockListParams {
	mmList.mutex.RLock()

	argCopy := make([]*BucketRepositoryMockListParams, len(mmList.callArgs))
	copy(argCopy, mmList.callArgs)

	mmList.mutex.RUnlock()

	return argCopy
}

// MinimockListDone returns true if the count of the List invocations corresponds
// the number of defined expectations
func (m *BucketRepositoryMock) MinimockListDone() bool {
	if m.ListMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.ListMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.ListMock.invocationsDone()
}

// MinimockListInspect logs each unmet expectation
func (m *BucketRepositoryMock) MinimockListInspect() {
	for _, e := range m.ListMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to BucketRepositoryMock.List at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterListCounter := mm_atomic.LoadUint64(&m.afterListCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.ListMock.defaultExpectation != nil && afterListCounter < 1 {
		if m.ListMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to BucketRepositoryMock.List at\n%s", m.ListMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to BucketRepositoryMock.List at\n%s with params: %#v", m.ListMock.defaultExpectation.expectationOrigins.origin, *m.ListMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcList != nil && afterListCounter < 1 {
		m.t.Errorf("Expected call to BucketRepositoryMock.List at\n%s", m.funcListOrigin)
	}

	if !m.ListMock.invocationsDone() && afterListCounter > 0 {
		m.t.Errorf("Expected %d calls to BucketRepositoryMock.List at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.ListMock.expectedInvocations), m.ListMock.expectedInvocationsOrigin, afterListCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *BucketRepositoryMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockCountObjectsInspect()

			m.MinimockCreateInspect()

			m.MinimockDeleteInspect()

			m.MinimockGetInspect()

			m.MinimockHeadInspect()

			m.MinimockListInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *BucketRepositoryMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *BucketRepositoryMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCountObjectsDone() &&
		m.MinimockCreateDone() &&
		m.MinimockDeleteDone() &&
		m.MinimockGetDone() &&
		m.MinimockHeadDone() &&
		m.MinimockListDone()
}
