name: Storage CI

on:
  push:
    paths:
      - "services/storage/**"
      - "shared/pkg/go/storage/**"
  pull_request:
    paths:
      - "services/storage/**"
      - "shared/pkg/go/storage/**"

defaults:
  run:
    working-directory: services/storage

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'

      - name: Run tests
        run: go test ./... -count=1
